import assert from 'node:assert/strict';
const base='http://127.0.0.1:5173/api/flock';const post=async(action,data,year='2026')=>{const r=await fetch(base,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data,year})});return {status:r.status,data:await r.json()}};const read=async()=>await(await fetch(base)).json();
const ids=Array.from({length:6},()=>crypto.randomUUID());const [sire,dam,child,goat,invalid,ancestor]=ids;
const create=(id,extra={},year='2026')=>post('animal',{id,species:'Sheep',name:'Phase 1 local QA',sex:'Unknown',origin:'Purchased',firstYear:Number(year),birthYear:null,...extra},year);
assert.equal((await create(sire,{sex:'Male',dob:'2020-01-01'})).status,200);assert.equal((await create(dam,{sex:'Female',birthYear:2020})).status,200);
assert.equal((await create(goat,{species:'Goats',sex:'Male'})).status,200);
assert.equal((await create(invalid,{sire:goat})).status,400);
assert.equal((await create(invalid,{sire,birthYear:2019})).status,400);
assert.equal((await create(invalid,{dam,birthYear:null,dob:'2019-01-01'})).status,400);
assert.equal((await create(child,{sex:'Male',sire,dam,birthYear:2025,eid:child.replaceAll('-','').slice(0,15)},'2025')).status,200);
assert.equal((await create(crypto.randomUUID(),{eid:child.replaceAll('-','').slice(0,15)})).status,409);
assert.equal((await create(crypto.randomUUID(),{},'all')).status,400);
const weight={id:crypto.randomUUID(),animalId:child,date:'2025-06-01',originalValue:100,unit:'lb',session:'Phase1 QA'};assert.equal((await post('weight',weight,'2025')).status,200);assert.equal((await post('weight',weight,'2025')).status,200);assert.equal((await post('weight',{...weight,id:crypto.randomUUID()},'2025')).status,409);
assert.equal((await post('weight',{...weight,id:crypto.randomUUID(),date:'2026-06-01',originalValue:50,unit:'kg'})).status,200);
let result=await read(),a=result.animals.find(a=>a.id===child);assert.equal(a.sire,sire);assert.equal(a.dam,dam);assert.equal(result.weights.filter(w=>w.animalId===child).length,2);assert.ok(Math.abs(result.weights.find(w=>w.animalId===child&&w.unit==='kg').pounds-110.23113109)<0.0001);
const edit={id:child,version:a.version,operationId:crypto.randomUUID(),name:a.name,breed:a.breed,sex:a.sex,dob:'',birthYear:2024,reason:'Correct birth year'};assert.equal((await post('edit',edit)).status,200);result=await read();const changed=result.animals.find(a=>a.id===child);assert.equal(changed.id,a.id);assert.equal(changed.seq,a.seq);assert.equal(changed.birthYear,2024);assert.ok(result.history.some(h=>h.animalId===child&&JSON.parse(h.before).birthYear===2025));
a=result.animals.find(a=>a.id===sire);assert.equal((await post('pedigree',{id:sire,version:a.version,operationId:crypto.randomUUID(),sire:child,dam:null,reason:'Reject cycle'})).status,400);
assert.equal((await post('ancestor',{id:ancestor,species:'Sheep',name:'Unowned local QA',sex:'Male',birthYear:null,breed:'',info:{}})).status,200);
assert.equal((await post('weight',{...weight,id:crypto.randomUUID(),animalId:ancestor,date:'2026-06-01'})).status,400);
assert.equal((await post('weight',{...weight,id:crypto.randomUUID()},'all')).status,400);
console.log('PASS Phase1 API: creation, missing data, species/parent rules, unique EID, durable parent links, units, duplicate/retry, stable identity after correction, read-only years, cycle rejection and unowned ancestor guard');
