import assert from 'node:assert/strict';
const base='http://127.0.0.1:5173/api/flock';
const post=async(path,action,data,year='2026')=>{const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data,year})});return {status:r.status,data:await r.json()}};
const read=async()=>await(await fetch(base)).json();
const animals=[crypto.randomUUID(),crypto.randomUUID()];
for(const id of animals)assert.equal((await post('','animal',{id,species:'Sheep',name:'Local batch QA',sex:'Unknown',origin:'Purchased',firstYear:2026,birthYear:null})).status,200);
const data={id:crypto.randomUUID(),operationId:crypto.randomUUID(),species:'Sheep',name:'Local session QA',date:'2026-05-01',rows:animals.map((animalId,i)=>({id:crypto.randomUUID(),animalId,originalValue:100+i,unit:i?'kg':'lb'}))};
assert.equal((await post('/weight-sessions','create',data,'all')).status,400);
assert.equal((await post('/weight-sessions','create',{...data,rows:[data.rows[0],data.rows[0]]})).status,400);
assert.equal((await post('/weight-sessions','create',{...data,rows:[data.rows[0],{...data.rows[1],originalValue:-2}]})).status,400);
assert.equal((await read()).weights.filter(w=>w.batchId===data.id).length,0);
assert.equal((await post('/weight-sessions','create',data)).status,200);
assert.equal((await post('/weight-sessions','create',data)).status,200);
let result=await read(),rows=result.weights.filter(w=>w.batchId===data.id);assert.equal(rows.length,2);assert.equal(rows[1].unit,'kg');
const duplicate={...data,id:crypto.randomUUID(),operationId:crypto.randomUUID(),rows:data.rows.map(w=>({...w,id:crypto.randomUUID()}))};
assert.equal((await post('/weight-sessions','create',duplicate)).status,400);
const change={id:data.id,operationId:crypto.randomUUID(),species:'Sheep',reason:'Review session',expected:rows.map(w=>({id:w.id,version:w.version}))};
assert.equal((await post('/weight-sessions','void',change)).status,200);
assert.equal((await post('/weight-sessions','void',change)).status,200);
rows=(await read()).weights.filter(w=>w.batchId===data.id);assert.ok(rows.every(w=>w.voided));
assert.equal((await post('/weight-sessions','restore',{...change,operationId:crypto.randomUUID()})).status,409);
assert.equal((await post('/weight-sessions','restore',{...change,operationId:crypto.randomUUID(),expected:rows.map(w=>({id:w.id,version:w.version}))})).status,200);
rows=(await read()).weights.filter(w=>w.batchId===data.id);assert.ok(rows.every(w=>!w.voided));
let w=rows[0];assert.equal((await post('/weights','weight-edit',{...w,originalValue:105,operationId:crypto.randomUUID(),reason:'Corrected scale value'})).status,200);
rows=(await read()).weights.filter(w=>w.batchId===data.id);assert.equal(rows.length,2);assert.equal(rows.find(v=>v.id===w.id).originalValue,105);
assert.equal((await post('/weight-sessions','void',{...change,operationId:crypto.randomUUID(),expected:rows.map(w=>({id:w.id,version:w.version}))})).status,200);
assert.ok((await read()).weights.filter(w=>w.batchId===data.id).every(w=>w.voided));
console.log('PASS: batch atomic validation, save/retry, mixed units, duplicates, void/restore, stale versions, individual correction retains session');
