import {withWriteEpoch} from '@/db/recovery-context';
import {rawDb} from '@/db';
import {type Animal} from '@/lib/livestock';
import {normalizeOwners,resolvedOwnership,ownershipDate} from '@/lib/ownership';
async function handlePOST(req:Request){try{const {year:chosen,data:a}=await req.json() as any;const year=Number(chosen);if(chosen==='all'||!Number.isInteger(year)||year<1900||year>new Date().getFullYear())throw Error('Choose a specific year.');if(!a||! /^[0-9a-f-]{36}$/i.test(a.id)||! /^[0-9a-f-]{36}$/i.test(a.operationId))throw Error('Invalid record identifier.');const db=rawDb();const prior=await db.prepare('SELECT animalId,action FROM animal_history WHERE operationId=?').bind(a.operationId).first<any>();if(prior){if(prior.animalId!==a.id||prior.action!=='ownership')throw Error('Change identifier already used.');return Response.json({saved:true});}
 const animal=await db.prepare('SELECT * FROM animals WHERE id=?').bind(a.id).first<Animal>();if(!animal||animal.archivedAt||animal.pedigreeOnly||animal.firstYear>year)throw Error('Choose a flock animal present in this year.');if(animal.version!==a.version)return Response.json({error:'Animal changed elsewhere. Close and reopen before retrying.'},{status:409});ownershipDate(a.date,year);if(animal.dob&&a.date<animal.dob)throw Error('Ownership date cannot precede birth.');
 const reason=String(a.reason||'').trim();if(!reason||reason.length>500)throw Error('Enter a reason, up to 500 characters.');const owners=normalizeOwners(a.owners,a.unknown===true);const {results}=await db.prepare("SELECT operationId,after,reason FROM animal_history WHERE animalId=? AND action='ownership'").bind(a.id).all<any>();const events=resolvedOwnership(results.map(h=>({...JSON.parse(h.after).ownershipEvent,operationId:h.operationId,reason:h.reason})));const corrected=a.correctLatest?events.at(-1):undefined;if(a.correctLatest&&!corrected)throw Error('No ownership entry to correct.');const previous=corrected?events.slice(0,-1):events;if(previous.some(e=>e.date>=a.date))throw Error('Use a date after the previous ownership event.');const event={operationId:a.operationId,date:a.date,owners,unknown:a.unknown===true,reason,...(corrected?{supersedes:corrected.operationId}:{})};const next={...animal,version:animal.version+1,ownershipEvent:event};
 const result=await db.batch([db.prepare('INSERT INTO animal_history (operationId,animalId,action,reason,before,after,createdAt) SELECT ?,?,?,?,?,?,? FROM animals WHERE id=? AND version=?').bind(a.operationId,a.id,'ownership',reason,JSON.stringify(animal),JSON.stringify(next),new Date().toISOString(),a.id,a.version),db.prepare('UPDATE animals SET version=version+1 WHERE id=? AND version=?').bind(a.id,a.version)]);if(result[1].meta.changes!==1)return Response.json({error:'Animal changed elsewhere. Reopen and review.'},{status:409});return Response.json({saved:true});
 }catch(e){console.error('Ownership save failed',e);const m=e instanceof Error?e.message:'Unable to save.';return Response.json({error:/D1|SQLITE/.test(m)?'Unable to save ownership. Please retry.':m},{status:400})}}

export const POST=withWriteEpoch(handlePOST);
