"use client";
import {useState} from 'react';
import {type Animal,type Weight,label} from '@/lib/livestock';
import {ageDays,adjustedGrowth,adjustedGrowthSource} from '@/lib/adjusted-growth';
export default function AdjustedGrowth({animals,weights}:{animals:Animal[];weights:Weight[]}){
 const [id,setId]=useState(''),[wean,setWean]=useState(''),[post,setPost]=useState(''),[factor,setFactor]=useState(''),[reference,setReference]=useState('');
 const animal=animals.find(a=>a.id===id),rows=weights.filter(w=>w.animalId===id&&!w.voided).sort((a,b)=>a.date.localeCompare(b.date)),w=rows.find(w=>w.id===wean),p=rows.find(w=>w.id===post),birth=rows.find(w=>w.date===animal?.dob);let result:ReturnType<typeof adjustedGrowth>|null=null,error='';
 if(animal?.dob&&w&&factor&&reference.trim()){try{result=adjustedGrowth(animal.dob,birth||null,w,p||null,Number(factor))}catch(e){error=(e as Error).message}}
 return <details className="border rounded p-4 my-4"><summary>Separate adjusted-weight calculation · sheep</summary><p>Actual measurements remain unchanged. This calculator follows Virginia Tech’s published 60-day and 120-day formulas. Enter the adjustment factor and its basis explicitly; the program does not guess rearing type or dam age. This is not an EBV.</p><div className="form-grid"><label>Animal<select className="border rounded p-2 w-full" value={id} onChange={e=>{setId(e.target.value);setWean('');setPost('');setFactor('');setReference('')}}><option value="">Choose sheep</option>{animals.filter(a=>a.species==='Sheep'&&!a.pedigreeOnly&&!a.archivedAt).map(a=><option key={a.id} value={a.id}>{label(a)}</option>)}</select></label>{(['weaning','post'] as const).map(k=><label key={k}>{k==='weaning'?'45–90-day measurement':'90–150-day measurement (optional)'}<select className="border rounded p-2 w-full" value={k==='weaning'?wean:post} onChange={e=>k==='weaning'?setWean(e.target.value):setPost(e.target.value)}><option value="">Choose measurement</option>{rows.filter(w=>{const age=animal?.dob?ageDays(animal.dob,w.date):null;return age!==null&&(k==='weaning'?age>=45&&age<=90:age>=90&&age<=150)}).map(w=><option key={w.id} value={w.id}>{w.date} · {w.originalValue} {w.unit}</option>)}</select></label>)}<label>Weaning adjustment factor<input className="border rounded p-2 w-full" type="number" step="any" min="0" value={factor} onChange={e=>setFactor(e.target.value)}/></label><label>Factor basis / source<input className="border rounded p-2 w-full" value={reference} onChange={e=>setReference(e.target.value)} placeholder="Sex, dam age, birth/rearing class or adviser reference"/></label></div>{animal&&!animal.dob&&<p>Exact birth date is needed for age adjustment.</p>}{result&&<p>Adjusted 60-day estimate: {result.adjusted60.toFixed(2)} lb · Adjusted 120-day estimate: {result.adjusted120===null?'Not calculated':result.adjusted120.toFixed(2)+' lb'}{result.missingBirthWeight?' · No measured birth weight: the source’s birth-weight-omitted formula was used.':''}</p>}{error&&<p role="alert">{error}</p>}<p>Compare animals raised under comparable conditions. Calculated values are for review and are not saved as scale measurements. <a className="underline" target="_blank" rel="noreferrer" href={adjustedGrowthSource}>Formula and factor table, page 3</a>.</p></details>
}
