"use client";
import {useState} from 'react';
import EntrySheet,{type SheetColumn} from './entry-sheet';
import {blankImportRow,prepareImport,type ImportRow} from '@/lib/animal-import';
import type {Animal} from '@/lib/livestock';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const columns:SheetColumn[]=[{key:'name',label:'Name'},{key:'sex',label:'Sex',options:['','Unknown','Female','Male','Castrated male']},{key:'dob',label:'Birth date',type:'date'},{key:'birthYear',label:'Birth year',type:'number'},{key:'breed',label:'Breed'},{key:'origin',label:'Origin',options:['Purchased','Home-raised']},{key:'rightTag',label:'Right tag'},{key:'rightTagColor',label:'Right color'},{key:'leftTag',label:'Left tag'},{key:'leftTagColor',label:'Left color'},{key:'eid',label:'EID'},{key:'registry',label:'Registry'},{key:'registrationNumber',label:'Registration number'},{key:'farm',label:'Breeder / farm'},{key:'notes',label:'Notes'}];
export default function AnimalEntrySheet({animals,species,year,disabled,onSaved}:{animals:Animal[];species:string;year:string;disabled:boolean;onSaved:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<ImportRow[]>([]),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function add(){setRows(r=>[...r,blankImportRow(species,year,crypto.randomUUID())]);setReview(false)}
 const check=rows.length?prepareImport(rows,animals,Number(year)):{errors:[],animals:[]};
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/flock/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({year,rows})}),d:any=await r.json();if(!r.ok)throw Error(d.error);await onSaved();setOpen(false);setRows([])}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><Button disabled={disabled} onClick={()=>{if(!rows.length)add();setOpen(true)}}>Add animals</Button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="worksheet-dialog"><DialogHeader><DialogTitle>{review?'Review new animals':'Add animals worksheet'}</DialogTitle><DialogDescription>{species} · {year}. One animal per row. Tags and EIDs stay text, including leading zeros. Missing sex and birth details stay unknown. Drafts remain while this workspace is open.</DialogDescription></DialogHeader>{!review?<EntrySheet columns={columns} rows={rows} onChange={r=>setRows(r as ImportRow[])} onAdd={add} onRemove={i=>setRows(rows.filter((_,n)=>n!==i))} disabled={busy}/>:<><p>{rows.length} new animal records will be saved together.</p><div className="entry-sheet-scroll"><table className="entry-sheet"><thead><tr><th>#</th><th>Name / tag</th><th>Sex</th><th>Birth</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.name||r.rightTag||r.leftTag||'Unnamed'}</td><td>{r.sex||'Unknown'}</td><td>{r.dob||r.birthYear||'Unknown'}</td></tr>)}</tbody></table></div></>}{check.errors.map((e,i)=><p role="alert" className="error" key={i}>{e}</p>)}{error&&<p role="alert" className="error">{error}</p>}<div className="worksheet-actions">{review?<><Button variant="outline" disabled={busy} onClick={()=>setReview(false)}>Back to worksheet</Button><Button disabled={busy||!!check.errors.length} onClick={save}>{busy?'Saving…':`Save ${rows.length} animals`}</Button></>:<Button disabled={!rows.length||!!check.errors.length} onClick={()=>setReview(true)}>Review animals</Button>}</div></DialogContent></Dialog></>
}
