"use client";
import {useState,useEffect,type ReactNode} from 'react';
import {type Animal,label,displayId} from '@/lib/livestock';
import {GroupFilter,useGroups} from './group-context';
import {groupMembers} from '@/lib/management-groups';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Column={title:string;render:(animal:Animal)=>ReactNode};
type Props={animals:Animal[];selected:string[];onChange:(ids:string[])=>void;multiple?:boolean;disabled?:boolean;max?:number;disabledReason?:(a:Animal)=>string;columns?:Column[];date?:string};
export function AnimalSheet({animals,selected,onChange,multiple=true,disabled=false,max=200,disabledReason,columns=[],date}:Props){
 const [query,setQuery]=useState(''),[sex,setSex]=useState(''),[breed,setBreed]=useState(''),[only,setOnly]=useState(false),[sort,setSort]=useState('id'),[desc,setDesc]=useState(false);
 const {events:groupEvents,error:groupError,loading:groupLoading}=useGroups();
 const [group,setGroup]=useState(''),[groupDate,setGroupDate]=useState(date||new Date().toISOString().slice(0,10));
 useEffect(()=>{if(date)setGroupDate(date)},[date]);
 const members=group?groupMembers(groupEvents,group,groupDate):null;
 const value=(a:Animal,k:string)=>k==='id'?displayId(a):k==='name'?label(a):String(a[k as keyof Animal]??'');
 const shown=animals.filter(a=>(!members||!groupError&&!groupLoading&&members.has(a.id))&&(!sex||a.sex===sex)&&(!breed||a.breed===breed)&&(!only||selected.includes(a.id))&&[displayId(a),a.name,a.rightTag,a.leftTag,a.eid,a.breed,a.sex].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(desc?-1:1)*value(a,sort).localeCompare(value(b,sort),undefined,{numeric:true}));
 const blocked=(a:Animal)=>disabledReason?.(a)||'';
 const toggle=(a:Animal)=>{if(disabled)return;if(selected.includes(a.id))onChange(selected.filter(id=>id!==a.id));else if(!blocked(a)&&(!multiple||selected.length<max))onChange(multiple?[...selected,a.id]:[a.id])};
 const addVisible=()=>onChange([...new Set([...selected,...shown.filter(a=>!blocked(a)).map(a=>a.id)])].slice(0,max));
 const cols=[['id','Animal ID'],['name','Name'],['rightTag','Right tag'],['leftTag','Left tag'],['eid','EID'],['sex','Sex'],['breed','Breed'],['status','Status']];
 return <div className="animal-sheet"><div className="animal-sheet-tools"><label>Find animals<input autoComplete="off" placeholder="ID, name, tag, EID or breed" value={query} onChange={e=>setQuery(e.target.value)}/></label><GroupFilter value={group} onChange={setGroup} date={groupDate} onDateChange={date?undefined:setGroupDate} species={new Set(animals.map(a=>a.species)).size===1?animals[0]?.species:undefined} eligibleIds={animals.map(a=>a.id)}/><label>Sex<select aria-label="Sex" value={sex} onChange={e=>setSex(e.target.value)}><option value="">All sexes</option>{[...new Set(animals.map(a=>a.sex))].filter(Boolean).sort().map(v=><option key={v}>{v}</option>)}</select></label><label>Breed<select aria-label="Breed" value={breed} onChange={e=>setBreed(e.target.value)}><option value="">All breeds</option>{[...new Set(animals.map(a=>a.breed))].filter(Boolean).sort().map(v=><option key={v}>{v}</option>)}</select></label><label className="animal-sheet-check"><input type="checkbox" checked={only} onChange={e=>setOnly(e.target.checked)}/>Selected only</label></div>
 <div className="animal-sheet-actions"><span>{shown.length} matching · {selected.length} selected{multiple?` / ${max}`:''}</span>{multiple&&<><Button type="button" variant="outline" disabled={disabled||selected.length>=max} onClick={addVisible}>Select filtered</Button><Button type="button" variant="outline" disabled={disabled} onClick={()=>onChange(selected.filter(id=>!shown.some(a=>a.id===id)))}>Clear filtered</Button></>}</div>
 <div className="animal-sheet-scroll" tabIndex={0} aria-label="Animal selection table"><table><thead><tr><th>Select</th>{cols.map(([k,title])=><th key={k} aria-sort={sort===k?(desc?'descending':'ascending'):'none'}><button type="button" onClick={()=>{if(sort===k)setDesc(!desc);else{setSort(k);setDesc(false)}}}>{title}{sort===k?(desc?' ↓':' ↑'):''}</button></th>)}{columns.map(c=><th key={c.title}>{c.title}</th>)}{disabledReason&&<th>Review</th>}</tr></thead><tbody>{shown.map(a=><tr key={a.id} data-selected={selected.includes(a.id)}><td><input type={multiple?'checkbox':'radio'} aria-label={`Select ${label(a)} · ${displayId(a)}`} checked={selected.includes(a.id)} disabled={disabled||!selected.includes(a.id)&&(!!blocked(a)||multiple&&selected.length>=max)} onChange={()=>toggle(a)}/></td>{cols.map(([k])=><td key={k}>{value(a,k)||'—'}</td>)}{columns.map(c=><td key={c.title}>{c.render(a)}</td>)}{disabledReason&&<td>{blocked(a)||'Eligible'}</td>}</tr>)}</tbody></table>{!shown.length&&<p className="empty">No matching animals. Change or clear the filters.</p>}</div><p className="hint">Type to find animals, filter columns, or click a column heading to sort. Filtering keeps your selections. Choose a group, then Select filtered to add its eligible members. All matching rows are available without paging.</p></div>
}
export default function AnimalPicker({animals,value,onValueChange,onChange,clearValue='',placeholder='Choose animal',disabled=false,required=false,date,'aria-label':aria}:{animals:Animal[];value:string;onValueChange?:(value:string)=>void;onChange?:(event:{target:{value:string}})=>void;clearValue?:string;placeholder?:string;disabled?:boolean;required?:boolean;className?:string;date?:string;'aria-label'?:string}){
 const [open,setOpen]=useState(false);const current=animals.find(a=>a.id===value);const choose=(id:string)=>{onValueChange?.(id);onChange?.({target:{value:id}});setOpen(false)};
 return <><Button type="button" className="animal-picker-trigger" variant="outline" disabled={disabled} aria-label={aria||placeholder} aria-haspopup="dialog" onClick={()=>setOpen(true)}>{current?`${label(current)} · ${displayId(current)}`:value&&value!==clearValue?'Selected record — choose to review':placeholder}<span aria-hidden="true"> ▦</span></Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="animal-picker-dialog"><DialogHeader><DialogTitle>{aria||'Select animal'}</DialogTitle><DialogDescription>Find and select one animal from the worksheet.</DialogDescription></DialogHeader><AnimalSheet date={date} animals={animals} selected={current?[current.id]:[]} multiple={false} onChange={ids=>{if(ids[0])choose(ids[0])}}/>{!required&&<Button type="button" variant="outline" onClick={()=>choose(clearValue)}>Clear / {placeholder}</Button>}<Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button></DialogContent></Dialog></>
}
