"use client";
import {AnimalCustomFields} from './custom-fields';
import AnimalOwnership from './animal-ownership';
import AnimalMedia from './animal-media';
import AnimalStatus from './animal-status';
import AnimalTags from './animal-tags';
import {useEffect,useState,type ReactNode} from 'react';
import PedigreeWorkspace from './pedigree-workspace';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Tags,FileText,GitBranch,Camera,Users,HeartPulse,History,NotebookPen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {type Animal,label,displayId} from '@/lib/livestock';
export default function AnimalActions({animal,animals,year,history,onSaved,onOpenAnimal,records,weights,onDirty}:{animal:Animal;animals:Animal[];year:string;history:any[];onSaved:()=>Promise<void>;onOpenAnimal:(a:Animal)=>void;records:ReactNode;weights:ReactNode;onDirty:(dirty:boolean)=>void}){
 const [detailsDirty,setDetailsDirty]=useState(false);
 const [section,setSection]=useState('details'),[dirty,setDirty]=useState(false),[rootId,setRootId]=useState(animal.id);
 const editable=year!=='all'&&Number(year)<=new Date().getFullYear()&&!animal.archivedAt;
 const tabs=[['details','Details & registration',FileText],['tags','Tags & EID',Tags],['pedigree','Pedigree',GitBranch],['photos','Photos',Camera],['ownership','Ownership',Users],['status','Status & exits',HeartPulse],['records','Events & weights',NotebookPen],['history','History',History]] as const;
 function changeSection(next:string){if(dirty&&!window.confirm('Discard unsaved changes in this section?'))return;setDirty(false);setDetailsDirty(false);onDirty(false);setSection(next);open('edit')}
 async function savedSection(){setDirty(false);onDirty(false);await onSaved()}
 const [origin,setOrigin]=useState(animal.origin);
 const [sex,setSex]=useState(animal.sex||'Unknown'),[dob,setDob]=useState(animal.dob||''),[birthYear,setBirthYear]=useState(animal.birthYear?String(animal.birthYear):'');
 const [action,setAction]=useState('edit'),[reason,setReason]=useState('Animal details updated'),[name,setName]=useState(animal.name),[breed,setBreed]=useState(animal.breed),[sire,setSire]=useState(animal.sire||''),[dam,setDam]=useState(animal.dam||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[operationId,setOperationId]=useState(()=>crypto.randomUUID());

 const readInfo=()=>{try{return JSON.parse(animal.pedigreeInfo||'{}')}catch{return {}}};
 const fields={registry:'Registry',registrationNumber:'Registration number',membershipId:'Membership ID',flockNameId:'Flock name / ID',farm:'Breeder / farm',notes:'Notes'};
 const [info,setInfo]=useState<Record<string,string>>(readInfo);
 const parentLabel=(id:string|null)=>{const p=animals.find(a=>a.id===id);return p?label(p):id||'Unknown'};
 function open(a:string){setInfo(readInfo());setOrigin(animal.origin);setAction(a);setReason(a==='edit'?'Animal details updated':'');setError('');setSex(animal.sex||'Unknown');setDob(animal.dob||'');setBirthYear(animal.birthYear?String(animal.birthYear):'');setName(animal.name);setBreed(animal.breed);setSire(animal.sire||'');setDam(animal.dam||'');setOperationId(crypto.randomUUID())}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/flock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,year,data:{id:animal.id,version:animal.version,operationId,reason,name,breed,sire,dam,...(action==='edit'?{info,origin,sex,dob,birthYear:birthYear?Number(birthYear):null}:{})}})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setAction('edit');setDetailsDirty(false);setDirty(false);onDirty(false);setOperationId(crypto.randomUUID());await onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to save. Try again.')}finally{setBusy(false)}}

 useEffect(()=>{setInfo(readInfo());setOrigin(animal.origin);setName(animal.name);setBreed(animal.breed);setSex(animal.sex||'Unknown');setDob(animal.dob||'');setBirthYear(animal.birthYear?String(animal.birthYear):'')},[animal.version]);
 return <div className="animal-editor"><div className="animal-editor-context"><span>{year==='all'?'All years · read-only':`Working year ${year}`} · First recorded {animal.firstYear}</span><span>{animal.archivedAt?'Deleted (restorable)':animal.status}</span></div><Tabs value={section} onValueChange={changeSection} orientation="vertical" className="animal-editor-layout"><TabsList className="animal-editor-nav" aria-label="Animal editing sections">{tabs.map(([id,title,Icon])=><TabsTrigger key={id} value={id}><Icon size={17}/><span>{title}</span></TabsTrigger>)}</TabsList><div className="animal-editor-panel" onChangeCapture={()=>{setDirty(true);onDirty(true)}}>
 <TabsContent value="details"><h3>Animal details & registration</h3><p className="hint">Update the fields below. Save this section before moving to another one.</p><form onSubmit={save} onChange={()=>setDetailsDirty(true)}><fieldset disabled={!editable||busy}>
 <h4>Identity & birth</h4><div className="form-grid"><label>Name<Input value={name} onChange={e=>setName(e.target.value)} maxLength={200}/></label><label>Breed / description<Input value={breed} onChange={e=>setBreed(e.target.value)} maxLength={200}/></label><label>Sex<Select value={sex} onValueChange={v=>{setSex(v);setDetailsDirty(true);setDirty(true);onDirty(true)}}><SelectTrigger aria-label="Edit sex"><SelectValue/></SelectTrigger><SelectContent>{['Unknown','Female','Male','Castrated male'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label>{!animal.pedigreeOnly&&<label>Origin<Select value={origin} onValueChange={v=>{setOrigin(v);setDetailsDirty(true);setDirty(true);onDirty(true)}}><SelectTrigger aria-label="Edit origin"><SelectValue/></SelectTrigger><SelectContent>{['Purchased','Home-raised'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label>}<label>Birth date (optional)<Input type="date" value={dob} onChange={e=>setDob(e.target.value)}/></label><label>Birth year only<Input type="number" value={dob?dob.slice(0,4):birthYear} disabled={!!dob} onChange={e=>setBirthYear(e.target.value)}/></label></div><h4>Registration & breeder</h4><div className="form-grid">{Object.entries(fields).filter(([k])=>k!=='notes').map(([k,title])=><label key={k}>{title}<Input value={info[k]||''} maxLength={200} onChange={e=>setInfo(v=>({...v,[k]:e.target.value}))}/></label>)}</div><label className="editor-notes">Animal notes<textarea value={info.notes||''} maxLength={2000} rows={3} onChange={e=>setInfo(v=>({...v,notes:e.target.value}))}/></label>
 <div className="animal-editor-save"><Button type="submit" disabled={!editable||busy}>{busy?'Saving…':'Save details & registration'}</Button>{error&&<p role="alert" className="error">{error}</p>}</div></fieldset></form>{detailsDirty&&<p className="hint">Save the details above before changing documents or custom fields.</p>}<fieldset disabled={detailsDirty}><AnimalMedia key={'registration'+animal.version} section="registration" animal={animal} year={year} onSaved={savedSection}/><AnimalCustomFields key={'custom'+animal.version} animal={animal} year={year} history={history} onSaved={savedSection}/></fieldset></TabsContent>
 <TabsContent value="tags"><h3>Tags & EID</h3><p className="hint">Correct a typo, retire a lost or replaced tag, add another tag, or choose tags to swap. Previous tags stay in history.</p><AnimalTags key={animal.version} animal={animal} year={year} history={history} onSaved={savedSection}/></TabsContent>
 <TabsContent value="pedigree"><PedigreeWorkspace animals={animals} species={animal.species} year={year} rootId={rootId} onRootChange={setRootId} onReload={savedSection} onOpenAnimal={onOpenAnimal}/></TabsContent>
 <TabsContent value="photos"><AnimalMedia key={animal.version} section="photo" animal={animal} year={year} onSaved={savedSection}/></TabsContent>
 <TabsContent value="ownership"><AnimalOwnership key={animal.version} animal={animal} year={year} onSaved={savedSection}/></TabsContent>
 <TabsContent value="status"><AnimalStatus key={animal.version} animal={animal} year={year} onSaved={savedSection}/><div className="animal-editor-danger"><h3>{animal.archivedAt?'Restore this record':'Delete this record'}</h3><p>Deletion is for unwanted records. Record a sale, death, transfer or cull above to preserve its disposition.</p><Button variant={animal.archivedAt?'outline':'destructive'} disabled={year==='all'} onClick={()=>open(animal.archivedAt?'restore':'archive')}>{animal.archivedAt?'Restore animal':'Delete animal'}</Button></div></TabsContent>
 <TabsContent value="records">{records}<h3>Lifetime weights</h3>{weights}</TabsContent>
 <TabsContent value="history"> <details open className="mt-4"><summary>Change history ({history.length})</summary>{history.length?history.map(h=>{const before=JSON.parse(h.before),after=JSON.parse(h.after);return <div key={h.operationId} className="history-entry"><b>{h.action==='display-id'?'Animal ID updated':h.action==='ownership'?'Ownership updated':h.action.startsWith('file-')?'Photo/document '+h.action.replace('file-',''):h.action.startsWith('weight-')?'Weight '+h.action.replace('weight-',''):h.action==='status'?'Status updated':h.action==='tag'?'Tag record updated':h.action==='archive'?'Deleted':h.action==='restore'?'Restored':h.action==='pedigree'?'Pedigree updated':'Edited'}</b><small>{new Date(h.createdAt).toLocaleString()}</small><p>{h.reason}</p>{h.action==='display-id'&&<p>{displayId(before)} → {displayId(after)}</p>}{h.action==='ownership'&&<p>{after.ownershipEvent.date} · {after.ownershipEvent.unknown?'Unknown ownership':after.ownershipEvent.owners.map((o:any)=>o.name+' '+o.basisPoints/100+'%').join('; ')}</p>}{h.action.startsWith('weight-')&&<p>{before.originalValue!==undefined?before.originalValue+' '+before.unit+' on '+before.date+' → ':''}{after.originalValue} {after.unit} on {after.date} · {after.voided?'Voided':'Valid'}<br/>Session: {after.session}</p>}{(h.action==='edit'||h.action==='ancestor-edit')&&<p>Name: {before.name||'Not entered'} → {after.name||'Not entered'}<br/>{(['rightTag','leftTag','eid','sex','dob','birthYear','origin'] as const).filter(k=>before[k]!==after[k]).map(k=><span key={k}>{({origin:'Origin',rightTag:'Right tag',leftTag:'Left tag',eid:'EID',sex:'Sex',dob:'Birth date',birthYear:'Birth year'})[k]}: {before[k]||'Not entered'} → {after[k]||'Not entered'}<br/></span>)}Breed: {before.breed||'Not entered'} → {after.breed||'Not entered'}</p>}{Object.entries(fields).map(([k,title])=>{const b=JSON.parse(before.pedigreeInfo||'{}')[k]||'',a=JSON.parse(after.pedigreeInfo||'{}')[k]||'';return b!==a?<p key={k}>{title}: {b||'Not entered'} → {a||'Not entered'}</p>:null})}{h.action==='pedigree'&&<p>Sire: {parentLabel(before.sire)} → {parentLabel(after.sire)}<br/>Dam: {parentLabel(before.dam)} → {parentLabel(after.dam)}</p>}</div>}):<p className="hint">No changes recorded yet.</p>}</details>
</TabsContent></div></Tabs>
 <AlertDialog open={action==='archive'||action==='restore'} onOpenChange={o=>{if(!busy&&!o)setAction('edit')}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{action==='archive'?'Delete animal?':'Restore animal?'}</AlertDialogTitle><AlertDialogDescription>The same identity and linked history are preserved. Deleted records can be restored.</AlertDialogDescription></AlertDialogHeader><form onSubmit={save}><label>Reason<Input required value={reason} onChange={e=>setReason(e.target.value)} maxLength={500}/></label>{error&&<p role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><Button type="submit" disabled={busy||!reason.trim()} variant={action==='archive'?'destructive':'default'}>{busy?'Saving…':action==='archive'?'Delete animal':'Restore animal'}</Button></AlertDialogFooter></form></AlertDialogContent></AlertDialog></div>;
}
