"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {tagSlots} from '@/lib/tag-records';
import {type Animal} from '@/lib/livestock';
export default function AnimalTags({animal,year,history,onSaved}:{animal:Animal;year:string;history:any[];onSaved:()=>Promise<void>}){
 const slots=tagSlots(animal),meta=JSON.parse(animal.pedigreeInfo||'{}');
 const [mode,setMode]=useState('correct'),[field,setField]=useState(''),[otherField,setOther]=useState(''),[ear,setEar]=useState('Left'),[value,setValue]=useState(''),[color,setColor]=useState(''),[eidPosition,setPosition]=useState(meta.eidTagPosition||''),[replacementEid,setReplacement]=useState(''),[date,setDate]=useState(year===String(new Date().getFullYear())?new Date().toLocaleDateString('en-CA'):year+'-01-01'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState(false),[operationId,setOperation]=useState(()=>crypto.randomUUID());
 const events=history.flatMap(h=>{try{const e=JSON.parse(h.after).tagChange;return e?[{...e,id:h.operationId,reason:h.reason}]:[]}catch{return []}});
 const name=(id:string)=>{const t=slots.find(t=>t.id===id);return t?`${t.ear} · ${t.number||'empty'}${t.color?' · '+t.color:''}`:id==='eid'?'EID':id};
 function start(m:string){setMode(m);setField('');setOther('');setValue('');setColor('');setReplacement('');setReason('');setError('');setOperation(crypto.randomUUID());setEditing(true)}
 function choose(id:string){setField(id);const t=slots.find(t=>t.id===id);setValue(mode==='correct'||mode==='color'||mode==='link'?id==='eid'?animal.eid||'':t?.number||'':'');setColor(mode==='correct'||mode==='color'?t?.color||'':'')}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/flock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'tag',year,data:{id:animal.id,version:animal.version,operationId,mode,field,otherField,ear,value,color,eidPosition,replacementEid,date,reason}})});const d:any=await r.json();if(!r.ok)throw Error(d.error);await onSaved();setEditing(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const editable=!animal.archivedAt&&year!=='all';
 return <details className="mt-4"><summary>Manage tags</summary>{slots.filter(t=>t.number).map(t=><p key={t.id}><b>{t.ear} ear · {t.number}</b> · {t.color||'Color not recorded'}{meta.eidTagPosition===t.id?' · EID '+animal.eid:''}</p>)}{animal.eid&&!meta.eidTagPosition&&<p>EID: {animal.eid} · not linked to a physical tag</p>}
 {editable&&<div className="flex flex-wrap gap-2 my-3"><Button variant="outline" onClick={()=>start('add')}>Add tag</Button><Button variant="outline" onClick={()=>start('correct')}>Correct tag</Button><Button variant="outline" onClick={()=>start('retire')}>Retire / replace</Button><Button variant="outline" onClick={()=>start('swap')}>Swap selected tags</Button><Button variant="outline" onClick={()=>{start(animal.eid?'link':'assign');setField('eid');setValue(animal.eid||'')}}>Manage EID</Button></div>}
 {editing&&editable&&<form onSubmit={save}><div className="form-grid">{mode==='add'?<label>Ear<select value={ear} onChange={e=>setEar(e.target.value)}><option>Left</option><option>Right</option></select></label>:<label>{mode==='swap'?'First tag':'Tag'}<select className="w-full border rounded p-2" required value={field} onChange={e=>choose(e.target.value)}><option value="">Choose a tag</option>{slots.map(t=><option key={t.id} value={t.id}>{name(t.id)}</option>)}{mode!=='swap'&&<option value="eid">EID</option>}</select></label>}
 {mode==='swap'?<label>Second tag<select className="w-full border rounded p-2" required value={otherField} onChange={e=>setOther(e.target.value)}><option value="">Choose another tag</option>{slots.filter(t=>t.id!==field&&t.number).map(t=><option key={t.id} value={t.id}>{name(t.id)}</option>)}</select></label>:<><label>{mode==='retire'?'Replacement number (optional)':'Tag number / EID'}<Input value={value} onChange={e=>setValue(e.target.value)} required={mode!=='retire'} disabled={mode==='link'} maxLength={200}/></label>{field!=='eid'&&<label>Color (optional)<Input value={color} onChange={e=>setColor(e.target.value)} maxLength={60}/></label>}{field==='eid'&&<><label>EID action<select value={mode} onChange={e=>setMode(e.target.value)}><option value="link">Link existing EID</option><option value="correct">Correct EID</option><option value="assign">Assign EID</option><option value="retire">Retire unlinked EID</option></select></label><label>Linked physical tag<select value={eidPosition} onChange={e=>setPosition(e.target.value)}><option value="">Not linked</option>{slots.filter(t=>t.number).map(t=><option key={t.id} value={t.id}>{name(t.id)}</option>)}</select></label></>}{mode==='retire'&&field!=='eid'&&<label>Replacement EID (optional)<Input value={replacementEid} onChange={e=>setReplacement(e.target.value)} maxLength={200}/></label>}</>}
 <label>Date<Input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Reason<Input value={reason} onChange={e=>setReason(e.target.value)} required maxLength={500}/></label></div>{mode==='swap'&&<p className="hint">Only the two selected tags exchange positions. Their numbers, colors, and linked EID stay together. This does not retire tags.</p>}{error&&<p role="alert" className="error">{error}</p>}<Button disabled={busy} type="submit">{busy?'Saving…':'Save tag record'}</Button><Button variant="outline" type="button" disabled={busy} onClick={()=>setEditing(false)}>Cancel</Button></form>}
 <h3 className="mt-4">Retired tags</h3>{events.filter(e=>e.mode==='retire').map(e=><p key={e.id}>{e.previous} · {e.previousColor||'Color not recorded'}{e.retiredEid?' · EID '+e.retiredEid:''} · {e.date} · {e.reason}</p>)}
 <h3 className="mt-4">Tag history</h3>{events.map(e=><p key={e.id}>{e.date} · {e.mode} · {e.previous||'Empty'} → {e.value||'Empty'}{e.otherPrevious?' · exchanged with '+e.otherPrevious:''}{e.color?' · '+e.color:''} · {e.reason}</p>)}</details>;
}
