"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {type Animal,label} from '@/lib/livestock';
export default function AnimalActions({animal,animals,year,history,onSaved}:{animal:Animal;animals:Animal[];year:string;history:any[];onSaved:()=>Promise<void>}){
 const [action,setAction]=useState(''),[reason,setReason]=useState(''),[name,setName]=useState(animal.name),[breed,setBreed]=useState(animal.breed),[sire,setSire]=useState(animal.sire||''),[dam,setDam]=useState(animal.dam||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[operationId,setOperationId]=useState('');
 const parentLabel=(id:string|null)=>{const p=animals.find(a=>a.id===id);return p?label(p):id||'Unknown'};
 function open(a:string){setAction(a);setReason('');setError('');setName(animal.name);setBreed(animal.breed);setSire(animal.sire||'');setDam(animal.dam||'');setOperationId(crypto.randomUUID())}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/flock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,year,data:{id:animal.id,version:animal.version,operationId,reason,name,breed,sire,dam}})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setAction('');await onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to save. Try again.')}finally{setBusy(false)}}
 return <div className="animal-actions"><div className="flex flex-wrap gap-2">{animal.archivedAt?<Button disabled={year==='all'} onClick={()=>open('restore')}>Restore animal</Button>:<><Button variant="outline" disabled={year==='all'} onClick={()=>open('edit')}>Edit name / breed</Button><Button variant="outline" disabled={year==='all'} onClick={()=>open('pedigree')}>Set pedigree</Button><Button variant="destructive" disabled={year==='all'} onClick={()=>open('archive')}>Delete animal</Button></>}</div>
 <details className="mt-4"><summary>Change history ({history.length})</summary>{history.length?history.map(h=>{const before=JSON.parse(h.before),after=JSON.parse(h.after);return <div key={h.operationId} className="history-entry"><b>{h.action==='archive'?'Deleted':h.action==='restore'?'Restored':h.action==='pedigree'?'Pedigree updated':'Edited'}</b><small>{new Date(h.createdAt).toLocaleString()}</small><p>{h.reason}</p>{h.action==='edit'&&<p>Name: {before.name||'Not entered'} → {after.name||'Not entered'}<br/>Breed: {before.breed||'Not entered'} → {after.breed||'Not entered'}</p>}{h.action==='pedigree'&&<p>Sire: {parentLabel(before.sire)} → {parentLabel(after.sire)}<br/>Dam: {parentLabel(before.dam)} → {parentLabel(after.dam)}</p>}</div>}):<p className="hint">No changes recorded yet.</p>}</details>
 <AlertDialog open={!!action} onOpenChange={o=>{if(!busy&&!o)setAction('')}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{action==='archive'?'Delete '+label(animal)+'?':action==='restore'?'Restore '+label(animal)+'?':action==='pedigree'?'Set pedigree for '+label(animal):'Edit animal details'}</AlertDialogTitle><AlertDialogDescription>{action==='archive'?'This animal will move to Deleted animals and leave active lists. Its weights, identity and pedigree links are preserved. You can restore it later.':action==='restore'?'Restore this same animal and its linked records. Enter a reason for the history.':action==='pedigree'?'Select recorded parents, or leave a parent unknown. COI recalculates from these links. Add missing ancestors as animal records first.':'Update the name or breed description. Previous values and your reason remain in the history.'}</AlertDialogDescription></AlertDialogHeader><form onSubmit={save}>
 {action==='pedigree'&&<div className="form-grid">{(['sire','dam'] as const).map(role=><label key={role}>{role==='sire'?'Sire':'Dam'}<Select value={(role==='sire'?sire:dam)||'unknown'} onValueChange={v=>(role==='sire'?setSire:setDam)(v==='unknown'?'':v)}><SelectTrigger aria-label={role}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unknown">Unknown / not recorded</SelectItem>{animals.filter(p=>p.id!==animal.id&&p.species===animal.species&&p.sex===(role==='sire'?'Male':'Female')).map(p=><SelectItem key={p.id} value={p.id}>{label(p)}{p.archivedAt?' (deleted record)':''}</SelectItem>)}</SelectContent></Select></label>)}</div>}
 {action==='edit'&&<div className="form-grid"><label>Name<Input value={name} onChange={e=>setName(e.target.value)} maxLength={200}/></label><label>Breed / description<Input value={breed} onChange={e=>setBreed(e.target.value)} maxLength={200}/></label></div>}
 <label className="block my-4">Reason *<Input value={reason} onChange={e=>setReason(e.target.value)} required maxLength={500} placeholder={action==='archive'?'For example: entered by mistake':'Reason for this change'}/></label>{error&&<p role="alert" className="error">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><Button type="submit" variant={action==='archive'?'destructive':'default'} disabled={busy||!reason.trim()}>{busy?'Saving…':action==='archive'?'Delete animal':action==='restore'?'Restore animal':'Save changes'}</Button></AlertDialogFooter></form></AlertDialogContent></AlertDialog></div>
}
