"use client";
import {useState} from 'react';
import {type Animal,label,displayId,visibleInYear} from '@/lib/livestock';
import {statusAt} from '@/lib/animal-status';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function AnimalYearRoll({animals,species,year,mode,onClose,onSaved,onYear,onAddYear}:{animals:Animal[];species:string;year:string;mode:'prior'|'forward';onClose:()=>void;onSaved:()=>Promise<void>;onYear:(year:string)=>void;onAddYear:()=>Promise<void>}){
 const source=Number(year),[target,setTarget]=useState(String(source-1)),[query,setQuery]=useState(''),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState<string[]>([]),[operations]=useState<Record<string,string>>({});
 const forward=mode==='forward';
 const candidates=animals.filter(a=>a.species===species&&!a.archivedAt&&!a.pedigreeOnly&&visibleInYear(a,year));
 const carried=candidates.filter(a=>statusAt(a,`${source+1}-01-01`)==='Active');
 function issue(a:Animal){const n=Number(target),birth=a.dob?Number(a.dob.slice(0,4)):a.birthYear;return !Number.isInteger(n)||n<1900||n>=source||n>=new Date().getFullYear()?'Choose a prior year':birth&&n<birth?'Before birth year':n>=a.firstYear?'Already recorded in this year or earlier':''}
 const shown=candidates.filter(a=>[label(a),displayId(a),a.rightTag,a.leftTag,a.eid].some(v=>v?.toLowerCase().includes(query.toLowerCase())));
 async function save(){setBusy(true);setError('');const complete=[...saved];try{for(const id of selected.filter(id=>!complete.includes(id))){const a=candidates.find(a=>a.id===id);if(!a)throw Error('Animal no longer available. Close and reopen to refresh.');if(issue(a))throw Error(`${label(a)}: ${issue(a)}`);operations[id]??=crypto.randomUUID();const r=await fetch('/api/flock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'roll-year',year,data:{id,version:a.version,operationId:operations[id],targetYear:Number(target),reason:`Recorded flock presence extended to ${target}`}})});const d:any=await r.json();if(!r.ok)throw Error(`${label(a)}: ${d.error||'Save failed'}`);complete.push(id);setSaved([...complete])}await onSaved();onYear(target);onClose()}catch(e){setError(`${complete.length} saved. ${e instanceof Error?e.message:'Save failed'}. Retry resumes remaining animals.`)}finally{setBusy(false)}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="sm:max-w-3xl max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{forward?`Roll livestock forward to ${source+1}`:'Roll livestock to year'}</DialogTitle><DialogDescription>{forward?'Active livestock carry forward as the same lifetime profiles. Previous-year records stay in their original years.':'Select animals whose recorded flock presence should begin earlier. This extends their history; it does not duplicate profiles or move dated records.'}</DialogDescription></DialogHeader>
 {forward?<><p>{carried.length} active {species.toLowerCase()} carry into {source+1}. {candidates.length-carried.length} other animals are not carried as active.</p><div className="max-h-80 overflow-auto"><table><thead><tr><th>Animal</th><th>ID</th></tr></thead><tbody>{carried.map(a=><tr key={a.id}><td>{label(a)}</td><td>{displayId(a)}</td></tr>)}</tbody></table></div><p className="hint">Future years support planning. Actual weights, treatments, and other completed events still require a valid date that is not in the future.</p>{error&&<p role="alert">{error}</p>}<Button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await onAddYear();onYear(String(source+1));onClose()}catch(e){setError(e instanceof Error?e.message:'Could not add year')}finally{setBusy(false)}}}>Add and open {source+1} with {carried.length} active animals</Button></>:<><label>Prior year<input aria-label="Roll target year" className="border rounded p-2 ml-3" type="number" min={1900} max={Math.min(source-1,new Date().getFullYear()-1)} value={target} disabled={busy||saved.length>0} onChange={e=>{setTarget(e.target.value);setSelected([])}}/></label><input aria-label="Find animals to roll" className="border rounded p-2" placeholder="Find animals by name, tag or ID" value={query} disabled={busy} onChange={e=>setQuery(e.target.value)}/><Button variant="outline" disabled={busy||saved.length>0} onClick={()=>setSelected(shown.filter(a=>!issue(a)).map(a=>a.id))}>Select eligible results</Button><div className="max-h-80 overflow-auto"><table><thead><tr><th>Select</th><th>Animal</th><th>First year</th><th>Review</th></tr></thead><tbody>{shown.map(a=><tr key={a.id}><td><input type="checkbox" aria-label={`Select ${label(a)}`} disabled={busy||saved.length>0||!!issue(a)} checked={selected.includes(a.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,a.id]:v.filter(id=>id!==a.id))}/></td><td>{label(a)} · {displayId(a)}</td><td>{a.firstYear}</td><td>{saved.includes(a.id)?'Saved':issue(a)||'Eligible'}</td></tr>)}</tbody></table></div><p>{selected.length} selected. Each animal retains an audited history entry. Successful saves remain saved if a later row fails.</p>{error&&<p role="alert">{error}</p>}<Button disabled={busy||!selected.length} onClick={save}>{busy?'Saving…':error?'Retry remaining animals':`Roll ${selected.length} animals to ${target}`}</Button></>}
 </DialogContent></Dialog>;
}
