"use client";
import {useState} from 'react';
import {type Animal} from '@/lib/livestock';
import {animalFiles,type AnimalFile} from '@/lib/animal-files';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function AnimalMedia({animal,year,onSaved}:{animal:Animal;year:string;onSaved:()=>Promise<void>}){
 const info=JSON.parse(animal.pedigreeInfo||'{}'),{files,primaryPhotoId}=animalFiles(animal.pedigreeInfo),primary=files.find(f=>f.id===primaryPhotoId&&!f.removedAt);const editable=year!=='all'&&!animal.archivedAt;
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[removed,setRemoved]=useState(false),[page,setPage]=useState(0),[edit,setEdit]=useState<AnimalFile|null>(null),[operationId,setOperationId]=useState(()=>crypto.randomUUID());
 const url=(f:AnimalFile)=>'/api/flock/files?animal='+animal.id+'&file='+f.id;
 async function send(form:FormData,action:string,fileId=''){setBusy(true);setError('');form.set('animalId',animal.id);form.set('year',year);form.set('version',String(animal.version));form.set('operationId',operationId);form.set('action',action);form.set('fileId',fileId);try{const response=await fetch('/api/flock/files',{method:'POST',body:form});const data=await response.json() as any;if(!response.ok)throw Error(data.error);setOperationId(crypto.randomUUID());await onSaved();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();void send(new FormData(e.currentTarget),'upload');}
 function action(mode:string,f:AnimalFile){void send(new FormData(),mode,f.id);}
 const photos=files.filter(f=>f.category==='photo'&&(removed||!f.removedAt)).sort((a,b)=>b.uploadedAt.localeCompare(a.uploadedAt));
 const paper=files.filter(f=>f.category==='registration'&&(removed||!f.removedAt));
 function card(f:AnimalFile){return <div key={f.id} className="border rounded p-2"><b>{f.id===primaryPhotoId?'Profile photo':f.category==='photo'?'Past photo':'Registration document'}</b>{f.removedAt?<p>Removed · can be restored</p>:<>{f.type.startsWith('image/')&&<a href={url(f)} target="_blank" rel="noopener noreferrer"><img src={url(f)} alt={f.caption||f.name} className="w-28 h-28 object-cover rounded my-2" loading="lazy"/></a>}<a className="animal-link" href={url(f)} target="_blank" rel="noopener noreferrer">Open {f.name}</a> · <a href={url(f)+'&download=1'}>Download</a></>}{f.category==='registration'&&(f.registry||f.registrationNumber)&&<p>Attached registration: {f.registry} {f.registrationNumber}</p>}<p className="hint">{f.takenOn?'Photo/document date: '+f.takenOn:'Date unknown'} · Uploaded {f.uploadedAt.slice(0,10)}</p>{f.caption&&<p>{f.caption}</p>}{editable&&<div className="flex flex-wrap gap-2">{f.removedAt?<Button type="button" disabled={busy} variant="outline" onClick={()=>action('restore',f)}>Restore</Button>:<>{f.category==='photo'&&f.id!==primaryPhotoId&&<Button type="button" disabled={busy} variant="outline" onClick={()=>action('primary',f)}>Use as profile photo</Button>}<Button type="button" variant="outline" disabled={busy} onClick={()=>{setEdit(f);setError('')}}>Edit date/caption</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>action('remove',f)}>Remove (restorable)</Button></>}</div>}</div>}
 return <div className="my-4">{(info.farm||info.notes)&&<section className="my-3">{info.farm&&<p>Breeder / farm: {info.farm}</p>}{info.notes&&<><h3>Animal notes</h3><p className="whitespace-pre-wrap">{info.notes}</p></>}</section>}<section><h3>Animal photos</h3>{primary?<a href={url(primary)} target="_blank" rel="noopener noreferrer"><img src={url(primary)} alt={primary.caption||'Profile photo'} className="w-40 h-40 object-cover rounded my-2"/></a>:<p className="hint">No profile photo yet.</p>}<p className="hint">Adding a new profile photo keeps all past photos. Dates can remain unknown.</p>{editable&&<details><summary>Add animal photo</summary><form onSubmit={upload}><input type="hidden" name="category" value="photo"/><label>Photo<Input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/></label><label>Date taken (optional)<Input name="takenOn" type="date"/></label><label>Caption (optional)<Input name="caption" maxLength={500}/></label><label><input type="checkbox" name="makePrimary" value="true" defaultChecked/> Use as profile photo</label><p className="hint">JPG, PNG or WebP, up to 10 MB. Save HEIC photos as JPEG first.</p><Button disabled={busy} type="submit">{busy?'Saving…':'Upload photo'}</Button></form></details>}<details className="my-3"><summary>Photo history ({photos.length})</summary><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{photos.slice(page*4,page*4+4).map(card)}</div>{photos.length>4&&<div className="flex gap-2"><Button type="button" variant="outline" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page+1} of {Math.ceil(photos.length/4)}</span><Button type="button" variant="outline" disabled={(page+1)*4>=photos.length} onClick={()=>setPage(page+1)}>Next</Button></div>}</details></section>
 <section className="my-4"><h3>Registration</h3><p>{info.registry||'Registry not entered'} · {info.registrationNumber||'Registration number not entered'}</p>{info.membershipId&&<p>Membership: {info.membershipId}</p>}{info.flockNameId&&<p>Flock ID: {info.flockNameId}</p>}<p className="hint">Use Edit animal details to update registration text. Papers are attached here, separately from animal photos.</p><div className="grid gap-2">{paper.map(card)}</div>{!paper.length&&<p>No registration papers attached.</p>}{editable&&<details><summary>Attach registration papers</summary><form onSubmit={upload}><input type="hidden" name="category" value="registration"/><label>Paper / scan<Input name="file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" required/></label><label>Document date (optional)<Input name="takenOn" type="date"/></label><label>Description (optional)<Input name="caption" maxLength={500}/></label><p className="hint">PDF, JPG, PNG or WebP, up to 10 MB.</p><Button disabled={busy} type="submit">Attach paper</Button></form></details>}</section>
 <label><input type="checkbox" checked={removed} onChange={e=>{setRemoved(e.target.checked);setPage(0)}}/> Show removed photos and papers</label>{edit&&<form className="border rounded p-3 my-2" onSubmit={e=>{e.preventDefault();void send(new FormData(e.currentTarget),'details',edit.id)}}><h4>Edit {edit.name}</h4><label>Date (optional)<Input type="date" name="takenOn" defaultValue={edit.takenOn}/></label><label>Caption / description<Input name="caption" defaultValue={edit.caption} maxLength={500}/></label><Button disabled={busy} type="submit">Save details</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setEdit(null)}>Cancel</Button></form>}{error&&<p className="error" role="alert">{error}</p>}</div>;
}
