"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {swapImportTags,importFields,fieldLabels,blankImportRow,matchImportField,normalizeImportRow,mapImportRows,parseCsv,prepareImport,type ImportRow,type ImportField} from '@/lib/animal-import';
import type {Animal} from '@/lib/livestock';
import ImportPdf from './import-pdf';
import PedigreeImportPreview from './pedigree-import-preview';
import {hasPedigreeColumns} from '@/lib/pedigree-import';
function Choice({value,options,onChange,label}:{value:string;options:string[];onChange:(v:string)=>void;label:string}){return <Select value={value||'choose'} onValueChange={v=>onChange(v==='choose'?'':v)}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="choose">Choose…</SelectItem>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>}
export default function AnimalImport({animals,species,year,disabled,onSaved}:{animals:Animal[];species:string;year:string;disabled:boolean;onSaved:(count:number,message?:string)=>Promise<void>}){
 const [open,setOpen]=useState(false),[file,setFile]=useState<File|null>(null),[sheets,setSheets]=useState<string[]>([]),[sheet,setSheet]=useState(''),[grid,setGrid]=useState<string[][]>([]),[mapping,setMapping]=useState<string[]>([]),[rows,setRows]=useState<ImportRow[]>([]),[step,setStep]=useState('file'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reviewed,setReviewed]=useState(false);
 const pdf=file?.name.toLowerCase().endsWith('.pdf');
 function changeRows(next:ImportRow[]){setRows(next);setReviewed(false);setError('')}
 function loadGrid(g:string[][]){if(g.length<2)throw Error('The sheet needs a header row and at least one animal.');if(g.length>201)throw Error('Use at most 200 animal rows.');if(g[0].length>60)throw Error('Use at most 60 columns.');if(g.slice(1).some(r=>r.length>g[0].length))throw Error('A row has more cells than the header. Check the file.');setGrid(g);setMapping(g[0].map(matchImportField));setStep('map')}
 async function excel(f:File,s:string){const {default:read}=await import('read-excel-file/browser');const data=await read(f,{sheet:s});loadGrid(data.map(r=>r.map(c=>c instanceof Date?c.toISOString().slice(0,10):String(c??''))).filter(r=>r.some(c=>c.trim())))}
 async function load(f:File){setBusy(true);setError('');setRows([]);setGrid([]);setSheets([]);setReviewed(false);setStep('file');setFile(null);try{if(f.size>10*1024*1024)throw Error('Use a file smaller than 10 MB.');const ext=f.name.split('.').pop()?.toLowerCase();if(!['csv','xlsx','pdf'].includes(ext||''))throw Error('Choose CSV, Excel .xlsx or PDF. Save older .xls files as .xlsx first.');setFile(f);if(ext==='pdf'){setStep('review');return}if(ext==='csv')loadGrid(parseCsv(await f.text()));else{const {readSheetNames}=await import('read-excel-file/browser');const names=await readSheetNames(f);if(!names.length)throw Error('No worksheets found.');setSheets(names);setSheet(names[0]);await excel(f,names[0])}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function template(){const text=importFields.join(',')+'\r\n';const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='animal-import-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function preview(){setError('');try{changeRows(mapImportRows(grid,mapping,species,year));setStep('review')}catch(e){setError((e as Error).message)}}
 function addRow(text='',page=0){if(rows.length>=200){setError('Import at most 200 animals at a time.');return}const r=blankImportRow(species,year,String(rows.length+1));r.notes=file?`Imported from ${file.name}${page?' · page '+page:''}`:'';if(text){for(const line of text.split(/\r?\n/)){const m=line.match(/^\s*([^:]{1,40}):\s*(.+?)\s*$/);if(!m)continue;const k=matchImportField(m[1]);if(k&&!['recordKey','sireKey','damKey','pedigreeOnly'].includes(k)&&!r[k])r[k]=m[2]}}let n=rows.length+1;while(rows.some(x=>x.recordKey===String(n)))n++;r.recordKey=String(n);changeRows([...rows,normalizeImportRow(r)])}
 const check=rows.length?prepareImport(rows,animals,Number(year)):{errors:[],animals:[]};
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/flock/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({year,rows})});const data:any=await r.json();if(!r.ok)throw Error(data.error||'Unable to import.');await onSaved(data.count);setOpen(false);setRows([]);setFile(null);setStep('file')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><Button variant="outline" disabled={disabled} onClick={()=>setOpen(true)}>Import animals</Button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="form-dialog import-dialog"><DialogHeader><DialogTitle>Import animals</DialogTitle><DialogDescription>Preview new animals and unowned ancestors before saving. Existing records are not overwritten.</DialogDescription></DialogHeader>
 <div className="flex flex-wrap gap-3 items-center"><label className="import-upload">Choose CSV, Excel (.xlsx) or PDF<Input type="file" accept=".csv,.xlsx,.pdf" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void load(f);e.target.value=''}}/></label><Button type="button" variant="outline" onClick={template}>Download CSV template</Button></div><p className="hint">Up to 200 animals per import. Dates use YYYY-MM-DD. Keep tags and EIDs as text to preserve leading zeros. Missing species and first recorded year default to {species}, {year}. Sex and birth details are optional and stay unknown when blank.</p>
 {busy&&<p role="status">Working…</p>}{error&&step!=='map'&&<p className="error whitespace-pre-line" role="alert">{error}</p>}
 {step==='pedigree'&&<PedigreeImportPreview grid={grid} animals={animals} year={year} species={species} onBack={()=>setStep('map')} onSaved={async message=>{await onSaved(0,message);setOpen(false);setRows([]);setFile(null);setStep('file')}}/>}
 {step==='map'&&<>{hasPedigreeColumns(grid[0]||[])&&<div className="banner"><b>Sire and dam registration columns detected</b><p>For animals already in your flock, update parent links and registration details here. For new animals, import the animal records first, then reopen this file to update their pedigrees.</p><Button disabled={busy} onClick={()=>{setError('');setStep('pedigree')}}>Preview pedigree updates</Button></div>}<h3>Match your columns</h3>{grid[0]?.some(h=>/^tag\s*[123]$/i.test(h.trim()))&&<p className="banner">Tag 1 maps to Right tag and Tag 2 to Left tag. Use Swap right/left tags in the preview if needed. Tag 3 is not assumed to be an EID; choose its mapping if needed.</p>}{grid[0]?.some(h=>/^tag\s*color$/i.test(h.trim()))&&<p className="hint">Tag Color is read as right/left: White/Yellow means right white and left yellow; /Blue leaves right unknown and sets left blue. A single color applies to the right tag. Color is required wherever a tag number is entered.</p>}{sheets.length>1&&<Choice value={sheet} label="Worksheet" options={sheets} onChange={async s=>{if(!s||!file)return;setSheet(s);setBusy(true);setError('');try{await excel(file,s)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/>}<div className="import-mapping">{grid[0]?.map((header,i)=><label key={i}>{header||`Column ${i+1}`}<Select value={mapping[i]||'ignore'} onValueChange={v=>setMapping(mapping.map((k,n)=>n===i?v==='ignore'?'':v:k))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ignore">Do not import</SelectItem>{importFields.map(k=><SelectItem key={k} value={k}>{fieldLabels[k]}</SelectItem>)}</SelectContent></Select><small>Example: {grid[1]?.[i]||'empty'}</small></label>)}</div><p className="hint">Columns mapped to the same field are combined when one is blank or their values agree.</p>{error&&<p className="error whitespace-pre-line" role="alert">{error}</p>}<Button disabled={busy} onClick={preview}>Preview {grid.length-1} animals</Button></>}
 {step==='review'&&<><div className={pdf?'import-review with-pdf':'import-review'}>{pdf&&file&&<ImportPdf file={file} onText={addRow}/>}<section><h3>Review animals ({rows.length})</h3><Button variant="outline" disabled={busy||!rows.length} onClick={()=>changeRows(rows.map(swapImportTags))}>Swap right/left tags for all rows</Button>{pdf&&<p className="hint">Read each animal from the PDF and add its details below. Scanned pages are shown for manual entry. No parent links are guessed.</p>}<p className="hint">For related animals in this file, give each a unique Import key, then enter that key in its offspring’s Sire or Dam import key. Mark ancestors you do not own as Yes.</p>{rows.map((row,i)=><details className="import-row" key={row.id} open={rows.length===1||undefined}><summary>{i+1}. {row.name||row.rightTag||'Animal details needed'} · {row.pedigreeOnly==='Yes'?'Unowned ancestor':'Flock animal'}</summary><div className="form-grid">{importFields.filter(k=>k!=='tagColors').map(k=><label key={k}>{fieldLabels[k]}{['species','sex','origin','pedigreeOnly'].includes(k)?<Choice label={`Row ${i+1} ${fieldLabels[k]}`} value={row[k]} options={k==='species'?['Sheep','Goats']:k==='sex'?['Unknown','Female','Male','Castrated male']:k==='origin'?['Purchased','Home-raised']:['No','Yes']} onChange={v=>changeRows(rows.map((r,n)=>n===i?{...r,[k]:v}:r))}/>:<Input aria-label={`Row ${i+1} ${fieldLabels[k]}`} value={row[k]} required={(k==='rightTagColor'&&!!row.rightTag.trim())||(k==='leftTagColor'&&!!row.leftTag.trim())} type={k==='dob'?'date':k==='birthYear'||k==='firstYear'?'number':'text'} maxLength={k==='notes'?2000:200} onChange={e=>changeRows(rows.map((r,n)=>n===i?{...r,[k]:e.target.value}:r))}/>}</label>)}</div><Button variant="outline" disabled={busy} onClick={()=>changeRows(rows.map((r,n)=>n===i?swapImportTags(r):r))}>Swap right/left tags</Button><Button variant="outline" onClick={()=>changeRows(rows.filter((_,n)=>n!==i))}>Remove this row</Button></details>)}<Button variant="outline" disabled={rows.length>=200||busy} onClick={()=>addRow()}>Add another animal</Button></section></div>
 {check.errors.length>0&&<div className="error" role="alert"><b>Resolve these items before importing:</b><ul>{check.errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>}{rows.length>0&&!check.errors.length&&<p className="success">{rows.filter(r=>r.pedigreeOnly!=='Yes').length} flock animals and {rows.filter(r=>r.pedigreeOnly==='Yes').length} unowned ancestors ready.</p>}<label className="import-confirm"><input type="checkbox" checked={reviewed} disabled={busy} onChange={e=>setReviewed(e.target.checked)}/> I checked the identities, dates and parent links against my source.</label><div className="form-actions">{!pdf&&<Button variant="outline" disabled={busy} onClick={()=>{setStep('map');setReviewed(false)}}>Back to columns</Button>}<Button disabled={busy||!reviewed||!rows.length||!!check.errors.length} onClick={save}>{busy?'Importing…':`Import ${rows.length} animals`}</Button></div></>}
 </DialogContent></Dialog></>;
}


