"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {tagLabels} from '@/lib/tag-change';
import {type Animal} from '@/lib/livestock';
export default function AnimalTags({animal,year,history,onSaved}:{animal:Animal;year:string;history:any[];onSaved:()=>Promise<void>}){
 const [field,setField]=useState<keyof typeof tagLabels>('rightTag'),[mode,setMode]=useState('retire'),[value,setValue]=useState(''),[date,setDate]=useState(year===String(new Date().getFullYear())?new Date().toLocaleDateString('en-CA'):year+'-01-01'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[operationId,setOperationId]=useState(()=>crypto.randomUUID());
 const storedPosition=JSON.parse(animal.pedigreeInfo||'{}').eidTagPosition||'';
 const [eidPosition,setEidPosition]=useState(storedPosition),[replacementEid,setReplacementEid]=useState('');
 const events=history.flatMap(h=>{try{const e=JSON.parse(h.after).tagChange;return e?[{...e,reason:h.reason,id:h.operationId}]:[]}catch{return []}});
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/flock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'tag',year,data:{id:animal.id,version:animal.version,operationId,field,mode,value:mode==='link'?animal.eid||'':value,eidPosition,replacementEid,date,reason}})});const d:any=await r.json();if(!r.ok)throw Error(d.error);await onSaved();setValue('');setReplacementEid('');setReason('');setOperationId(crypto.randomUUID());setNotice('Tag record saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details className="mt-4"><summary>Manage tags · correct, retire, or replace</summary><p className="hint">Correct fixes a recording mistake. Retire records a lost, removed, or replaced tag; a replacement is optional. Link an existing EID by choosing EID, then Link existing EID to an ear tag. Retiring a linked ear tag retires its EID too.</p>
 <div className="my-3">{Object.entries(tagLabels).map(([k,title])=><p key={k}>{title}{k==='eid'?(storedPosition?` (on ${tagLabels[storedPosition as keyof typeof tagLabels].toLowerCase()})`:' (ear position not linked)'):''}: <b>{animal[k as keyof typeof tagLabels]||'No active tag'}</b></p>)}</div>
 {!animal.archivedAt&&year!=='all'&&<form onSubmit={save}><div className="form-grid"><label>Tag position<select className="w-full border rounded p-2" value={field} onChange={e=>{setField(e.target.value as keyof typeof tagLabels);setMode('retire');setValue('');setReplacementEid('');setEidPosition(storedPosition)}}>{Object.entries(tagLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Action<select className="w-full border rounded p-2" value={mode} onChange={e=>{setMode(e.target.value);setValue('')}}><option value="retire">Retire / replace tag</option><option value="correct">Correct a recording mistake</option><option value="assign">Assign tag to empty position</option>{field==='eid'&&<option value="link">Link existing EID to an ear tag</option>}</select></label><label>{mode==='retire'?'Replacement tag (optional)':mode==='correct'?'Corrected tag':'New tag'}<Input value={mode==='link'?animal.eid||'':value} disabled={mode==='link'} onChange={e=>setValue(e.target.value)} maxLength={200} required={mode!=='retire'}/></label><label>{mode==='retire'?'Retirement date':mode==='correct'?'Correction date':'Assignment date'}<Input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label>{field==='eid'&&mode!=='retire'&&<label>EID belongs to<select className="w-full border rounded p-2" value={eidPosition} onChange={e=>setEidPosition(e.target.value)}><option value="">Ear position unknown / not linked</option><option value="rightTag">Right ear tag</option><option value="leftTag">Left ear tag</option></select></label>}{field!=='eid'&&mode!=='correct'&&<label>{mode==='retire'?'Replacement':'New'} tag EID (optional)<Input value={replacementEid} maxLength={200} onChange={e=>setReplacementEid(e.target.value)}/></label>}<label>Reason<Input value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} required placeholder="Lost, damaged, replaced, or entry mistake"/></label></div>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}<Button type="submit" disabled={busy}>{busy?'Saving…':'Save tag record'}</Button></form>}
 <h3 className="mt-4">Retired tags</h3>{events.filter(e=>e.mode==='retire').length?events.filter(e=>e.mode==='retire').map(e=><p key={e.id}><b>{e.previous}</b>{e.retiredEid?` · EID ${e.retiredEid}`:''} · {tagLabels[e.field as keyof typeof tagLabels]} · retired {e.date} · {e.reason}{e.value?` · replaced by ${e.value}`:' · no replacement at retirement'}</p>):<p className="hint">No tag retirements recorded.</p>}
 <h3 className="mt-4">Tag history</h3>{events.map(e=><p key={e.id}>{e.date} · {tagLabels[e.field as keyof typeof tagLabels]} · {e.mode==='correct'?'Correction':e.mode==='retire'?'Retirement':e.mode==='link'?'EID link':'Assignment'}: {e.previous||'Empty'} → {e.value||'Empty'} · {e.reason}{e.previousEid!==e.eid?` · EID ${e.previousEid||'none'} → ${e.eid||'none'}`:''}{e.position?` · linked to ${tagLabels[e.position as keyof typeof tagLabels]}`:''}</p>)}
 </details>;
}

