"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {statuses} from '@/lib/animal-status';
import {type Animal} from '@/lib/livestock';
export default function AnimalStatus({animal,year,onSaved}:{animal:Animal;year:string;onSaved:()=>Promise<void>}){
 const [status,setStatus]=useState(animal.statusEvents?.some(e=>!e.date)?animal.status:'Sold'),[date,setDate]=useState(year===String(new Date().getFullYear())?new Date().toLocaleDateString('en-CA'):year+'-01-01'),[cull,setCull]=useState(false),[cullReason,setCullReason]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[operationId]=useState(()=>crypto.randomUUID());
 const [correctLatest,setCorrectLatest]=useState(false);
 const isCull=status==='Culled'||(['Sold','Transferred'].includes(status)&&cull);
 async function save(e:React.FormEvent){e.preventDefault();const submittedDate=String(new FormData(e.currentTarget as HTMLFormElement).get('effectiveDate')||'');setBusy(true);setError('');try{const r=await fetch('/api/flock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status',year,data:{id:animal.id,version:animal.version,operationId,status,date:submittedDate,correctLatest,exitReason:isCull?'Cull':'',cullReason:isCull?cullReason:'',reason}})});const d:any=await r.json();if(!r.ok)throw Error(d.error);await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details className="mt-4"><summary>Status and exit history · {animal.status}</summary><p className="hint">Record when the animal left or returned. Earlier years keep their recorded presence. Delete is for removing a record, not recording an exit.</p>{!animal.pedigreeOnly&&!animal.archivedAt&&year!=='all'&&<form onSubmit={save}><div className="form-grid">{!!animal.statusEvents?.length&&<label><input type="checkbox" checked={correctLatest} onChange={e=>{setCorrectLatest(e.target.checked);if(e.target.checked){const last=animal.statusEvents!.at(-1)!;setStatus(last.status);setDate(last.date);setCull(last.exitReason==='Cull');setCullReason(last.cullReason||'')}}}/> Correct latest status entry (keeps original in change history)</label>}<label>Status<select className="w-full border rounded p-2" value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Effective date (leave blank if unknown)<Input name="effectiveDate" type="date" value={date} onChange={e=>setDate(e.target.value)} required={status==='Active'}/></label>{['Sold','Transferred'].includes(status)&&<label><input type="checkbox" checked={cull} onChange={e=>setCull(e.target.checked)}/> This exit is for culling</label>}{isCull&&<label>Cull reason<Input value={cullReason} onChange={e=>setCullReason(e.target.value)} required maxLength={200} placeholder="Enter the reason for culling"/></label>}<label>Reason / notes<Input value={reason} onChange={e=>setReason(e.target.value)} required maxLength={500}/></label></div>{error&&<p role="alert" className="error">{error}</p>}<Button disabled={busy} type="submit">{busy?'Saving…':'Save status'}</Button></form>}{(animal.statusEvents||[]).map(e=><p key={e.operationId}><b>{e.date||'Exit date unknown'} · {e.status}</b>{e.exitReason?' · '+e.exitReason:''}{e.cullReason?' · '+e.cullReason:''} · {e.reason}</p>)}</details>;
}
