"use client";
import {AnimalSheet} from './animal-picker';
import {useEffect,useState} from 'react';
import {type Animal,label,displayId,visibleInYear} from '@/lib/livestock';
import {includedInYear} from '@/lib/animal-status';
import {yearRollCandidates,rollDecision} from '@/lib/year-roll';
import type {FarmEvent} from '@/lib/farm-events';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function AnimalYearRoll({animals,species,year,mode,onClose,onSaved,onYear,onAddYear}:{animals:Animal[];species:string;year:string;mode:'prior'|'forward';onClose:()=>void;onSaved:()=>Promise<void>;onYear:(year:string)=>void;onAddYear:(selected:string[],candidates:Animal[],settingsVersion:number,operationId:string)=>Promise<void>}){
 const source=Number(year),[target,setTarget]=useState(String(source-1)),[query,setQuery]=useState(''),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState<string[]>([]),[operations]=useState<Record<string,string>>({});
 const forward=mode==='forward';
 const candidates=animals.filter(a=>a.species===species&&!a.archivedAt&&!a.pedigreeOnly&&visibleInYear(a,year));
 const carried=yearRollCandidates(animals,species,source);
 const [events,setEvents]=useState<FarmEvent[]>([]),[ready,setReady]=useState(!forward),[settingsVersion,setSettingsVersion]=useState(0),[operationId]=useState(()=>crypto.randomUUID());
 useEffect(()=>{if(!forward)return;let cancelled=false;Promise.all([fetch('/api/flock/events').then(async r=>{if(!r.ok)throw Error('Could not load retention decisions. Reopen rollover.');return r.json()}),fetch('/api/flock/settings').then(async r=>{if(!r.ok)throw Error('Could not load saved rollover. Reopen rollover.');return r.json()})]).then(([eventData,settings]:any[])=>{if(cancelled)return;setEvents(eventData.events);setSettingsVersion(settings.version);setSelected(carried.filter(a=>{const explicit=JSON.parse(a.pedigreeInfo||'{}').yearSelections?.[source+1];return typeof explicit==='boolean'?explicit:rollDecision(a,eventData.events,source)==='Retain'||includedInYear(a,source+1)}).map(a=>a.id));setReady(true)}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[]);
 function issue(a:Animal){const n=Number(target),birth=a.dob?Number(a.dob.slice(0,4)):a.birthYear;return !Number.isInteger(n)||n<1900||n>=source||n>=new Date().getFullYear()?'Choose a prior year':birth&&n<birth?'Before birth year':n>=a.firstYear?'Already recorded in this year or earlier':''}
 const shown=candidates.filter(a=>[label(a),displayId(a),a.rightTag,a.leftTag,a.eid].some(v=>v?.toLowerCase().includes(query.toLowerCase())));
 async function save(){setBusy(true);setError('');const complete=[...saved];try{for(const id of selected.filter(id=>!complete.includes(id))){const a=candidates.find(a=>a.id===id);if(!a)throw Error('Animal no longer available. Close and reopen to refresh.');if(issue(a))throw Error(`${label(a)}: ${issue(a)}`);operations[id]??=crypto.randomUUID();const r=await fetch('/api/flock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'roll-year',year,data:{id,version:a.version,operationId:operations[id],targetYear:Number(target),reason:`Recorded flock presence extended to ${target}`}})});const d:any=await r.json();if(!r.ok)throw Error(`${label(a)}: ${d.error||'Save failed'}`);complete.push(id);setSaved([...complete])}await onSaved();onYear(target);onClose()}catch(e){setError(`${complete.length} saved. ${e instanceof Error?e.message:'Save failed'}. Retry resumes remaining animals.`)}finally{setBusy(false)}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="rollover-dialog sm:max-w-3xl max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{forward?`Roll livestock forward to ${source+1}`:'Roll livestock to year'}</DialogTitle><DialogDescription>{forward?'Active livestock carry forward as the same lifetime profiles. Previous-year records stay in their original years.':'Select animals whose recorded flock presence should begin earlier. This extends their history; it does not duplicate profiles or move dated records.'}</DialogDescription></DialogHeader>
 {forward?<><p>{selected.length} of {carried.length} eligible animals selected for {source+1}. Retained ewe and ram lambs are labeled below and selected by default.</p><AnimalSheet date={source+'-12-31'} animals={carried} selected={selected} onChange={setSelected} max={carried.length} disabled={!ready||busy} columns={[{title:'Retention decision',render:a=>rollDecision(a,events,source)}]}/><p className="hint">Unchecked animals remain in their earlier history and are not carried into this year or later until selected again. This does not mark them sold or dead. Saved records in earlier years are unchanged. Future years allow planning; actual events still require a valid date.</p>{error&&<p role="alert">{error}</p>}<Button disabled={busy||!ready} onClick={async()=>{setBusy(true);setError('');try{await onAddYear(selected,carried,settingsVersion,operationId);await onSaved();onYear(String(source+1));onClose()}catch(e){setError(e instanceof Error?e.message:'Could not save rollover')}finally{setBusy(false)}}}>{busy?'Saving...':`Save rollover to ${source+1} (${selected.length} selected)`}</Button></>:<><label>Prior year<input aria-label="Roll target year" className="border rounded p-2 ml-3" type="number" min={1900} max={Math.min(source-1,new Date().getFullYear()-1)} value={target} disabled={busy||saved.length>0} onChange={e=>{setTarget(e.target.value);setSelected([])}}/></label><AnimalSheet date={source+'-12-31'} animals={candidates} selected={selected} onChange={setSelected} max={candidates.length} disabled={busy||saved.length>0} disabledReason={issue} columns={[{title:'First year',render:a=>a.firstYear},{title:'Saved',render:a=>saved.includes(a.id)?'Saved':''}]}/><p>{selected.length} selected. Each animal retains an audited history entry. Successful saves remain saved if a later row fails.</p>{error&&<p role="alert">{error}</p>}<Button disabled={busy||!selected.length} onClick={save}>{busy?'Saving…':error?'Retry remaining animals':`Roll ${selected.length} animals to ${target}`}</Button></>}
 </DialogContent></Dialog>;
}
