"use client";
import {useState} from 'react';
import {ownershipAt} from '@/lib/ownership';
import {type Animal} from '@/lib/livestock';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function AnimalOwnership({animal,year,onSaved}:{animal:Animal;year:string;onSaved:()=>Promise<void>}){
 const events=animal.ownershipEvents||[],current=ownershipAt(events,year==='all'?new Date().toISOString().slice(0,10):year+'-12-31');
 const [open,setOpen]=useState(false),[correct,setCorrect]=useState(false),[unknown,setUnknown]=useState(false),[rows,setRows]=useState([{name:'',percent:'100'}]),[date,setDate]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[op,setOp]=useState('');
 function start(correction:boolean){const e=correction?events.at(-1):current;setCorrect(correction);setUnknown(e?.unknown||false);setRows(e?.owners.length?e.owners.map(o=>({name:o.name,percent:String(o.basisPoints/100)})):[{name:'',percent:'100'}]);setDate(correction?e?.date||'':'');setOp(crypto.randomUUID());setError('');setOpen(true);}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/flock/ownership',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({year,data:{id:animal.id,version:animal.version,operationId:op,correctLatest:correct,unknown,owners:rows,date:String(f.get('date')),reason:String(f.get('reason'))}})});const data=await r.json() as any;if(!r.ok)throw Error(data.error);await onSaved();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="my-4"><h3>Ownership</h3><p>{!current||current.unknown?'Ownership not recorded / unknown':current.owners.map(o=>o.name+' · '+(o.basisPoints/100)+'%').join('; ')}</p>{current&&<p className="hint">Effective {current.date} · shown through {year==='all'?'today':year}</p>}<p className="hint">Ownership is separate from Active/Sold status. No owner is inferred from imported records. Shares use 0.01% precision and must total 100%.</p>{!animal.pedigreeOnly&&!animal.archivedAt&&year!=='all'&&<div className="flex gap-2"><Button variant="outline" onClick={()=>start(false)}>Record ownership change</Button>{events.length>0&&<Button variant="outline" onClick={()=>start(true)}>Correct latest entry</Button>}</div>}{open&&<form className="border rounded p-3 my-3" onSubmit={save}><label>Effective date<Input name="date" type="date" key={op} defaultValue={date} required/></label><label><input type="checkbox" checked={unknown} onChange={e=>setUnknown(e.target.checked)}/> Ownership unknown</label>{!unknown&&<>{rows.map((r,i)=><div className="flex gap-2 my-2" key={i}><label>Owner<Input value={r.name} required maxLength={200} onChange={e=>setRows(rows.map((v,n)=>n===i?{...v,name:e.target.value}:v))}/></label><label>Share %<Input type="number" step="0.01" min="0.01" max="100" value={r.percent} required onChange={e=>setRows(rows.map((v,n)=>n===i?{...v,percent:e.target.value}:v))}/></label>{rows.length>1&&<Button type="button" variant="outline" onClick={()=>setRows(rows.filter((_,n)=>n!==i))}>Remove owner</Button>}</div>)}<Button type="button" variant="outline" disabled={rows.length>=10} onClick={()=>setRows([...rows,{name:'',percent:''}])}>Add co-owner</Button><p>Total: {rows.reduce((sum,r)=>sum+(Number(r.percent)||0),0).toFixed(2)}%</p></>}<label>Reason<Input name="reason" required maxLength={500}/></label>{error&&<p className="error" role="alert">{error}</p>}<Button disabled={busy} type="submit">{busy?'Saving…':'Save ownership'}</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button></form>}<details className="my-3"><summary>Ownership history ({events.length})</summary>{events.map(e=><p key={e.operationId}>{e.date} · {e.unknown?'Unknown':e.owners.map(o=>o.name+' '+o.basisPoints/100+'%').join('; ')} · {e.reason}</p>)}<p className="hint">Superseded entries remain in the full change history.</p></details></section>;
}
