"use client";
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
export default function BackupVault(){
 const [items,setItems]=useState<any[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const operation=useRef<{kind:string;id:string}|null>(null);
 async function load(next?:string){try{const r=await fetch('/api/flock/backup/vault'+(next?'?cursor='+encodeURIComponent(next):'')),d=await r.json() as any;if(!r.ok)throw Error(d.error);setItems(old=>next?[...old,...d.backups]:d.backups);setCursor(d.cursor);setError('')}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[]);
 async function save(kind:string){setBusy(true);setError('');if(operation.current?.kind!==kind)operation.current={kind,id:crypto.randomUUID()};try{const r=await fetch('/api/flock/backup/vault',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,operationId:operation.current!.id})}),d=await r.json() as any;if(!r.ok)throw Error(d.error);operation.current=null;await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="border rounded p-4 my-4"><h3>Saved manual backups</h3><p>Keep a dated copy in application storage. Manual copies are retained; download another copy for storage outside the program. This does not enable an unattended backup schedule.</p><div className="flex flex-wrap gap-2 my-3"><Button disabled={busy} onClick={()=>save('records')}>Save records copy</Button><Button disabled={busy} onClick={()=>save('full')}>Save full copy with photos</Button></div>{busy&&<p role="status">Creating backup…</p>}{error&&<p role="alert">{error}</p>}{items.map(item=><p key={item.key}><a className="underline" href={'/api/flock/backup/vault?key='+encodeURIComponent(item.key)}>{new Date(item.date).toLocaleString()} · {item.full?'Full archive':'Records'} · {(item.size/1024/1024).toFixed(2)} MB</a></p>)}{cursor&&<Button variant="outline" onClick={()=>load(cursor)}>More saved copies</Button>}</section>
}
