"use client";
import {AnimalSheet} from './animal-picker';
import {useState} from 'react';
import {type Animal,label,displayId} from '@/lib/livestock';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const fields={name:'Name',sex:'Sex',breed:'Breed',dob:'Birth date',birthYear:'Birth year',origin:'Origin',registry:'Registry',registrationNumber:'Registration number',farm:'Breeder / farm',notes:'Notes'};
type Field=keyof typeof fields;
type Draft=Record<Field,string>;
const choices:Partial<Record<Field,string[]>>={sex:['Unknown','Female','Male','Castrated male'],origin:['Purchased','Home-raised']};
function values(a:Animal):Draft{const info=JSON.parse(a.pedigreeInfo||'{}');return Object.fromEntries(Object.keys(fields).map(k=>[k,k in a?String((a as any)[k]??''):String(info[k]||'')])) as Draft}
export default function BatchEdit({animals,year,disabled,onSaved}:{animals:Animal[];year:string;disabled:boolean;onSaved:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[selected,setSelected]=useState<string[]>([]),[rows,setRows]=useState<Animal[]>([]),[draft,setDraft]=useState<Record<string,Draft>>({}),[stage,setStage]=useState('select'),[page,setPage]=useState(0),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState<string[]>([]),[operations,setOperations]=useState<Record<string,string>>({});
 const [field,setField]=useState<Field>('breed'),[value,setValue]=useState('');
 const candidates=animals.filter(a=>!a.pedigreeOnly&&!a.archivedAt&&[label(a),displayId(a),a.rightTag,a.leftTag,a.eid,a.breed].some(v=>v?.toLowerCase().includes(query.toLowerCase())));
 const changes=rows.filter(a=>!saved.includes(a.id)&&JSON.stringify(values(a))!==JSON.stringify(draft[a.id]));
 function start(){setOpen(true);setQuery('');setSelected([]);setRows([]);setDraft({});setStage('select');setPage(0);setReason('');setError('');setSaved([])}
 function edit(){const chosen=animals.filter(a=>selected.includes(a.id));setRows(chosen);setDraft(Object.fromEntries(chosen.map(a=>[a.id,values(a)])));setOperations(Object.fromEntries(chosen.map(a=>[a.id,crypto.randomUUID()])));setStage('edit');setPage(0)}
 function update(id:string,k:Field,v:string){setDraft(d=>({...d,[id]:{...d[id],[k]:v}}))}
 async function save(){setBusy(true);setError('');const complete=[...saved];let failure='';for(const a of changes){try{const d=draft[a.id];const r=await fetch('/api/flock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'edit',year,data:{id:a.id,version:a.version,operationId:operations[a.id],reason:reason.trim(),name:d.name,breed:d.breed,sex:d.sex,origin:d.origin,dob:d.dob,birthYear:d.birthYear?Number(d.birthYear):null,info:{registry:d.registry,registrationNumber:d.registrationNumber,farm:d.farm,notes:d.notes}}})});const result:any=await r.json();if(!r.ok)throw Error(result.error||'Save failed');complete.push(a.id);setSaved([...complete])}catch(e){failure=label(a)+': '+(e instanceof Error?e.message:'Save failed');break}}setBusy(false);if(failure){setError(`${complete.length} saved. Remaining rows were not confirmed saved. ${failure} Retry to resume, or close and reopen after reloading for a conflict.`)}else{setStage('done')}await onSaved()}
 function input(k:Field,v:string,change:(v:string)=>void){return choices[k]?<select aria-label={fields[k]} value={v} onChange={e=>change(e.target.value)} className="border rounded p-2">{choices[k]!.map(x=><option key={x}>{x}</option>)}</select>:<input aria-label={fields[k]} className="border rounded p-2 min-w-40" type={k==='dob'?'date':k==='birthYear'?'number':'text'} value={v} maxLength={k==='notes'?2000:200} onChange={e=>change(e.target.value)}/>}
 return <><Button variant="outline" disabled={disabled||!animals.some(a=>!a.pedigreeOnly&&!a.archivedAt)} onClick={start}>Batch edit</Button><Dialog open={open} onOpenChange={o=>{if(!busy)setOpen(o)}}><DialogContent className="sm:max-w-[95vw] max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Batch edit animal profiles</DialogTitle><DialogDescription>Select up to 50 animals, edit the table, then review. Each saved animal keeps its own change history. Tags and status changes use their dedicated profile controls.</DialogDescription></DialogHeader>
 {stage==='select'&&<><AnimalSheet animals={candidates} selected={selected} onChange={setSelected} max={50}/><Button disabled={!selected.length} onClick={edit}>Edit selected animals</Button></>}
 {stage==='edit'&&<><div className="flex flex-wrap gap-2"><select aria-label="Field to apply" value={field} onChange={e=>{const k=e.target.value as Field;setField(k);setValue(choices[k]?.[0]||'')}}>{Object.entries(fields).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{input(field,value,setValue)}<Button variant="outline" onClick={()=>setDraft(d=>Object.fromEntries(Object.entries(d).map(([id,row])=>[id,saved.includes(id)?row:{...row,[field]:value}])))}>Apply to selected animals</Button></div><p className="hint">Blank birth details are allowed. A supplied birth date determines birth year. Empty ear-tag fields mean no tag. Blank tags and colors are not flagged.</p><div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Animal</th>{Object.entries(fields).map(([k,v])=><th key={k}>{v}</th>)}</tr></thead><tbody>{rows.slice(page*10,page*10+10).map(a=><tr key={a.id}><th>{label(a)}<small className="block">{displayId(a)}</small></th>{(Object.keys(fields) as Field[]).map(k=><td key={k}>{input(k,draft[a.id][k],v=>update(a.id,k,v))}</td>)}</tr>)}</tbody></table></div><div className="flex gap-2"><Button variant="outline" disabled={!page} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page+1} of {Math.ceil(rows.length/10)}</span><Button variant="outline" disabled={(page+1)*10>=rows.length} onClick={()=>setPage(page+1)}>Next</Button><Button disabled={!changes.length} onClick={()=>setStage('review')}>Review {changes.length} changed animals</Button></div></>}
 {stage==='review'&&<><p>{changes.length} animals to save. Saves are per animal; if one fails, earlier successful saves stay saved and remaining rows are held.</p><div className="max-h-72 overflow-y-auto">{changes.map(a=><div key={a.id} className="border-b py-2"><strong>{label(a)} · {displayId(a)}</strong>{(Object.keys(fields) as Field[]).filter(k=>values(a)[k]!==draft[a.id][k]).map(k=><p key={k}>{fields[k]}: {values(a)[k]||'(blank)'} → {draft[a.id][k]||'(blank)'}</p>)}</div>)}</div><label>Reason for changes<input className="border rounded p-2 w-full" value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} disabled={busy}/></label>{error&&<p role="alert" className="error">{error}</p>}<div className="flex gap-2"><Button variant="outline" disabled={busy||saved.length>0||!!error} onClick={()=>setStage('edit')}>Back to table</Button><Button disabled={busy||!reason.trim()||!changes.length} onClick={save}>{busy?'Saving…':error?'Retry remaining rows':'Save changes'}</Button></div></>}
 {stage==='done'&&<><p role="status">{saved.length} animal profiles saved. Their individual histories include your reason.</p><Button onClick={()=>setOpen(false)}>Done</Button></>}
 </DialogContent></Dialog></>;
}

