"use client";
import {useState} from 'react';
import type {CalendarEntry} from '@/lib/farm-calendar';
import {Button} from '@/components/ui/button';
export default function CalendarView({entries,year,onOpen}:{entries:CalendarEntry[];year:string;onOpen:(entry:CalendarEntry)=>void}){
 const today=new Date().toISOString().slice(0,10);
 const [mode,setMode]=useState('agenda'),[month,setMonth]=useState(year==='all'||year===today.slice(0,4)?today.slice(0,7):year+'-01'),[day,setDay]=useState(''),[type,setType]=useState('all');
 const filtered=entries.filter(e=>type==='all'||e.type===type),monthly=filtered.filter(e=>e.date.startsWith(month));
 const shown=mode==='agenda'?filtered:monthly.filter(e=>!day||e.date===day);
 const date=new Date(month+'-01T12:00:00Z'),offset=date.getUTCDay(),days=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth()+1,0)).getUTCDate();
 function shift(n:number){date.setUTCMonth(date.getUTCMonth()+n);const next=date.toISOString().slice(0,7);if(year==='all'||next.startsWith(year)){setMonth(next);setDay('')}}
 return <><div className="flex flex-wrap gap-2 my-3"><Button variant={mode==='agenda'?'default':'outline'} onClick={()=>setMode('agenda')}>Agenda</Button><Button variant={mode==='month'?'default':'outline'} onClick={()=>setMode('month')}>Month</Button><select className="border rounded p-2" aria-label="Calendar event type" value={type} onChange={e=>setType(e.target.value)}><option value="all">All event types</option>{[...new Set(entries.map(e=>e.type))].sort().map(t=><option key={t}>{t}</option>)}</select></div>
 {mode==='month'&&<><div className="flex flex-wrap items-center gap-2 my-3"><Button variant="outline" aria-label="Previous month" disabled={year!=='all'&&month.endsWith('-01')} onClick={()=>shift(-1)}>←</Button><label>Month <input aria-label="Calendar month" type="month" value={month} min={year==='all'?'1900-01':year+'-01'} max={year==='all'?'2100-12':year+'-12'} onChange={e=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value)&&(year==='all'||e.target.value.startsWith(year))){setMonth(e.target.value);setDay('')}}}/></label><Button variant="outline" aria-label="Next month" disabled={year!=='all'&&month.endsWith('-12')} onClick={()=>shift(1)}>→</Button><Button variant="outline" onClick={()=>setDay('')}>Whole month</Button></div><div className="grid grid-cols-7 gap-1" aria-label="Month calendar">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><small className="text-center" key={d}>{d}</small>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const d=month+'-'+String(i+1).padStart(2,'0'),count=monthly.filter(e=>e.date===d).length;return <button key={d} aria-pressed={day===d} aria-label={d+', '+count+' events'} className={'border rounded p-1 min-h-14 text-center '+(day===d?'bg-emerald-100 border-emerald-700':'')} onClick={()=>setDay(d)}><b>{i+1}</b><span className="block text-xs">{count?count+' '+(count===1?'event':'events'):'—'}</span></button>})}</div></>}
 {shown.map((e,i)=><div key={e.date+e.title+i} className="border-b py-3 flex justify-between items-center gap-2"><div><b>{e.date}</b> · {e.type}<p>{e.title}</p></div><Button variant="outline" onClick={()=>onOpen(e)}>{e.recordId?'Open record':'Open '+e.section}</Button></div>)}{!shown.length&&<p className="my-3">No matching events {day?'on '+day:mode==='month'?'this month':'in this view'}.</p>}</>;
}
