"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {dashboardUsers} from '@/lib/dashboard-access';
export default function ChangeHistory(){
 const [open,setOpen]=useState(false),[user,setUser]=useState(''),[rows,setRows]=useState<any[]>([]),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(who=user,start=0){setBusy(true);setError('');try{const r=await fetch('/api/flock/change-history?user='+encodeURIComponent(who)+'&offset='+start);if(!r.ok)throw Error('Could not load change history.');const d:any=await r.json();setRows(d.rows);setMore(d.more);setOffset(start)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><Button size="sm" variant="outline" onClick={()=>{setOpen(true);load()}}>Change history</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-5xl max-h-[85dvh] overflow-auto"><DialogHeader><DialogTitle>Changes by user</DialogTitle><DialogDescription>Tracks saves from the user ID selected at unlock. Earlier records have no user attribution. Unconfirmed requests may need review before retrying.</DialogDescription></DialogHeader><label>User ID <select className="border rounded p-2" value={user} onChange={e=>{setUser(e.target.value);load(e.target.value)}}><option value="">All users</option>{dashboardUsers.map(u=><option key={u}>{u}</option>)}</select></label>{error&&<p role="alert">{error}</p>}<div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{['Time','User ID','Section / action','Result','Details'].map(x=><th className="text-left border p-2" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="border p-2">{new Date(r.createdAt).toLocaleString()}</td><td className="border p-2">{r.userId}</td><td className="border p-2">{r.path.replace('/api/flock','Animals')} · {r.action}</td><td className="border p-2">{r.outcome}</td><td className="border p-2"><details><summary>Saved values</summary><pre className="max-w-lg whitespace-pre-wrap break-all">{JSON.stringify(JSON.parse(r.details),null,2)}</pre></details></td></tr>)}</tbody></table></div>{!busy&&!rows.length&&<p>No changes recorded for this selection.</p>}<div className="flex gap-2"><Button variant="outline" disabled={busy||offset===0} onClick={()=>load(user,Math.max(0,offset-100))}>Previous</Button><Button variant="outline" disabled={busy||!more} onClick={()=>load(user,offset+100)}>Next</Button></div></DialogContent></Dialog></>
}
