"use client";
import {useEffect,useState} from 'react';import type {Contact} from '@/lib/contacts';import {Button} from '@/components/ui/button';import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';import EventHistory from './event-history';
export default function ContactDirectory({year}:{year:string}){
 const [contacts,setContacts]=useState<Contact[]>([]),[draft,setDraft]=useState<Contact|null>(null),[op,setOp]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState(''),[archived,setArchived]=useState(false),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/flock/contacts'),d=await r.json() as any;if(!r.ok)throw Error(d.error);setContacts(d.contacts);setError('')}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[]);
 function open(c?:Contact){setDraft(c?{...c}:{id:crypto.randomUUID(),version:0,name:'',email:'',phone:'',address:'',role:'Supplier',notes:'',archived:false});setOp(crypto.randomUUID());setError('')}
 async function save(){setBusy(true);try{const r=await fetch('/api/flock/contacts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({year,operationId:op,data:draft})}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setDraft(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel mt-5"><div className="panel-top"><h2>Contacts</h2><Button disabled={year==='all'} onClick={()=>open()}>Add contact</Button></div><p>Reusable suppliers, veterinarians, buyers and other farm contacts.</p><input className="border rounded p-2 w-full" aria-label="Search contacts" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search contacts"/><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Show archived contacts</label>{error&&!draft&&<p role="alert">{error}</p>}{contacts.filter(c=>c.archived===archived&&[c.name,c.role,c.email,c.phone].some(v=>v.toLowerCase().includes(query.toLowerCase()))).map(c=><article className="border-b py-3" key={c.id}><h3>{c.name} · {c.role}</h3><p>{c.phone} {c.email}</p><p>{c.address}</p><Button variant="outline" disabled={year==='all'} onClick={()=>open(c)}>Edit / archive</Button><EventHistory id={c.id}/></article>)}<Dialog open={!!draft} onOpenChange={v=>{if(!v&&!busy)setDraft(null)}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Contact details</DialogTitle><DialogDescription>Archived contacts retain their history and existing transaction references.</DialogDescription></DialogHeader>{draft&&<><div className="form-grid">{(['name','email','phone','address','notes'] as const).map(k=><label key={k}>{k}<input className="border rounded p-2 w-full" value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<label>Role<select className="border rounded p-2 w-full" value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}>{['Supplier','Veterinarian','Buyer','Breeder','Co-owner','Other'].map(v=><option key={v}>{v}</option>)}</select></label></div><label><input type="checkbox" checked={draft.archived} onChange={e=>setDraft({...draft,archived:e.target.checked})}/> Archive contact</label>{error&&<p role="alert">{error}</p>}<Button disabled={busy||!draft.name.trim()} onClick={save}>{busy?'Saving…':'Save contact'}</Button></>}</DialogContent></Dialog></section>
}
