"use client";
import {useEffect,useState} from 'react';
import type {CustomField} from '@/lib/custom-fields';
import type {Animal} from '@/lib/livestock';
import {Button} from '@/components/ui/button';
const input='border rounded p-2 w-full';
export function FieldSettings({year}:{year:string}){
 const [fields,setFields]=useState<CustomField[]>([]),[version,setVersion]=useState(0),[original,setOriginal]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){try{const r=await fetch('/api/flock/settings'),d:any=await r.json();if(!r.ok)throw Error(d.error);setFields(d.fields);setVersion(d.version);setOriginal(d.fields.map((f:CustomField)=>f.id))}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[]);
 function change(id:string,key:keyof CustomField,value:unknown){setFields(fs=>fs.map(f=>f.id===id?{...f,[key]:value}:f));setNotice('')}
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/flock/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fields,version,year,operationId:crypto.randomUUID()})}),d:any=await r.json();if(!r.ok)throw Error(d.error);await load();setNotice('Custom fields saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel"><h2>Settings · custom animal fields</h2><p>Add optional fields for information specific to your farm. Existing field types are preserved; archive fields you no longer use.</p>{fields.map(f=><div className="form-grid border-b py-3" key={f.id}><label>Name<input className={input} maxLength={100} value={f.name} onChange={e=>change(f.id,'name',e.target.value)}/></label><label>Type<select className={input} disabled={original.includes(f.id)} value={f.type} onChange={e=>change(f.id,'type',e.target.value)}>{['Text','Number','Date','Yes/No','Choice'].map(t=><option key={t}>{t}</option>)}</select></label>{f.type==='Choice'&&<label>Choices, one per line<textarea className={input} value={f.choices.join('\n')} onChange={e=>change(f.id,'choices',e.target.value.split('\n'))}/></label>}<label><input type="checkbox" checked={f.archived} onChange={e=>change(f.id,'archived',e.target.checked)}/> Archived</label></div>)}<div className="flex gap-3 my-3"><Button variant="outline" disabled={fields.length>=100||year==='all'} onClick={()=>setFields([...fields,{id:crypto.randomUUID(),name:'',type:'Text',choices:[],archived:false}])}>Add field</Button><Button disabled={busy||year==='all'} onClick={save}>{busy?'Saving…':'Save field settings'}</Button></div>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>
}
export function AnimalCustomFields({animal,year,history,onSaved}:{animal:Animal;year:string;history:any[];onSaved:()=>Promise<void>}){
 const [fields,setFields]=useState<CustomField[]>([]),[values,setValues]=useState<Record<string,unknown>>(()=>JSON.parse(animal.pedigreeInfo||'{}').customValues||{}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{fetch('/api/flock/settings').then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error);setFields(d.fields)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{setValues(JSON.parse(animal.pedigreeInfo||'{}').customValues||{})},[animal.pedigreeInfo]);
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/flock/custom-values',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({animalId:animal.id,version:animal.version,year,values,operationId:crypto.randomUUID()})}),d:any=await r.json();if(!r.ok)throw Error(d.error);await onSaved();setNotice('Custom values saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details className="my-4"><summary>Custom animal fields ({fields.length})</summary>{fields.map(f=><label className="block my-2" key={f.id}>{f.name}{f.archived?' (archived)':''}{f.archived?<p>{String(values[f.id]??'Not recorded')}</p>:f.type==='Choice'||f.type==='Yes/No'?<select className={input} value={values[f.id]===null||values[f.id]===undefined?'':String(values[f.id])} onChange={e=>setValues({...values,[f.id]:e.target.value===''?null:f.type==='Yes/No'?e.target.value==='true':e.target.value})}><option value="">Not recorded</option>{(f.type==='Yes/No'?['true','false']:f.choices).map(v=><option value={v} key={v}>{f.type==='Yes/No'?v==='true'?'Yes':'No':v}</option>)}</select>:<input className={input} type={f.type==='Number'?'number':f.type==='Date'?'date':'text'} step="any" value={String(values[f.id]??'')} onChange={e=>setValues({...values,[f.id]:e.target.value===''?null:f.type==='Number'?Number(e.target.value):e.target.value})}/>}</label>)}{!fields.length&&<p>Create fields in Settings.</p>}<Button disabled={busy||year==='all'||!!animal.archivedAt||!fields.length} onClick={save}>Save custom values</Button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<details><summary>Custom value history</summary>{history.filter(h=>h.action==='custom-values').map(h=><div className="border-b py-2" key={h.operationId}><strong>{new Date(h.createdAt).toLocaleString()}</strong>{fields.map(f=>{const before=JSON.parse(JSON.parse(h.before).pedigreeInfo||'{}').customValues?.[f.id],after=JSON.parse(JSON.parse(h.after).pedigreeInfo||'{}').customValues?.[f.id];return before!==after?<p key={f.id}>{f.name}: {String(before??'Not recorded')} → {String(after??'Not recorded')}</p>:null})}</div>)}</details></details>
}
