"use client";
import {weightsThroughYear,formerDisplayIds,animalCsv} from '@/lib/foundation';
import {FieldSettings} from './custom-fields';
import useWorkspace from './use-workspace';
import SectionMenu from './section-menu';
import PracticeBanner from './practice-banner';
import OfflineSync from './offline-sync';
import RecordSearch from './record-search';
import ContactDirectory from './contact-directory';
import PeerGrowth from './peer-growth';
import AdjustedGrowth from './adjusted-growth';
import RecoveryWorkspace from './recovery-workspace';
import FarmOverview from './farm-overview';
import EventWorkspace from './event-workspace';
import LambingWorkspace from './lambing-workspace';
import BreedingWorkspace from './breeding-workspace';
import BatchEdit from './batch-edit';
import ReviewGuide from './review-guide';
import WeightWorkspace from './weight-workspace';
import {useEffect,useMemo,useState} from 'react';
import {statusAt} from '@/lib/animal-status';
import TagColor,{tagColor,ExtraTags} from './tag-color';
import AnimalActions from './animal-actions';
import AnimalEntrySheet from './animal-entry-sheet';
import AnimalImport from './animal-import';
import {recordFlags,type FlagRules} from '@/lib/record-flags';
import PedigreeWorkspace from './pedigree-workspace';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableHead,TableHeader,TableRow,TableCell} from '@/components/ui/table';
import {LayoutGrid,Leaf,Plus,Search,Download,Scale,GitBranch,ArrowUpRight,RefreshCw,Check,AlertTriangle} from 'lucide-react';
import {adg,displayId,label,visibleInYear,relationshipMatrix,projectedCoi,relation,type Animal,type Weight} from '@/lib/livestock';
// Birth profiles and birth weights now connect to the shared growth workflow.
const weightsEnabled=true;
const currentYear=new Date().getFullYear();
const sections=['Overall concept','Animal identity','Animal information','Ownership and registries','Status and year behavior','Lifetime profiles','Pedigree and genetics','Breeding','COI and relatedness','Cross-year breeding','Flushing','Lambing / kidding','Stillborn and neonatal losses','Rearing and weaning','Management groups','Weights','Female / sire performance','Health','Health-product inventory','Feed and rations','Financial system','Profit and offspring contribution','Sales','Working sessions','XR5000 and EID','Imports and historical data','Global search','Reports and exports','Dashboard','Calendar','Phone sidekick','Offline and sync','Backups and restore','Data ownership','Custom fields','Settings','Exclusions'];
const included=new Set([1,2,3,5,6,7,8,9,16,24,26,27,28,29,31,33,34,36]);
function Pick({value,onChange,options,label:aria}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value||'none'} onValueChange={v=>onChange(v==='none'?'':v)}><SelectTrigger aria-label={aria} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value||'none'}>{o.label}</SelectItem>)}</SelectContent></Select>}
function download(name:string,text:string,type:string){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function freshAnimal(species:string,year:string){return {id:crypto.randomUUID(),species,name:'',rightTag:'',rightTagColor:'',leftTag:'',leftTagColor:'',eid:'',sex:'Unknown',origin:'Purchased',dob:'',birthYear:'',firstYear:year,breed:'',sire:'',dam:''}}
export default function Dashboard(){
 const {species,year,setSpecies,setYear,reset:resetWorkspace}=useWorkspace(currentYear);
 const [view,setView]=useState('dashboard'),[query,setQuery]=useState('');
 const [eventTarget,setEventTarget]=useState('');
 const [flagRules,setFlagRules]=useState<FlagRules>({sex:true,birth:true});
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('flock-flag-rules')||'null');if(saved&&typeof saved.sex==='boolean'&&typeof saved.birth==='boolean')setFlagRules(saved)}catch{}},[]);
 function changeFlagRule(key:keyof FlagRules,value:boolean){const next={...flagRules,[key]:value};setFlagRules(next);try{localStorage.setItem('flock-flag-rules',JSON.stringify(next))}catch{}}
 const [statusFilter,setStatusFilter]=useState('Active');
 const [pedigreeRoot,setPedigreeRoot]=useState('');
 const [history,setHistory]=useState<any[]>([]);const [voidedWeights,setVoidedWeights]=useState<Weight[]>([]);
 const [animals,setAnimals]=useState<Animal[]>([]),[weights,setWeights]=useState<Weight[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [modal,setModal]=useState(''),[form,setForm]=useState<any>({}),[formError,setFormError]=useState(''),[saving,setSaving]=useState(false),[selected,setSelected]=useState<Animal|null>(null),[sire,setSire]=useState('');
 async function reload(){setLoading(true);setError('');try{const r=await fetch('/api/flock');const d:any=await r.json();if(!r.ok)throw Error(d.error);setAnimals(d.animals);setWeights(d.weights.filter((w:Weight)=>!w.voided));setVoidedWeights(d.weights.filter((w:Weight)=>w.voided));setHistory(d.history||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load records')}finally{setLoading(false)}}
 useEffect(()=>{reload();const refresh=()=>{reload()};window.addEventListener('flock-synced',refresh);return()=>window.removeEventListener('flock-synced',refresh)},[]);
 const years=Array.from(new Set([String(currentYear),String(currentYear+1),String(currentYear+2),year,...animals.map(a=>String(a.firstYear)),...[...weights,...voidedWeights].map(w=>w.date.slice(0,4)),...animals.flatMap(a=>(a.statusEvents||[]).flatMap(e=>e.date?[e.date.slice(0,4)]:[]))])).filter(y=>y!=='all').sort().reverse();
 const deleted=animals.filter(a=>a.archivedAt&&a.species===species&&(a.pedigreeOnly||visibleInYear(a,year)));
 const flock=animals.filter(a=>!a.pedigreeOnly&&!a.archivedAt&&a.species===species&&visibleInYear(a,year));
 const formerIdentifiers=(id:string)=>history.filter(h=>h.animalId===id).flatMap(h=>{try{const v=JSON.parse(h.before);const after=JSON.parse(h.after);return [...formerDisplayIds(history,id),v.rightTag,v.leftTag,v.eid,after.tagChange?.previous,after.tagChange?.otherPrevious,...(JSON.parse(v.pedigreeInfo||'{}').additionalTags||[]).map((t:any)=>t.number)]}catch{return []}});
 const found=(a:Animal)=>[...formerIdentifiers(a.id),a.name,a.rightTag,a.leftTag,a.eid,displayId(a),a.breed,a.pedigreeInfo].some(x=>x?.toLowerCase().includes(query.toLowerCase()));
 const statusDate=year==='all'?new Date().toISOString().slice(0,10):year+'-12-31';
 const activeFlock=flock.filter(a=>statusAt(a,statusDate)==='Active');
 const statusCandidates=query?animals.filter(a=>!a.archivedAt&&(a.pedigreeOnly||visibleInYear(a,year))&&found(a)):flock;
 const statusCounts=statusCandidates.reduce<Record<string,number>>((counts,a)=>{const status=statusAt(a,statusDate);counts[status]=(counts[status]||0)+1;return counts},{});
 const filtered=statusCandidates.filter(a=>statusFilter==='all'||statusAt(a,statusDate)===statusFilter);
 const ids=new Set(flock.map(a=>a.id));const measured=weights.filter(w=>ids.has(w.animalId)&&(year==='all'||w.date.startsWith(year)));
 const matrix=useMemo(()=>{try{return relationshipMatrix(animals)}catch{return null}},[animals]);
 const selectedSire=activeFlock.find(a=>a.id===sire&&a.sex==='Male');
 const editable=year!=='all'&&Number(year)<=currentYear&&!loading&&!error;
 function openAnimal(){setForm(freshAnimal(species,year));setFormError('');setModal('animal')}
 function openWeight(animalId=''){setForm({id:crypto.randomUUID(),animalId,date:year===String(currentYear)?new Date().toLocaleDateString('en-CA'):year+'-01-01',originalValue:'',unit:'lb',session:'Manual weighing'});setFormError('');setModal('weight')}
 function update(k:string,v:string){setForm((a:any)=>({...a,[k]:v}))}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setFormError('');try{const data=modal==='animal'?{...form,birthYear:form.birthYear?Number(form.birthYear):null,firstYear:Number(year)}:{...form,originalValue:Number(form.originalValue)};const r=await fetch('/api/flock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:modal,year,data})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setModal('');setNotice(modal==='animal'?'Animal saved.':'Measured weight saved.');await reload()}catch(e){setFormError(e instanceof Error?e.message:'Unable to save; please retry.')}finally{setSaving(false)}}
 async function exportCsv(){try{const r=await fetch('/api/flock/settings'),d=await r.json() as any;if(!r.ok)throw Error(d.error);download('flock-animals.csv',animalCsv(filtered,statusDate,d.fields),'text/csv')}catch(e){setNotice('Animal export could not load custom field definitions: '+(e as Error).message)}}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'search_flock_animals',title:'Search flock animals',description:'Search current animal identifiers across both species in the selected year and show matching animals.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(typeof input?.query!=='string'||input.query.length>200)throw Error('Enter a search query up to 200 characters.');setQuery(input.query);setView('animals');return {matches:animals.filter(a=>!a.archivedAt&&(a.pedigreeOnly||visibleInYear(a,year))&&[a.name,a.rightTag,a.leftTag,a.eid,displayId(a)].some(x=>x?.toLowerCase().includes(input.query.toLowerCase()))).map(a=>({id:a.id,name:label(a),species:a.species}))}}},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort()},[animals,year]);
 return <main className="workspace"><PracticeBanner/><OfflineSync/><header className="mast"><div className="brand"><Leaf/><span>Clarkson’s <b>Flock</b></span></div><RecordSearch animals={animals} history={history} onAnimal={a=>{setSpecies(a.species);setYear(String(currentYear));setSelected(a)}} onNavigate={(section,recordYear,recordSpecies)=>{if(recordSpecies==='Sheep'||recordSpecies==='Goats')setSpecies(recordSpecies);if(recordYear)setYear(recordYear);setView(section)}}/></header><div className="content"><div className="heading"><div><p className="eyebrow">YOUR FLOCK, THROUGH THE YEARS</p><h1>{({dashboard:'Farm dashboard',animals:'Animals',breeding:'Breeding',lambing:species==='Sheep'?'Lambing':'Kidding',calendar:'Calendar',reports:'Reports',health:'Health & inventory',feed:'Feed & rations',management:'Management groups',finance:'Finances',weights:'Weights & growth',settings:'Settings',recovery:'Backups & recovery',pedigree:'Pedigree',genetics:'Genetic evaluations',events:'Animal events',deleted:'Deleted animals',plan:'Build plan'} as Record<string,string>)[view]||'Flock overview'}</h1></div>{view==='animals'&&<div className="flex flex-wrap gap-2"><BatchEdit animals={filtered} year={year} disabled={!editable} onSaved={reload}/><AnimalImport animals={animals} species={species} year={year} disabled={!editable} onSaved={async (count,message)=>{setNotice(message||`${count} animals imported.`);await reload()}}/><AnimalEntrySheet animals={animals} species={species} year={year} disabled={!editable} onSaved={reload}/></div>}</div>
 <div className="toolbar"><Tabs value={species} onValueChange={v=>{setSpecies(v);setSire('');setQuery('')}}><TabsList><TabsTrigger value="Sheep">Sheep</TabsTrigger><TabsTrigger value="Goats">Goats</TabsTrigger></TabsList></Tabs><div className="year"><span>Year</span><Pick label="Year" value={year} onChange={setYear} options={[...years.map(y=>({value:y,label:y})),{value:'all',label:'All Years · read-only'}]}/><Button variant="outline" size="sm" onClick={()=>{setForm({year:''});setFormError('');setModal('year')}}>Historic year</Button></div></div>
 {Number(year)>currentYear&&<p className="banner">Future year · plan breeding and reminders here.</p>}{year==='all'&&<p className="banner">All Years shows lifetime records. Select a year to add information.</p>}
 {error&&<div className="error" role="alert">{error} <Button variant="outline" size="sm" onClick={reload}><RefreshCw/> Retry</Button></div>}{notice&&<p role="status" className="success"><Check size={16}/>{notice}</p>}

 <Tabs value={view} onValueChange={setView}><SectionMenu value={view} onChange={setView} species={species} deletedCount={deleted.length}/>
 <TabsContent value="animals"> <div className="metrics">{[['Total flock records',flock.length],['Active animals',activeFlock.length],['Females',activeFlock.filter(a=>a.sex==='Female').length],['Males',activeFlock.filter(a=>(a.sex==='Male'||a.sex==='Castrated male')).length],...(weightsEnabled?[['Recorded weights',measured.length]]:[])].map(([x,n])=><article className="metric" key={x}><span>{x}</span><strong>{loading?'…':error?'—':n}</strong><small>{species} · {year==='all'?'Lifetime':year}</small></article>)}</div><section className="panel"><div className="panel-top"><div><p className="eyebrow">LIFETIME ANIMAL RECORDS</p><h2>{query?'Search results':'Your '+species.toLowerCase()}</h2></div><Button variant="outline" disabled={loading||!!error} onClick={exportCsv}><Download/> CSV</Button></div><details className="flag-rules"><summary>Missing-detail flags</summary><p className="hint">Choose which missing details to flag. Flags never prevent saving. Preferences are remembered on this device.</p><div className="flex flex-wrap gap-5"><label><input type="checkbox" checked={flagRules.sex} onChange={e=>changeFlagRule("sex",e.target.checked)}/> Unknown sex</label><label><input type="checkbox" checked={flagRules.birth} onChange={e=>changeFlagRule("birth",e.target.checked)}/> Unknown birth date and year</label></div></details><div className="form-grid"><label>Status in selected year<select className="w-full border rounded p-2" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}>{['all','Active','Sold','Culled','Dead','Transferred','Unknown',...(statusCounts.Reference?['Reference']:[])].map(v=><option key={v} value={v}>{v==='all'?'All statuses':v} ({loading?'…':error?'—':v==='all'?statusCandidates.length:statusCounts[v]||0})</option>)}</select></label></div><p className="hint">Status counts match the search. Total flock records includes all statuses for the selected species and year; unowned ancestors and deleted records are excluded.</p><div className="search"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search both species by name, current or former tags, EID, ID or breed" aria-label="Search animals"/></div>{query&&<p className="hint">Searching both species in {year==='all'?'all years':year}.</p>}
 {filtered.length?<Table><TableHeader><TableRow>{['Animal','Right tag','Left tag','Sex / species','Status','Breed',...(weightsEnabled?['Latest weight']:[]),''].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(a=>{const w=weightsThroughYear(weights,year).filter(w=>w.animalId===a.id).sort((a,b)=>b.date.localeCompare(a.date))[0];return <TableRow key={a.id}><TableCell><button className="animal-link" onClick={()=>setSelected(a)}>{label(a)}</button><small className="sub">{displayId(a)}{a.eid?' · '+a.eid:''}</small>{recordFlags(a,flagRules).map(f=><span key={f} className="pill warn record-flag">{f}</span>)}</TableCell><TableCell>{a.rightTag||'—'}<TagColor animal={a} field="rightTag"/><ExtraTags animal={a} ear="Right"/></TableCell><TableCell>{a.leftTag||'—'}<TagColor animal={a} field="leftTag"/><ExtraTags animal={a} ear="Left"/></TableCell><TableCell>{a.sex}<small className="sub">{a.species}{a.pedigreeOnly?' · not owned':''}</small></TableCell><TableCell>{statusAt(a,statusDate)}</TableCell><TableCell>{a.breed||'Not entered'}</TableCell>{weightsEnabled&&<TableCell>{w?`${w.originalValue} ${w.unit}`:'—'}</TableCell>}<TableCell><Button variant="ghost" size="sm" aria-label={'Open '+label(a)} onClick={()=>setSelected(a)}><ArrowUpRight/></Button></TableCell></TableRow>})}</TableBody></Table>:<div className="empty">{loading?'Loading your flock…':error?'Records unavailable. Retry loading above.':query?'No matching animals.':'No animals recorded for this species and year.'}<small>{!loading&&!error&&!query?'Add an animal to start its lifetime record.':''}</small></div>}</section></TabsContent>
 {weightsEnabled&&<TabsContent value="weights"><section className="panel"><div className="panel-top"><div><p className="eyebrow">ACTUAL SCALE MEASUREMENTS</p><h2>Weights & growth</h2></div><Button disabled={!editable||!flock.length} onClick={()=>openWeight()}><Plus/> Record weight</Button></div><p className="hint">ADG uses the two most recent valid measurements on different dates through the selected year. All Years uses the full lifetime. Original measured units are retained.</p>{species==='Sheep'&&<AdjustedGrowth year={year} animals={flock} weights={weights.filter(w=>year==='all'||w.date<=year+'-12-31')}/>}<PeerGrowth key={'peers'+species+year} animals={flock} weights={weights} year={year}/><WeightWorkspace key={species+year} animals={flock} weights={[...weights,...voidedWeights]} history={history} year={year} editable={editable} onSaved={reload}/></section></TabsContent>}
 {(['dashboard','calendar','reports'] as const).map(mode=><TabsContent value={mode} key={mode}><FarmOverview key={mode+species+year} mode={mode} animals={animals} weights={weights} species={species} year={year} onNavigate={entry=>{setEventTarget(entry.recordId||'');setYear(entry.year);setView(entry.section)}}/></TabsContent>)}<TabsContent value="events"><EventWorkspace key={species+year} animals={animals} species={species} year={year} initialRecordId={eventTarget} onRecordOpened={()=>setEventTarget('')}/></TabsContent>{(['health','finance','management','feed','genetics'] as const).map(scope=><TabsContent key={scope} value={scope}><EventWorkspace key={scope+species+year} scope={scope} animals={animals} species={species} year={year}/></TabsContent>)}<TabsContent value="settings"><section className="panel"><h2>Workspace preferences</h2><p>This browser remembers your selected species and a separate year for Sheep and Goats. The home page opens on Dashboard.</p><Button variant="outline" onClick={resetWorkspace}>Reset to Sheep and current year</Button></section><FieldSettings year={year}/><ContactDirectory year={year}/></TabsContent><TabsContent value="recovery"><RecoveryWorkspace onSaved={reload}/></TabsContent><TabsContent value="lambing"><LambingWorkspace animals={animals} species={species} year={year} onSaved={reload} onYearChange={setYear}/></TabsContent><TabsContent value="breeding"><BreedingWorkspace animals={animals} species={species} year={year} onAnimalsSaved={reload}/></TabsContent><TabsContent value="pedigree"><PedigreeWorkspace animals={animals} species={species} year={year} rootId={pedigreeRoot} onRootChange={setPedigreeRoot} onReload={reload} onOpenAnimal={setSelected}/></TabsContent>


 <TabsContent value="deleted"><section className="panel"><h2>Deleted animals</h2><p className="hint">Deleted animals keep their identity, weights and pedigree links. Open a record to restore it.</p>{deleted.length?<Table><TableHeader><TableRow><TableHead>Animal</TableHead><TableHead>Deleted</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{deleted.map(a=><TableRow key={a.id}><TableCell>{label(a)}<small className="sub">{displayId(a)}</small></TableCell><TableCell>{new Date(a.archivedAt!).toLocaleDateString()}</TableCell><TableCell><Button variant="outline" onClick={()=>setSelected(a)}>Open / restore</Button></TableCell></TableRow>)}</TableBody></Table>:<div className="empty">No deleted animals in this species and year.</div>}</section></TabsContent>
 <TabsContent value="plan"><section className="panel"><p className="eyebrow">ALL 37 CAPABILITY AREAS PRESERVED</p><h2>From foundation to farm workflow</h2><p>Build order: animal identity, then breeding, then lambing and offspring, then weights and growth. Weight tools now connect to offspring birth records and support breeding-stock measurements. Saved measurements are preserved. All 37 requirement areas remain in scope.</p><div className="plan-grid">{['1 · Animal identity & records','2 · Breeding','3 · Lambing & offspring','4 · Weights, growth & performance','5 · Farm operations','6 · Finances','7 · Offline & recovery'].map((p,i)=><div key={p}><span className="pill">{i===0?'Available · Review pending':i===4?'Available · Open decisions':i===6?'Available · Automatic scheduling remains':'Available · Integration review'}</span><h3>{p}</h3></div>)}</div><a className="underline block my-3" href="/api/flock/backup/full">Download full backup including photos and registration files</a><a href="/api/flock/backup" className="underline">Download all records backup (photos/files excluded)</a><ReviewGuide/><details><summary>View all requirement areas</summary><div className="scope-list">{sections.map((s,i)=><p key={s}><span>{i+1}. {s}</span><span className="pill">{i===36?'Exclusions respected':'Coverage review in progress'}</span></p>)}</div></details><p className="caution">Current limits: unattended backup scheduling, complete nutritional planning remain unfinished. Feed allocation, management flags and dashboard inventory alerts are available. Manual offline sync, full backups with media, missing-record recovery, health protocols, cash reports, and saved report filters are available. Sheep and Goats remain partitioned within one database. The presence of a section does not mean every requirement is complete.</p><Button variant="outline" disabled={loading||!!error} onClick={()=>download('clarksons-flock-foundation.json',JSON.stringify({format:'clarksons-flock-foundation',version:1,exportedAt:new Date().toISOString(),animals,weights:[...weights,...voidedWeights],history},null,2),'application/json')}><Download/> Export all foundation records</Button></section></TabsContent>
 </Tabs><section className="note"><Leaf size={25}/><p><b>Your records stay yours.</b><br/>Export records and full photo backups from Backups & recovery. Offline changes stay pending on this device until you manually sync; file uploads require a connection.</p></section></div>
 <Dialog open={!!modal} onOpenChange={o=>{if(!saving&&!o)setModal('')}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{modal==='animal'?'Add '+(species==='Sheep'?'sheep':'goat'):modal==='weight'?'Record measured weight':'Open a historic year'}</DialogTitle><DialogDescription>{modal==='animal'?'Start a lifetime record. Name and tags are optional.':modal==='weight'?'Save an actual measurement; calculated feed weights do not belong here.':'Choose a year from 1900 through the current year.'}</DialogDescription></DialogHeader>
 {modal==='year'?<form onSubmit={e=>{e.preventDefault();const n=Number(form.year);if(!Number.isInteger(n)||n<1900||n>currentYear){setFormError('Enter a valid historical year.');return}setYear(String(n));setModal('')}}><label>Year<Input type="number" value={form.year} onChange={e=>update('year',e.target.value)} required min={1900} max={currentYear}/></label>{formError&&<p role="alert" className="error">{formError}</p>}<Button type="submit" className="mt-4">Open year</Button></form>:<form onSubmit={save}><div className="form-grid">{modal==='animal'?<>
 <label>Name<Input value={form.name} onChange={e=>update('name',e.target.value)} maxLength={200}/></label><label>Sex (optional)<Pick label="Sex" value={form.sex} onChange={v=>update('sex',v)} options={[{value:'',label:'Choose sex'},...['Unknown','Female','Male','Castrated male'].map(v=>({value:v,label:v}))]}/></label>
 <label>Right tag<Input value={form.rightTag} onChange={e=>update('rightTag',e.target.value)} maxLength={200}/></label><label>Right tag color<Input value={form.rightTagColor} onChange={e=>update('rightTagColor',e.target.value)} maxLength={60}/></label><label>Left tag<Input value={form.leftTag} onChange={e=>update('leftTag',e.target.value)} maxLength={200}/></label><label>Left tag color<Input value={form.leftTagColor} onChange={e=>update('leftTagColor',e.target.value)} maxLength={60}/></label><label>EID<Input value={form.eid} onChange={e=>update('eid',e.target.value)} maxLength={200}/></label><label>Breed / commercial description<Input value={form.breed} onChange={e=>update('breed',e.target.value)} maxLength={200}/></label>
 <label>Origin<Pick label="Origin" value={form.origin} onChange={v=>update('origin',v)} options={['Purchased','Home-raised'].map(v=>({value:v,label:v}))}/></label><label>Date of birth (optional)<Input type="date" onInput={e=>update('dob',e.currentTarget.value)} value={form.dob} onChange={e=>update('dob',e.target.value)}/></label>
 {!form.dob&&<label>Birth year (if known)<Input type="number" min={1900} max={currentYear} value={form.birthYear} onChange={e=>update('birthYear',e.target.value)}/></label>}<div className="field-note">First recorded year: <b>{year}</b><small>Earlier presence will not be invented from the date of birth.</small></div>
 {['sire','dam'].map(role=><label key={role}>{role==='sire'?'Sire':'Dam'}<Pick label={role} value={form[role]} onChange={v=>update(role,v)} options={[{value:'',label:'Unknown / not recorded'},...animals.filter(a=>!a.archivedAt&&a.species===species&&a.sex===(role==='sire'?'Male':'Female')).map(a=>({value:a.id,label:label(a)}))]}/></label>)}
 </>:<><label className="wide">Animal *<Pick label="Animal" value={form.animalId} onChange={v=>update('animalId',v)} options={[{value:'',label:'Choose animal'},...flock.map(a=>({value:a.id,label:label(a)}))]}/></label><label>Date *<Input type="date" onInput={e=>update('date',e.currentTarget.value)} value={form.date} onChange={e=>update('date',e.target.value)} required/></label><label>Measured weight *<Input type="number" step="any" min="0.001" value={form.originalValue} onChange={e=>update('originalValue',e.target.value)} required/></label><label>Unit<Pick label="Weight unit" value={form.unit} onChange={v=>update('unit',v)} options={[{value:'lb',label:'Pounds (lb)'},{value:'kg',label:'Kilograms (kg)'}]}/></label><label>Session name *<Input value={form.session} onChange={e=>update('session',e.target.value)} required maxLength={200}/></label></>}</div>{formError&&<p className="error" role="alert">{formError}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={saving} onClick={()=>setModal('')}>Cancel</Button><Button disabled={saving} type="submit">{saving?'Saving…':modal==='animal'?'Save animal':'Save weight'}</Button></div></form>}</DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={o=>{if(!o)setSelected(null)}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{selected?label(selected):'Animal'}</DialogTitle><DialogDescription>{selected?displayId(selected)+' · '+selected.species+(selected.pedigreeOnly?' · Pedigree only (not owned)':' · Lifetime record'):''}</DialogDescription></DialogHeader>{selected&&<>{recordFlags(selected,flagRules).length>0&&<p className="caution">Follow up when known: {recordFlags(selected,flagRules).join(" · ")}. You can keep using this record.</p>}<div className="detail-grid">{[['Sex',selected.sex],['Origin',selected.origin],['Breed',selected.breed||'Not entered'],['Birth',selected.dob||(selected.birthYear?selected.birthYear+' (approximate year)':'Unknown')],[selected.pedigreeOnly?'Record created for year':'First recorded',selected.firstYear],['Right tag',(selected.rightTag||'—')+(tagColor(selected,'rightTag')?' · '+tagColor(selected,'rightTag'):'')],['Left tag',(selected.leftTag||'—')+(tagColor(selected,'leftTag')?' · '+tagColor(selected,'leftTag'):'')],['EID',selected.eid||'—'],['Status in selected year',selected.archivedAt?'Deleted (restorable)':statusAt(selected,statusDate)]].map(([k,v])=><div key={k}><small>{k}</small><p>{v}</p></div>)}</div><AnimalActions key={selected.id+selected.version} animal={selected} animals={animals} year={year} history={history.filter(h=>h.animalId===selected.id)} onPedigree={()=>{setPedigreeRoot(selected.id);setSpecies(selected.species);setView("pedigree");setSelected(null)}} onSaved={async()=>{setSelected(null);setNotice("Animal record updated.");await reload()}}/><Button variant="outline" onClick={()=>{setPedigreeRoot(selected.id);setSpecies(selected.species);setView("pedigree");setSelected(null)}}>View / enter multiple generations</Button><EventWorkspace key={selected.id+year} animalId={selected.id} animals={animals} species={selected.species} year={year}/><h3>Recorded parents</h3><div className="parents">{['sire','dam'].map(role=>{const p=animals.find(a=>a.id===(selected as any)[role]);return <div key={role}><small>{role==='sire'?'Sire':'Dam'}</small>{p?<button className="animal-link" onClick={()=>setSelected(p)}>{label(p)} ↗</button>:<p>Unknown</p>}</div>})}</div>{weightsEnabled&&<><h3>Lifetime weights</h3>{weights.filter(w=>w.animalId===selected.id).map(w=><div className="weight-line" key={w.id}><span>{w.date}</span><b>{w.originalValue} {w.unit}</b><span>{w.session}</span></div>)}{!weights.some(w=>w.animalId===selected.id)&&<p className="hint">No measured weights yet.</p>}<Button disabled={!!selected.pedigreeOnly||!!selected.archivedAt||!editable||selected.species!==species||!visibleInYear(selected,year)} onClick={()=>{openWeight(selected.id);setSelected(null)}}><Plus/> Record weight</Button></>}</>}</DialogContent></Dialog>
 </main>
}
