"use client";
import {useEffect,useMemo,useState} from 'react';
import AnimalActions from './animal-actions';
import PedigreeWorkspace from './pedigree-workspace';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableHead,TableHeader,TableRow,TableCell} from '@/components/ui/table';
import {Leaf,Plus,Search,Download,Scale,GitBranch,ArrowUpRight,RefreshCw,Check,AlertTriangle} from 'lucide-react';
import {adg,displayId,label,visibleInYear,relationshipMatrix,projectedCoi,relation,type Animal,type Weight} from '@/lib/livestock';
const currentYear=new Date().getFullYear();
const sections=['Overall concept','Animal identity','Animal information','Ownership and registries','Status and year behavior','Lifetime profiles','Pedigree and genetics','Breeding','COI and relatedness','Cross-year breeding','Flushing','Lambing / kidding','Stillborn and neonatal losses','Rearing and weaning','Management groups','Weights','Female / sire performance','Health','Health-product inventory','Feed and rations','Financial system','Profit and offspring contribution','Sales','Working sessions','XR5000 and EID','Imports and historical data','Global search','Reports and exports','Dashboard','Calendar','Phone sidekick','Offline and sync','Backups and restore','Data ownership','Custom fields','Settings','Exclusions'];
const included=new Set([1,2,3,5,6,7,8,9,16,24,26,27,28,29,31,33,34,36]);
function Pick({value,onChange,options,label:aria}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value||'none'} onValueChange={v=>onChange(v==='none'?'':v)}><SelectTrigger aria-label={aria} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value||'none'}>{o.label}</SelectItem>)}</SelectContent></Select>}
function download(name:string,text:string,type:string){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function freshAnimal(species:string,year:string){return {id:crypto.randomUUID(),species,name:'',rightTag:'',leftTag:'',eid:'',sex:'',origin:'Purchased',dob:'',birthYear:'',firstYear:year,breed:'',sire:'',dam:''}}
export default function Dashboard(){
 const [species,setSpecies]=useState('Sheep'),[year,setYear]=useState(String(currentYear)),[view,setView]=useState('animals'),[query,setQuery]=useState('');
 const [pedigreeRoot,setPedigreeRoot]=useState('');
 const [history,setHistory]=useState<any[]>([]);
 const [animals,setAnimals]=useState<Animal[]>([]),[weights,setWeights]=useState<Weight[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [modal,setModal]=useState(''),[form,setForm]=useState<any>({}),[formError,setFormError]=useState(''),[saving,setSaving]=useState(false),[selected,setSelected]=useState<Animal|null>(null),[sire,setSire]=useState('');
 async function reload(){setLoading(true);setError('');try{const r=await fetch('/api/flock');const d:any=await r.json();if(!r.ok)throw Error(d.error);setAnimals(d.animals);setWeights(d.weights);setHistory(d.history||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load records')}finally{setLoading(false)}}
 useEffect(()=>{reload()},[]);
 const years=Array.from(new Set([String(currentYear),year,...animals.map(a=>String(a.firstYear)),...weights.map(w=>w.date.slice(0,4))])).filter(y=>y!=='all').sort().reverse();
 const deleted=animals.filter(a=>a.archivedAt&&a.species===species&&(a.pedigreeOnly||visibleInYear(a,year)));
 const flock=animals.filter(a=>!a.pedigreeOnly&&!a.archivedAt&&a.species===species&&visibleInYear(a,year));
 const found=(a:Animal)=>[a.name,a.rightTag,a.leftTag,a.eid,displayId(a),a.breed,a.pedigreeInfo].some(x=>x?.toLowerCase().includes(query.toLowerCase()));
 const filtered=(query?animals.filter(a=>!a.archivedAt&&(a.pedigreeOnly||visibleInYear(a,year))&&found(a)):flock);
 const ids=new Set(flock.map(a=>a.id));const measured=weights.filter(w=>ids.has(w.animalId)&&(year==='all'||w.date.startsWith(year)));
 const matrix=useMemo(()=>{try{return relationshipMatrix(animals)}catch{return null}},[animals]);
 const selectedSire=animals.find(a=>a.id===sire);
 const editable=year!=='all'&&!loading&&!error;
 function openAnimal(){setForm(freshAnimal(species,year));setFormError('');setModal('animal')}
 function openWeight(animalId=''){setForm({id:crypto.randomUUID(),animalId,date:year===String(currentYear)?new Date().toLocaleDateString('en-CA'):year+'-01-01',originalValue:'',unit:'lb',session:'Manual weighing'});setFormError('');setModal('weight')}
 function update(k:string,v:string){setForm((a:any)=>({...a,[k]:v}))}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setFormError('');try{const data=modal==='animal'?{...form,birthYear:form.birthYear?Number(form.birthYear):null,firstYear:Number(year)}:{...form,originalValue:Number(form.originalValue)};const r=await fetch('/api/flock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:modal,year,data})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setModal('');setNotice(modal==='animal'?'Animal saved.':'Measured weight saved.');await reload()}catch(e){setFormError(e instanceof Error?e.message:'Unable to save; please retry.')}finally{setSaving(false)}}
 function exportCsv(){const keys=['id','species','name','rightTag','leftTag','eid','sex','dob','birthYear','breed','firstYear','status'];const safe=(v:unknown)=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};download('flock-animals.csv',[keys.join(','),...filtered.map(a=>keys.map(k=>safe(k==='id'?displayId(a):(a as any)[k])).join(','))].join('\r\n'),'text/csv')}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'search_flock_animals',title:'Search flock animals',description:'Search current animal identifiers across both species in the selected year and show matching animals.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(typeof input?.query!=='string'||input.query.length>200)throw Error('Enter a search query up to 200 characters.');setQuery(input.query);setView('animals');return {matches:animals.filter(a=>!a.archivedAt&&(a.pedigreeOnly||visibleInYear(a,year))&&[a.name,a.rightTag,a.leftTag,a.eid,displayId(a)].some(x=>x?.toLowerCase().includes(input.query.toLowerCase()))).map(a=>({id:a.id,name:label(a),species:a.species}))}}},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort()},[animals,year]);
 return <main className="workspace"><header className="mast"><div className="brand"><Leaf/><span>Clarkson’s <b>Flock</b></span></div><span className="phase">Working version · Foundation</span></header><div className="content"><div className="heading"><div><p className="eyebrow">YOUR FLOCK, THROUGH THE YEARS</p><h1>Flock overview</h1></div><Button disabled={!editable} onClick={openAnimal}><Plus/> Add animal</Button></div>
 <div className="toolbar"><Tabs value={species} onValueChange={v=>{setSpecies(v);setSire('');setQuery('')}}><TabsList><TabsTrigger value="Sheep">Sheep</TabsTrigger><TabsTrigger value="Goats">Goats</TabsTrigger></TabsList></Tabs><div className="year"><span>Year</span><Pick label="Year" value={year} onChange={setYear} options={[...years.map(y=>({value:y,label:y})),{value:'all',label:'All Years · read-only'}]}/><Button variant="outline" size="sm" onClick={()=>{setForm({year:''});setFormError('');setModal('year')}}>Historic year</Button></div></div>
 {year==='all'&&<p className="banner">All Years shows lifetime records. Select a year to add information.</p>}
 {error&&<div className="error" role="alert">{error} <Button variant="outline" size="sm" onClick={reload}><RefreshCw/> Retry</Button></div>}{notice&&<p role="status" className="success"><Check size={16}/>{notice}</p>}
 <div className="metrics">{[['Active animals',flock.length],['Females',flock.filter(a=>a.sex==='Female').length],['Males',flock.filter(a=>a.sex!=='Female').length],['Recorded weights',measured.length]].map(([x,n])=><article className="metric" key={x}><span>{x}</span><strong>{loading?'…':error?'—':n}</strong><small>{species} · {year==='all'?'Lifetime':year}</small></article>)}</div>
 <Tabs value={view} onValueChange={setView}><TabsList className="view-tabs" variant="line"><TabsTrigger value="animals">Animals</TabsTrigger><TabsTrigger value="weights"><Scale size={14}/> Weights</TabsTrigger><TabsTrigger value="pedigree">Pedigree</TabsTrigger><TabsTrigger value="breeding"><GitBranch size={14}/> Breeding screen</TabsTrigger><TabsTrigger value="deleted">Deleted animals ({deleted.length})</TabsTrigger><TabsTrigger value="plan">Build plan</TabsTrigger></TabsList>
 <TabsContent value="animals"><section className="panel"><div className="panel-top"><div><p className="eyebrow">LIFETIME ANIMAL RECORDS</p><h2>{query?'Search results':'Your '+species.toLowerCase()}</h2></div><Button variant="outline" disabled={loading||!!error} onClick={exportCsv}><Download/> CSV</Button></div><div className="search"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search both species by name, tags, EID, ID or breed" aria-label="Search animals"/></div>{query&&<p className="hint">Searching both species in {year==='all'?'all years':year}.</p>}
 {filtered.length?<Table><TableHeader><TableRow>{['Animal','Right tag','Left tag','Sex / species','Breed','Latest weight',''].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(a=>{const w=weights.filter(w=>w.animalId===a.id).sort((a,b)=>b.date.localeCompare(a.date))[0];return <TableRow key={a.id}><TableCell><button className="animal-link" onClick={()=>setSelected(a)}>{label(a)}</button><small className="sub">{displayId(a)}{a.eid?' · '+a.eid:''}</small></TableCell><TableCell>{a.rightTag||'—'}</TableCell><TableCell>{a.leftTag||'—'}</TableCell><TableCell>{a.sex}<small className="sub">{a.species}{a.pedigreeOnly?' · not owned':''}</small></TableCell><TableCell>{a.breed||'Not entered'}</TableCell><TableCell>{w?`${w.originalValue} ${w.unit}`:'—'}</TableCell><TableCell><Button variant="ghost" size="sm" aria-label={'Open '+label(a)} onClick={()=>setSelected(a)}><ArrowUpRight/></Button></TableCell></TableRow>})}</TableBody></Table>:<div className="empty">{loading?'Loading your flock…':error?'Records unavailable. Retry loading above.':query?'No matching animals.':'No animals recorded for this species and year.'}<small>{!loading&&!error&&!query?'Add an animal to start its lifetime record.':''}</small></div>}</section></TabsContent>
 <TabsContent value="weights"><section className="panel"><div className="panel-top"><div><p className="eyebrow">ACTUAL SCALE MEASUREMENTS</p><h2>Weights & growth</h2></div><Button disabled={!editable||!flock.length} onClick={()=>openWeight()}><Plus/> Record weight</Button></div><p className="hint">ADG uses the two most recent lifetime measurements on different dates. Original measured units are retained.</p>{measured.length?<Table><TableHeader><TableRow>{['Animal','Date','Actual weight','Session','Lifetime latest ADG'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{measured.map(w=>{const a=animals.find(a=>a.id===w.animalId)!;const g=adg(weights.filter(v=>v.animalId===a.id));return <TableRow key={w.id}><TableCell><button className="animal-link" onClick={()=>setSelected(a)}>{label(a)}</button></TableCell><TableCell>{w.date}</TableCell><TableCell>{w.originalValue} {w.unit}</TableCell><TableCell>{w.session}</TableCell><TableCell>{g===null?'Needs two dates':g.toFixed(3)+' lb/day'}</TableCell></TableRow>})}</TableBody></Table>:<div className="empty">No measured weights in this view.<small>Add an animal, then record its scale weight.</small></div>}</section></TabsContent>
 <TabsContent value="pedigree"><PedigreeWorkspace animals={animals} species={species} year={year} rootId={pedigreeRoot} onRootChange={setPedigreeRoot} onReload={reload} onOpenAnimal={setSelected}/></TabsContent>
 <TabsContent value="breeding"><section className="panel"><p className="eyebrow">CHECK THE PEDIGREE BEFORE PAIRING</p><h2>{species==='Sheep'?'Ram':'Buck'}-first screening</h2><div className="max-picker"><Pick label="Select sire" value={sire} onChange={setSire} options={[{value:'',label:'Choose a '+(species==='Sheep'?'ram':'buck')},...flock.filter(a=>a.sex==='Male').map(a=>({value:a.id,label:label(a)}))]}/></div><p className="caution"><AlertTriangle size={17}/> Known-pedigree estimate only. Missing ancestors are assumed unrelated; a low value does not establish that a mating is unrelated.</p>{selectedSire&&matrix?<Table><TableHeader><TableRow>{['Female','Known-pedigree COI','Relationship','Screening result'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{flock.filter(a=>a.sex==='Female').map(a=>{const coi=projectedCoi(matrix,sire,a.id);return <TableRow key={a.id}><TableCell><button className="animal-link" onClick={()=>setSelected(a)}>{label(a)}</button></TableCell><TableCell>{(coi*100).toFixed(2)}%</TableCell><TableCell>{relation(selectedSire,a)}</TableCell><TableCell><span className={coi>.2?'pill danger':coi>=.15?'pill warn':'pill'}>{coi>.2?'Excluded (>20%)':coi>=.2?'Strong warning':coi>=.15?'Warning':'Below warning threshold'}</span></TableCell></TableRow>})}</TableBody></Table>:<div className="empty">Choose a recorded sire to calculate prospective offspring COI.<small>Use the Pedigree tab to enter both family lines, including ancestors you do not own. This screen does not create breeding groups.</small></div>}<p className="hint">Thresholds from the PDF: warning at 15%, strong warning at 20%, exclude strictly above 20%. Saved groups, exposure dates and configurable thresholds are planned.</p></section></TabsContent>
 <TabsContent value="deleted"><section className="panel"><h2>Deleted animals</h2><p className="hint">Deleted animals keep their identity, weights and pedigree links. Open a record to restore it.</p>{deleted.length?<Table><TableHeader><TableRow><TableHead>Animal</TableHead><TableHead>Deleted</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{deleted.map(a=><TableRow key={a.id}><TableCell>{label(a)}<small className="sub">{displayId(a)}</small></TableCell><TableCell>{new Date(a.archivedAt!).toLocaleDateString()}</TableCell><TableCell><Button variant="outline" onClick={()=>setSelected(a)}>Open / restore</Button></TableCell></TableRow>)}</TableBody></Table>:<div className="empty">No deleted animals in this species and year.</div>}</section></TabsContent>
 <TabsContent value="plan"><section className="panel"><p className="eyebrow">ALL 37 CAPABILITY AREAS PRESERVED</p><h2>From foundation to farm workflow</h2><p>This first version supports animal entry, weights, known-pedigree screening and exports. The full nine-page specification remains the scope.</p><div className="plan-grid">{['1 · Animal foundation','2 · History & sessions','3 · Reproduction','4 · Health, feed & calendar','5 · Financial ledger','6 · Offline & recovery'].map((p,i)=><div key={p}><span className="pill">{i===0?'First working slice':'Planned'}</span><h3>{p}</h3></div>)}</div><details><summary>View all requirements and first-build coverage</summary><div className="scope-list">{sections.map((s,i)=><p key={s}><span>{i+1}. {s}</span><span className="pill">{i===36?'Exclusions respected':included.has(i+1)?'Partial foundation':'Planned'}</span></p>)}</div></details><p className="caution">Important limits: online-only; current identifiers only; no status transitions, automated backups, restore, imports, health or financial ledger yet. Sheep and Goats are partitioned within one database. The separate review explains the proposed architecture and open decisions.</p><Button variant="outline" disabled={loading||!!error} onClick={()=>download('clarksons-flock-foundation.json',JSON.stringify({format:'clarksons-flock-foundation',version:1,exportedAt:new Date().toISOString(),animals,weights,history},null,2),'application/json')}><Download/> Export all foundation records</Button></section></TabsContent>
 </Tabs><section className="note"><Leaf size={25}/><p><b>Your records stay yours.</b><br/>CSV and JSON exports are available. This foundation requires an internet connection; full backup/restore and offline sessions are planned.</p></section></div>
 <Dialog open={!!modal} onOpenChange={o=>{if(!saving&&!o)setModal('')}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{modal==='animal'?'Add '+(species==='Sheep'?'sheep':'goat'):modal==='weight'?'Record measured weight':'Open a historic year'}</DialogTitle><DialogDescription>{modal==='animal'?'Start a lifetime record. Name and tags are optional.':modal==='weight'?'Save an actual measurement; calculated feed weights do not belong here.':'Choose a year from 1900 through the current year.'}</DialogDescription></DialogHeader>
 {modal==='year'?<form onSubmit={e=>{e.preventDefault();const n=Number(form.year);if(!Number.isInteger(n)||n<1900||n>currentYear){setFormError('Enter a valid historical year.');return}setYear(String(n));setModal('')}}><label>Year<Input type="number" value={form.year} onChange={e=>update('year',e.target.value)} required min={1900} max={currentYear}/></label>{formError&&<p role="alert" className="error">{formError}</p>}<Button type="submit" className="mt-4">Open year</Button></form>:<form onSubmit={save}><div className="form-grid">{modal==='animal'?<>
 <label>Name<Input value={form.name} onChange={e=>update('name',e.target.value)} maxLength={200}/></label><label>Sex *<Pick label="Sex" value={form.sex} onChange={v=>update('sex',v)} options={[{value:'',label:'Choose sex'},...['Female','Male','Castrated male'].map(v=>({value:v,label:v}))]}/></label>
 <label>Right tag<Input value={form.rightTag} onChange={e=>update('rightTag',e.target.value)} maxLength={200}/></label><label>Left tag<Input value={form.leftTag} onChange={e=>update('leftTag',e.target.value)} maxLength={200}/></label><label>EID<Input value={form.eid} onChange={e=>update('eid',e.target.value)} maxLength={200}/></label><label>Breed / commercial description<Input value={form.breed} onChange={e=>update('breed',e.target.value)} maxLength={200}/></label>
 <label>Origin<Pick label="Origin" value={form.origin} onChange={v=>update('origin',v)} options={['Purchased','Home-raised'].map(v=>({value:v,label:v}))}/></label><label>Date of birth {form.origin==='Home-raised'?'*':''}<Input type="date" value={form.dob} onChange={e=>update('dob',e.target.value)} required={form.origin==='Home-raised'}/></label>
 {!form.dob&&<label>Birth year (if known)<Input type="number" min={1900} max={currentYear} value={form.birthYear} onChange={e=>update('birthYear',e.target.value)}/></label>}<div className="field-note">First recorded year: <b>{year}</b><small>Earlier presence will not be invented from the date of birth.</small></div>
 {['sire','dam'].map(role=><label key={role}>{role==='sire'?'Sire':'Dam'}<Pick label={role} value={form[role]} onChange={v=>update(role,v)} options={[{value:'',label:'Unknown / not recorded'},...animals.filter(a=>!a.archivedAt&&a.species===species&&a.sex===(role==='sire'?'Male':'Female')).map(a=>({value:a.id,label:label(a)}))]}/></label>)}
 </>:<><label className="wide">Animal *<Pick label="Animal" value={form.animalId} onChange={v=>update('animalId',v)} options={[{value:'',label:'Choose animal'},...flock.map(a=>({value:a.id,label:label(a)}))]}/></label><label>Date *<Input type="date" value={form.date} onChange={e=>update('date',e.target.value)} required/></label><label>Measured weight *<Input type="number" step="any" min="0.001" value={form.originalValue} onChange={e=>update('originalValue',e.target.value)} required/></label><label>Unit<Pick label="Weight unit" value={form.unit} onChange={v=>update('unit',v)} options={[{value:'lb',label:'Pounds (lb)'},{value:'kg',label:'Kilograms (kg)'}]}/></label><label>Session name *<Input value={form.session} onChange={e=>update('session',e.target.value)} required maxLength={200}/></label></>}</div>{formError&&<p className="error" role="alert">{formError}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={saving} onClick={()=>setModal('')}>Cancel</Button><Button disabled={saving} type="submit">{saving?'Saving…':modal==='animal'?'Save animal':'Save weight'}</Button></div></form>}</DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={o=>{if(!o)setSelected(null)}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{selected?label(selected):'Animal'}</DialogTitle><DialogDescription>{selected?displayId(selected)+' · '+selected.species+(selected.pedigreeOnly?' · Pedigree only (not owned)':' · Lifetime record'):''}</DialogDescription></DialogHeader>{selected&&<><div className="detail-grid">{[['Sex',selected.sex],['Breed',selected.breed||'Not entered'],['Birth',selected.dob||(selected.birthYear?selected.birthYear+' (approximate year)':'Unknown')],[selected.pedigreeOnly?'Record created for year':'First recorded',selected.firstYear],['Right tag',selected.rightTag||'—'],['Left tag',selected.leftTag||'—'],['EID',selected.eid||'—'],['Status',selected.archivedAt?'Deleted (restorable)':selected.status]].map(([k,v])=><div key={k}><small>{k}</small><p>{v}</p></div>)}</div><AnimalActions key={selected.id+selected.version} animal={selected} animals={animals} year={year} history={history.filter(h=>h.animalId===selected.id)} onSaved={async()=>{setSelected(null);setNotice("Animal record updated.");await reload()}}/><Button variant="outline" onClick={()=>{setPedigreeRoot(selected.id);setSpecies(selected.species);setView("pedigree");setSelected(null)}}>View / enter multiple generations</Button><h3>Recorded parents</h3><div className="parents">{['sire','dam'].map(role=>{const p=animals.find(a=>a.id===(selected as any)[role]);return <div key={role}><small>{role==='sire'?'Sire':'Dam'}</small>{p?<button className="animal-link" onClick={()=>setSelected(p)}>{label(p)} ↗</button>:<p>Unknown</p>}</div>})}</div><h3>Lifetime weights</h3>{weights.filter(w=>w.animalId===selected.id).map(w=><div className="weight-line" key={w.id}><span>{w.date}</span><b>{w.originalValue} {w.unit}</b><span>{w.session}</span></div>)}{!weights.some(w=>w.animalId===selected.id)&&<p className="hint">No measured weights yet.</p>}<Button disabled={!!selected.pedigreeOnly||!!selected.archivedAt||!editable||selected.species!==species||!visibleInYear(selected,year)} onClick={()=>{openWeight(selected.id);setSelected(null)}}><Plus/> Record weight</Button></>}</DialogContent></Dialog>
 </main>
}
