"use client";
import {useRef,useState} from 'react';
export type SheetColumn={key:string;label:string;type?:'text'|'number'|'date';options?:string[];readOnly?:boolean};
export default function EntrySheet({columns,rows,onChange,onRemove,onAdd,limit=200,disabled=false}:{columns:SheetColumn[];rows:Record<string,string>[];onChange:(rows:Record<string,string>[])=>void;onRemove?:(index:number)=>void;onAdd?:()=>void;limit?:number;disabled?:boolean}){
 const ref=useRef<HTMLDivElement>(null),[error,setError]=useState('');
 function paste(e:React.ClipboardEvent<HTMLInputElement|HTMLSelectElement>,row:number,col:number){const text=e.clipboardData.getData('text/plain');if(!text.includes('\t')&&!text.includes('\n'))return;e.preventDefault();const cells=text.replace(/\r\n/g,'\n').replace(/\r/g,'\n').replace(/\n$/,'').split('\n').map(r=>r.split('\t'));if(row+cells.length>rows.length||row+cells.length>limit){setError('Add enough rows before pasting. Nothing was changed.');return;}if(cells.some(r=>col+r.length>columns.length)){setError('Pasted cells exceed the available columns. Nothing was changed.');return;}const next=rows.map(r=>({...r}));for(let r=0;r<cells.length;r++)for(let c=0;c<cells[r].length;c++){const column=columns[col+c],value=cells[r][c].trim();if(column.readOnly){setError('The pasted range includes a read-only column. Start in an editable cell.');return;}if(value&&column.type==='number'&&!Number.isFinite(Number(value))){setError(`Row ${row+r+1}, ${column.label}: enter a number. Nothing was changed.`);return;}if(value&&column.type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value)){setError(`Row ${row+r+1}, ${column.label}: use YYYY-MM-DD. Nothing was changed.`);return;}if(column.options&&!column.options.includes(value)){setError(`Row ${row+r+1}, ${column.label}: choose ${column.options.join(', ')}. Nothing was changed.`);return;}next[row+r][column.key]=value;}setError('');onChange(next);}
 function enter(e:React.KeyboardEvent<HTMLInputElement|HTMLSelectElement>,row:number,col:number){if(e.key!=='Enter')return;e.preventDefault();const target=ref.current?.querySelector<HTMLElement>(`[data-cell="${row+(e.shiftKey?-1:1)}:${col}"]`);target?.focus();}
 return <div className="entry-sheet-block"><div className="entry-sheet-toolbar"><strong>{rows.length} rows</strong><span>Tab → next cell · Enter ↓ next row · Paste Excel cells</span><span className="entry-sheet-draft">Unsaved worksheet</span></div><div ref={ref} className="entry-sheet-scroll"><table className="entry-sheet"><thead><tr><th className="sheet-row-number">#</th>{columns.map((c,i)=><th key={c.key}><small>{String.fromCharCode(65+i)}</small>{c.label}</th>)}{onRemove&&<th>Row</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}><th className="sheet-row-number">{i+1}</th>{columns.map((c,j)=><td key={c.key} className={c.readOnly?'sheet-readonly':''}>{c.readOnly?<span>{r[c.key]}</span>:c.options?<select aria-label={`${c.label}, row ${i+1}`} data-cell={`${i}:${j}`} disabled={disabled} value={r[c.key]||''} onPaste={e=>paste(e,i,j)} onKeyDown={e=>enter(e,i,j)} onChange={e=>{setError('');onChange(rows.map((v,n)=>n===i?{...v,[c.key]:e.target.value}:v))}}>{c.options.map(v=><option key={v} value={v}>{v||'Not entered'}</option>)}</select>:<input aria-label={`${c.label}, row ${i+1}`} data-cell={`${i}:${j}`} disabled={disabled} type={c.type||'text'} value={r[c.key]||''} step="any" onPaste={e=>paste(e,i,j)} onKeyDown={e=>enter(e,i,j)} onChange={e=>{setError('');onChange(rows.map((v,n)=>n===i?{...v,[c.key]:e.target.value}:v))}}/>}</td>)}{onRemove&&<td><button type="button" disabled={disabled} aria-label={`Remove row ${i+1}`} onClick={()=>onRemove(i)}>Remove</button></td>}</tr>)}</tbody></table></div>{error&&<p role="alert" className="error">{error}</p>}{onAdd&&<button type="button" className="sheet-add-row" disabled={disabled||rows.length>=limit} onClick={onAdd}>＋ Add row</button>}</div>
}
