"use client";
import {useState} from 'react';import {Button} from '@/components/ui/button';
export type EventDocument={id:string;name:string;type:string;size:number;uploadedAt:string;removedAt?:string};
export default function EventDocuments({event,year,onSaved}:{event:{id:string;version:number;date:string;voided?:boolean;attachments?:EventDocument[]};year:string;onSaved:()=>Promise<void>}){
 const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(action:string,fileId=''){setBusy(true);setError('');try{const form=new FormData();form.set('eventId',event.id);form.set('operationId',crypto.randomUUID());form.set('version',String(event.version));form.set('year',year);form.set('action',action);form.set('fileId',fileId);if(file)form.set('file',file);const r=await fetch('/api/flock/events/files',{method:'POST',body:form}),d:any=await r.json();if(!r.ok)throw Error(d.error);setFile(null);await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const editable=year!=='all'&&event.date.startsWith(year)&&!event.voided;
 return <details className="my-2"><summary>Documents ({event.attachments?.filter(f=>!f.removedAt).length||0})</summary>{event.attachments?.map(f=><div className="flex flex-wrap gap-2 my-2" key={f.id}>{f.removedAt?<span>{f.name} (removed)</span>:<a className="underline" target="_blank" rel="noreferrer" href={'/api/flock/events/files?event='+event.id+'&file='+f.id}>{f.name}</a>}<Button variant="ghost" size="sm" disabled={!editable||busy} onClick={()=>save(f.removedAt?'restore':'remove',f.id)}>{f.removedAt?'Restore':'Remove'}</Button></div>)}{editable&&<><label>Attach lab report, bill or supporting document<input key={event.version} className="block" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" disabled={busy} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><Button variant="outline" disabled={!file||busy} onClick={()=>save('upload')}>{busy?'Saving…':'Upload document'}</Button></>}{error&&<p role="alert">{error}</p>}</details>
}
