"use client";
import AnimalPicker from './animal-picker';
import {useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {label,type Animal,relationshipMatrix} from '@/lib/livestock';
import {sharedFamily} from '@/lib/female-relationships';
export default function FemaleRelationships({animals,flock,species,matrix,onPedigree,loading,error}:{animals:Animal[];flock:Animal[];species:string;matrix:ReturnType<typeof relationshipMatrix>|null;onPedigree:(a:Animal)=>void;loading:boolean;error:string}){
 const [first,setFirst]=useState(''),[second,setSecond]=useState('');
 const females=flock.filter(a=>a.sex==='Female').sort((a,b)=>label(a).localeCompare(label(b),undefined,{numeric:true}));
 const a=females.find(a=>a.id===first),b=females.find(a=>a.id===second),family=a&&b?sharedFamily(a,b,animals):null;
 const pairs=useMemo(()=>{if(!matrix)return [];const f=flock.filter(a=>a.sex==='Female'),pairs:{a:Animal;b:Animal;value:number}[]=[];for(let i=0;i<f.length;i++)for(let j=i+1;j<f.length;j++){const value=matrix.get(f[i].id,f[j].id);if(value>0)pairs.push({a:f[i],b:f[j],value})}return pairs.sort((a,b)=>b.value-a.value)},[flock,matrix]);
 const shown=a?pairs.filter(p=>p.a.id===a.id||p.b.id===a.id):pairs;
 const female=species==='Sheep'?'ewe':'doe';
 function picker(value:string,set:(v:string)=>void,exclude:string,title:string){return <label>{title}<AnimalPicker value={value||'none'} onValueChange={v=>set(v==='none'?'':v)} aria-label={title} animals={females.filter(a=>a.id!==exclude)} clearValue="none" placeholder="Choose"/></label>}
 const generation=(n:number)=>n===0?'This animal':n===1?'Parent':n===2?'Grandparent':`Ancestor, ${n} generations back`;
 return <section className="panel female-relationships"><p className="eyebrow">FEMALE FAMILY CONNECTIONS</p><h2>{species==='Sheep'?'Ewe':'Doe'} relationships</h2><p>Compare two females or browse related pairs in the selected year. Unowned ancestors and earlier generations are included in the calculation.</p><p className="caution">These estimates use recorded pedigree only. Missing ancestry can hide a relationship; 0% means no relationship was found in the records.</p>
 {loading?<p role="status">Loading relationships…</p>:error?<p role="alert" className="error">Relationships are unavailable until records reload successfully.</p>:!matrix?<p role="alert" className="error">The pedigree contains a missing ancestor or conflicting link. Correct it before comparing relationships.</p>:females.length<2?<p className="empty">Record at least two {female}s to compare them. Animals with unknown sex can be updated through Edit animal details.</p>:<>
 <div className="female-pickers">{picker(a?.id||'',v=>{setFirst(v);if(v===second)setSecond('')},b?.id||'',`First ${female}`)}{picker(b?.id||'',setSecond,a?.id||'',`Second ${female}`)}<Button variant="outline" onClick={()=>{setFirst('');setSecond('')}}>Show all pairs</Button></div>
 {a&&b&&family&&<div className="female-comparison"><h3>{label(a)} & {label(b)}</h3><p><strong>{(matrix.get(a.id,b.id)*100).toFixed(2)}%</strong> pedigree relationship · {family.description}</p><p className="hint">This is their estimated pedigree relationship, not offspring COI. With unrelated, non-inbred parents, full sisters average 50%, half sisters 25%, and first cousins 12.5%.</p><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>onPedigree(a)}>View {label(a)}’s pedigree</Button><Button variant="outline" onClick={()=>onPedigree(b)}>View {label(b)}’s pedigree</Button></div>{family.shared.length?<><h3>Shared family records</h3><Table><TableHeader><TableRow><TableHead>Ancestor</TableHead><TableHead>For {label(a)}</TableHead><TableHead>For {label(b)}</TableHead></TableRow></TableHeader><TableBody>{family.shared.map(p=><TableRow key={p.animal.id}><TableCell><button className="animal-link" onClick={()=>onPedigree(p.animal)}>{label(p.animal)}</button>{p.animal.pedigreeOnly?<small className="sub">Unowned ancestor</small>:null}</TableCell><TableCell>{generation(p.left)}</TableCell><TableCell>{generation(p.right)}</TableCell></TableRow>)}</TableBody></Table></>:<p>No common ancestors or direct family link are recorded for this pair.</p>}</div>}
 <h3>{a?`Related to ${label(a)}`:'Related female pairs'} ({shown.length})</h3>{shown.length?<Table><TableHeader><TableRow><TableHead>Females</TableHead><TableHead>Relationship</TableHead><TableHead>Pedigree estimate</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{shown.map(p=><TableRow key={p.a.id+p.b.id}><TableCell>{label(p.a)} & {label(p.b)}</TableCell><TableCell>{sharedFamily(p.a,p.b,animals).description}</TableCell><TableCell>{(p.value*100).toFixed(2)}%</TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>{setFirst(p.a.id);setSecond(p.b.id)}}>Compare</Button></TableCell></TableRow>)}</TableBody></Table>:<p>No related pairs were found in the recorded pedigree{a?` for ${label(a)}`:''}. Missing parent records can affect this result.</p>}
 </>}
 </section>
}
