"use client";
import {useState} from 'react';
import type {Animal} from '@/lib/livestock';
import {groupMembers,managementGroups} from '@/lib/management-groups';
import {planGroupTransfer,type TransferInput} from '@/lib/group-transfer';
import {useGroups} from './group-context';
import {AnimalSheet} from './animal-picker';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function GroupTransfer({animals,species,date}:{animals:Animal[];species:string;date:string}){
 const {events,loading,error:loadError,reload}=useGroups(),groups=managementGroups(events,species);
 const [draft,setDraft]=useState<TransferInput|null>(null),[operation,setOperation]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [versions,setVersions]=useState<{id:string;version:number}[]>([]);
 const sourceIds=draft?groupMembers(events,draft.from,draft.date):new Set<string>();
 const change=(patch:Partial<TransferInput>)=>{setDraft(d=>d?{...d,...patch}:d);setReview(false);setError('')};
 function preview(){if(!draft)return;try{planGroupTransfer(events,draft,()=>crypto.randomUUID());setError('');setVersions(events.filter(e=>e.kind==='management'&&e.species===species).map(e=>({id:e.id,version:e.version})));setReview(true)}catch(e){setError((e as Error).message)}}
 async function save(){if(!draft)return;setBusy(true);try{const r=await fetch('/api/flock/groups/transfer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,operationId:operation,versions})}),data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error||'Transfer could not be saved.');setNotice(`${draft.animalIds.length} animals transferred. Earlier membership history is preserved.`);setDraft(null);window.dispatchEvent(new Event('flock-synced'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><Button disabled={loading||!!loadError||!groups.length} onClick={()=>{setDraft({species,from:'',to:'',newName:'',date,endDate:'',animalIds:[]});setOperation(crypto.randomUUID());setReview(false);setError('');setNotice('')}}>Transfer animals</Button>{notice&&<p role="status">{notice}</p>}<Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null)}}><DialogContent className="event-entry-dialog max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Transfer animals</DialogTitle><DialogDescription>Selected animals leave the source group the day before the transfer date and join the destination on that date. Other group memberships stay unchanged.</DialogDescription></DialogHeader>{draft&&<>{!review?<><div className="form-grid"><label>From group<select value={draft.from} onChange={e=>change({from:e.target.value,animalIds:[]})}><option value="">Choose source group</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>To group<select value={draft.to} onChange={e=>change({to:e.target.value})}><option value="">Create new group</option>{groups.filter(g=>g.id!==draft.from).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>{!draft.to&&<label>New group name<input value={draft.newName} maxLength={200} onChange={e=>change({newName:e.target.value})}/></label>}<label>Transfer / start date<input type="date" max={new Date().toISOString().slice(0,10)} value={draft.date} onChange={e=>change({date:e.target.value,animalIds:[]})}/></label><label>Destination end date (optional)<input type="date" min={draft.date} value={draft.endDate} onChange={e=>change({endDate:e.target.value})}/></label></div>{draft.from&&<AnimalSheet showGroupFilter={false} animals={animals.filter(a=>a.species===species&&sourceIds.has(a.id))} selected={draft.animalIds} onChange={ids=>change({animalIds:ids})} disabled={busy}/>}<Button disabled={loading||!!loadError||!draft.animalIds.length} onClick={preview}>Review transfer</Button></>:<><p><strong>{draft.animalIds.length} animals</strong> from {groups.find(g=>g.id===draft.from)?.name} to {groups.find(g=>g.id===draft.to)?.name||draft.newName}.</p><p>Start: {draft.date} · End: {draft.endDate||'Ongoing'}</p><p>Animals not selected remain in the source group. This moves group membership only; it does not change ownership, status or breeding exposures.</p><Button variant="outline" disabled={busy} onClick={()=>setReview(false)}>Back</Button><Button disabled={busy||loading||!!loadError} onClick={save}>{busy?'Transferring…':'Confirm transfer'}</Button></>}{(error||loadError)&&<p role="alert">{error||loadError} <Button variant="outline" disabled={busy} onClick={()=>{reload();setReview(false)}}>Reload groups</Button></p>}</>}</DialogContent></Dialog></>
}
