"use client";
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import type {PDFDocumentProxy} from 'pdfjs-dist';
export default function ImportPdf({file,onText}:{file:File;onText:(text:string,page:number)=>void}){
 const [doc,setDoc]=useState<PDFDocumentProxy|null>(null),[page,setPage]=useState(1),[text,setText]=useState(''),[error,setError]=useState('');const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{let active=true,task:any;setError('');setDoc(null);setPage(1);(async()=>{const pdf=await import('pdfjs-dist');pdf.GlobalWorkerOptions.workerSrc=`/pdf.worker.min.mjs?v=${pdf.version}`;if(!active)return;task=pdf.getDocument({data:new Uint8Array(await file.arrayBuffer())});const d=await task.promise;if(!active){await d.destroy();return}if(d.numPages>100){await d.destroy();throw Error('Use a PDF with 100 pages or fewer.')}setDoc(d)})().catch(e=>{if(active)setError(e.message)});return()=>{active=false;task?.destroy() }},[file]);
 useEffect(()=>{if(!doc)return;let active=true,render:any;setText('');setError('');(async()=>{const p=await doc.getPage(page);if(!active||!canvas.current)return;const viewport=p.getViewport({scale:Math.min(1.5,1100/p.getViewport({scale:1}).width)});canvas.current.width=viewport.width;canvas.current.height=viewport.height;render=p.render({canvas:canvas.current,viewport});await render.promise;const content=await p.getTextContent();if(active)setText(content.items.map((i:any)=>i.str?i.str+(i.hasEOL?'\n':' '):'').join(''))})().catch(e=>{if(active&&e.name!=='RenderingCancelledException')setError(e.message)});return()=>{active=false;render?.cancel()}},[doc,page]);
 return <aside className="import-pdf"><div className="flex flex-wrap items-center gap-2"><Button type="button" variant="outline" disabled={!doc||page<=1} onClick={()=>setPage(page-1)}>Previous page</Button><span>Page {page} of {doc?.numPages||'…'}</span><Button type="button" variant="outline" disabled={!doc||page>=doc.numPages} onClick={()=>setPage(page+1)}>Next page</Button></div>{error&&<p role="alert" className="error">{error}</p>}<canvas ref={canvas} aria-label={`PDF page ${page}`}/><details><summary>Extracted page text</summary><pre>{text||'No selectable text found. Read the displayed page and enter the animal details.'}</pre></details><Button type="button" variant="outline" disabled={!text} onClick={()=>onText(text,page)}>Draft animal from labeled text</Button><p className="hint">Only clearly labeled fields are copied. Review the draft against the page; parent links and unlabeled family trees need manual entry.</p></aside>
}

