"use client";
import type {FarmEvent} from '@/lib/farm-events';
import {lotBalance} from '@/lib/farm-events';
import {label,type Animal} from '@/lib/livestock';
import type {CalendarEntry} from '@/lib/farm-calendar';
import {Flag,PackageCheck,AlertTriangle} from 'lucide-react';
import {Button} from '@/components/ui/button';
export default function ManagementAlerts({events,animals,species,year,onOpen}:{events:FarmEvent[];animals:Animal[];species:string;year:string;onOpen:(e:CalendarEntry)=>void}){
 const today=new Date().toISOString().slice(0,10),through=year==='all'?today:year+'-12-31'<today?year+'-12-31':today,eligible=events.filter(e=>e.species===species&&!e.voided&&e.date<=through);
 const watches=eligible.filter(e=>e.kind==='watch'&&e.watch&&(!e.watch.resolvedDate||e.watch.resolvedDate>through));
 const lots=eligible.filter(e=>e.kind==='stock'&&e.stock).map(e=>({e,b:lotBalance(e,events,through)!})).filter(({e,b})=>e.stock!.expires&&e.stock!.expires<through&&b.remaining>0||e.stock!.lowAt!==null&&b.remaining<=e.stock!.lowAt);
 const open=(e:FarmEvent)=>onOpen({date:e.date,title:e.title,type:e.kind,section:'events',year:e.date.slice(0,4),recordId:e.id});
 return <div className="grid md:grid-cols-2 gap-4 my-5"><section className="border rounded-xl p-4"><h3 className="flex items-center gap-2"><Flag size={19}/> Management watch ({watches.length})</h3><p className="hint">Open as of {through}, including flags from earlier years.</p>{watches.map(e=><article key={e.id} className="border-b py-3"><strong>{e.title}</strong><p>{e.category}{e.dueDate?' · Follow-up '+e.dueDate:''}</p><p className="hint">{e.animalIds.map(id=>{const a=animals.find(a=>a.id===id);return a?label(a):'Unavailable animal'}).join(', ')}</p><Button size="sm" variant="outline" onClick={()=>open(e)}>Review / resolve</Button></article>)}{!watches.length&&<p className="my-3">No open management flags.</p>}<p className="hint">Add a Management flag in Animal events or Management groups.</p></section><section className="border rounded-xl p-4"><h3 className="flex items-center gap-2"><PackageCheck size={19}/> Health inventory alerts ({lots.length})</h3><p className="hint">Recorded stock and given doses through {through}.</p>{lots.map(({e,b})=><article key={e.id} className="border-b py-3"><strong className="flex items-center gap-2"><AlertTriangle size={16}/>{e.title}</strong><p>{b.remaining} {e.stock!.unit} remaining</p>{e.stock!.expires&&e.stock!.expires<through&&b.remaining>0&&<p className="caution">Expired {e.stock!.expires}</p>}{e.stock!.lowAt!==null&&b.remaining<=e.stock!.lowAt&&<p className="caution">At or below your low-stock threshold ({e.stock!.lowAt})</p>}<Button size="sm" variant="outline" onClick={()=>open(e)}>Review inventory lot</Button></article>)}{!lots.length&&<p className="my-3">No recorded low-stock or expired-stock alerts.</p>}</section></div>
}
