"use client";
import {useState} from 'react';
import {type PendingChange,replacePending} from '@/lib/offline-store';
import {Button} from '@/components/ui/button';
const labels:Record<string,string>={title:'Title',notes:'Notes',date:'Record date',category:'Category',dueDate:'Follow-up date'};
export default function OfflineConflict({change,transport,onChanged}:{change:PendingChange;transport:typeof fetch;onChanged:()=>Promise<void>}){
 const [serverEpoch,setServerEpoch]=useState('0');
 const [current,setCurrent]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[usePending,setUsePending]=useState<string[]>([]);
 const body=JSON.parse(change.body),data=body.data;
 const path=change.url,collections:Record<string,string[]>={'/api/flock':['animals','weights'],'/api/flock/events':['events'],'/api/flock/breeding':['groups'],'/api/flock/lambing':['litters'],'/api/flock/projects':['projects'],'/api/flock/contacts':['contacts'],'/api/flock/report-presets':['presets']};
 if(!data?.id||!collections[path])return null;
 async function compare(){setBusy(true);setMessage('');try{const r=await transport(path,{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error||'Current records unavailable.');setServerEpoch(r.headers.get('X-Flock-Epoch')||'0');const row=collections[path].flatMap(k=>d[k]||[]).find(r=>r.id===data.id);setCurrent(row||null);setUsePending([]);if(!row)setMessage('No matching server record. This may be a new entry.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 const fields=current?Object.keys(data).filter(k=>!['id','version','operationId'].includes(k)&&JSON.stringify(data[k]??null)!==JSON.stringify(current[k]??null)):[];
 const canMerge=path==='/api/flock/events'&&['note','reminder'].includes(data.kind)&&current?.kind===data.kind&&!current.voided&&!data.voided&&(!body.action||body.action==='save');
 async function prepare(){if(!canMerge||!usePending.length)return;setBusy(true);try{const merged={...current};for(const k of usePending)merged[k]=data[k];const operationId=crypto.randomUUID();await replacePending(change,{key:path+':'+operationId,url:path,epoch:serverEpoch,createdAt:new Date().toISOString(),body:JSON.stringify({year:merged.date.slice(0,4),action:'save',operationId,data:merged})});await onChanged();}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <div className="my-2"><Button variant="outline" disabled={busy} onClick={compare}>Compare with current server record</Button>{message&&<p role="status">{message}</p>}{current&&<><p>Server revision {current.version}; pending revision {data.version??'new record'}. The server is unchanged by this review.</p>{fields.length===0?<p>These submitted fields match the current server record.</p>:fields.map(k=><div className="border rounded p-2 my-2" key={k}><strong>{labels[k]||k}</strong><div className="grid sm:grid-cols-2 gap-2"><div><small>Current server value</small><p className="whitespace-pre-wrap break-all">{typeof current[k]==='string'?current[k]:JSON.stringify(current[k]??'Not entered')}</p></div><div><small>Pending device value</small><p className="whitespace-pre-wrap break-all">{typeof data[k]==='string'?data[k]:JSON.stringify(data[k]??'Not entered')}</p></div></div>{canMerge&&labels[k]&&<label><input type="checkbox" checked={usePending.includes(k)} onChange={e=>setUsePending(e.target.checked?[...usePending,k]:usePending.filter(v=>v!==k))}/> Use the pending {labels[k].toLowerCase()}</label>}</div>)}{canMerge&&<><p>Select the note/reminder fields to keep from this device. All other fields keep their current server values. This prepares another pending copy; you still choose when to sync it.</p><Button variant="outline" disabled={busy||!usePending.length} onClick={prepare}>Prepare reviewed pending copy</Button></>}{!canMerge&&<p>Resolve this record in its normal editor after reviewing both copies. Automatic merging is not available for this record type.</p>}</>}</div>;
}

