"use client";
import {useEffect,useRef,useState} from 'react';
import {localStore,type PendingChange} from '@/lib/offline-store';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const readable=new Set(['/api/flock','/api/flock/events','/api/flock/breeding','/api/flock/lambing','/api/flock/projects','/api/flock/settings','/api/flock/report-presets']);
const writable=new Set([...readable,'/api/flock/weights','/api/flock/weight-sessions','/api/flock/ownership','/api/flock/import','/api/flock/pedigree-import','/api/flock/custom-values','/api/flock/evaluation-import']);
export default function OfflineSync(){
 const [shellReady,setShellReady]=useState(false);
 const [pending,setPending]=useState<PendingChange[]>([]),[offline,setOffline]=useState(false),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<string[]>([]);
 useEffect(()=>{if(!('serviceWorker' in navigator))return;const receive=(event:MessageEvent)=>{if(event.data?.type==='SHELL_CACHE_READY')setShellReady(event.data.complete)};navigator.serviceWorker.addEventListener('message',receive);navigator.serviceWorker.register('/offline-worker.js').catch(()=>{});const cache=()=>{navigator.serviceWorker.ready.then(reg=>reg.active?.postMessage({type:'CACHE_LOADED_ASSETS',urls:performance.getEntriesByType('resource').map(r=>r.name)})).catch(()=>{})};cache();window.addEventListener('load',cache);return()=>{window.removeEventListener('load',cache);navigator.serviceWorker.removeEventListener('message',receive)}},[]);
 const transport=useRef<typeof fetch|null>(null);
 async function refresh(){try{setPending((await localStore('queue','all')).sort((a:PendingChange,b:PendingChange)=>a.createdAt.localeCompare(b.createdAt)))}catch(e){setError('Local working copies are unavailable: '+(e as Error).message)}}
 useEffect(()=>{
  const original=window.fetch.bind(window);transport.current=original;
  const wrapped:typeof fetch=async(input,init)=>{
   const url=typeof input==='string'?new URL(input,location.origin):null;if(!url||url.origin!==location.origin)return original(input,init);
   const path=url.pathname;if(!readable.has(path)&&!writable.has(path))return original(input,init);const method=init?.method?.toUpperCase()||'GET';let change:PendingChange|undefined;
   if(method==='POST'&&writable.has(path)&&typeof init?.body==='string'){try{const b=JSON.parse(init.body),id=b.operationId||b.data?.operationId||(['animal','ancestor'].includes(b.action)?b.data?.id:null);if(id){change={key:path+':'+id,url:path,body:init.body,createdAt:new Date().toISOString()};const previous:PendingChange|undefined=await localStore('queue','get',change.key);if(previous&&previous.body!==change.body)return Response.json({error:'A different version of this save is pending on this device. Review Pending saves before making another change.'},{status:409});}}catch{/* Continue online if local storage cannot be read. */}}
   try{const response=await original(input,init);if(response.ok){setOffline(false);if(method==='GET'&&readable.has(path)){try{await localStore('cache','put',{key:path,body:await response.clone().text(),savedAt:new Date().toISOString()})}catch{}}if(change){await localStore('queue','delete',change.key).catch(()=>{});refresh()}return response;}if(response.status<500)return response;throw Error('The server did not confirm this request.');
   }catch(e){setOffline(true);if(method==='GET'&&readable.has(path)){const cached=await localStore('cache','get',path).catch(()=>null);if(cached)return new Response(cached.body,{headers:{'Content-Type':'application/json','X-Working-Copy':cached.savedAt}})}
    if(change){try{await localStore('queue','put',change);refresh();return Response.json({error:'Saved on this device, but not confirmed by the server. Use Pending saves to sync manually when connected.'},{status:503})}catch{return Response.json({error:'The server is unavailable and this device could not keep a working copy. Keep this form open and retry.'},{status:503})}}
    throw e;
   }
  };
  window.fetch=wrapped;refresh();const update=()=>setOffline(!navigator.onLine);update();window.addEventListener('offline',update);window.addEventListener('online',update);return()=>{if(window.fetch===wrapped)window.fetch=original;window.removeEventListener('offline',update);window.removeEventListener('online',update)};
 },[]);
 async function sync(){setBusy(true);setError('');try{for(const change of pending.filter(c=>selected.includes(c.key))){try{const r=await transport.current!(change.url,{method:'POST',headers:{'Content-Type':'application/json'},body:change.body}),d:any=await r.json();if(!r.ok){await localStore('queue','put',{...change,error:d.error||'Server did not confirm the save.'});continue}await localStore('queue','delete',change.key);}catch{await localStore('queue','put',{...change,error:'Connection interrupted. This save remains pending.'});break}}await refresh();window.dispatchEvent(new Event('flock-synced'));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><div className="flex flex-wrap items-center gap-3 px-4 py-2 border-b">{offline&&<strong>Offline / server unavailable · showing last loaded records</strong>}<Button variant="outline" size="sm" onClick={()=>{refresh();setOpen(true)}}>Pending saves ({pending.length})</Button><span className="text-sm">{shellReady?'Offline reload ready':'Preparing offline reload…'}</span>{error&&<span role="alert">{error}</span>}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-2xl max-h-[85dvh] overflow-y-auto"><DialogHeader><DialogTitle>Pending saves on this device</DialogTitle><DialogDescription>Nothing syncs automatically. A save stays here until the server confirms it. {shellReady?'The loaded application screens are cached for offline reload.':'Keep this page open until offline reload is ready.'} Photo uploads and recovery require a connection.</DialogDescription></DialogHeader><Button variant="outline" onClick={()=>setSelected(pending.map(c=>c.key))}>Select all</Button>{pending.map(c=><article className="border rounded p-3" key={c.key}><label><input type="checkbox" checked={selected.includes(c.key)} onChange={e=>setSelected(e.target.checked?[...selected,c.key]:selected.filter(k=>k!==c.key))}/> {new Date(c.createdAt).toLocaleString()} · {c.url.split('/').at(-1)}</label>{c.error&&<p role="alert">{c.error}</p>}<details><summary>Review saved values</summary><pre className="whitespace-pre-wrap break-all text-sm">{JSON.stringify(JSON.parse(c.body),null,2)}</pre></details><Button variant="ghost" disabled={busy} onClick={async()=>{if(!window.confirm('Discard this device’s pending copy? This does not undo anything already saved on the server.'))return;await localStore('queue','delete',c.key);await refresh()}}>Discard local copy</Button></article>)}{!pending.length&&<p>No pending saves.</p>}<Button disabled={busy||!selected.some(k=>pending.some(c=>c.key===k))} onClick={sync}>{busy?'Syncing…':'Sync selected saves'}</Button></DialogContent></Dialog></>
}
