"use client";
import AnimalPicker from './animal-picker';
import {useState} from 'react';
import {planPedigreeImport} from '@/lib/pedigree-import';
import type {Animal} from '@/lib/livestock';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {label} from '@/lib/livestock';
import {Button} from '@/components/ui/button';
export default function PedigreeImportPreview({grid,animals,year,species,onSaved,onBack}:{grid:string[][];animals:Animal[];year:string;species:string;onSaved:(message:string)=>Promise<void>;onBack:()=>void}){
 const [overrides,setOverrides]=useState<Record<string,string>>({});
 const [confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const plan=planPedigreeImport(grid,animals,Number(year),species,overrides);
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/flock/pedigree-import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({grid,year,species,overrides,revision:plan.revision})});const d:any=await r.json();if(!r.ok)throw Error(d.error);await onSaved(`Pedigrees updated for ${d.matched} animals; ${d.ancestors} unowned ancestor records added.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section><h3>Update existing pedigrees</h3><p>{plan.matched} existing animals matched · {plan.created.length} new unowned ancestors. Shared parents are reused. Blank parent cells keep existing links.</p><p className="hint">Animal registration numbers and flock names are also retained. Existing animal records are updated, not imported again.</p>{plan.skipped.length>0&&<details open><summary>{plan.skipped.length} unmatched rows will be left out</summary><ul>{plan.skipped.map(s=><li key={s}>{s}<AnimalPicker value={overrides[s.match(/^Row (\d+)/)![1]]||'skip'} onValueChange={v=>{setOverrides({...overrides,[s.match(/^Row (\d+)/)![1]]:v==='skip'?'':v});setConfirmed(false)}} aria-label={'Match '+s} animals={animals.filter(a=>a.species===species&&!a.archivedAt)} clearValue="skip" placeholder="Leave this row out"/></li>)}</ul></details>}<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>Animal</th><th>Sire</th><th>Dam</th></tr></thead><tbody>{plan.preview.map(p=><tr key={p.row}><td className="p-2">{p.animal}</td><td className="p-2">{p.sire}</td><td className="p-2">{p.dam}</td></tr>)}</tbody></table></div>{(error||plan.errors.length>0)&&<p role="alert" className="error whitespace-pre-line">{error||plan.errors.join('\n')}</p>}<label className="import-confirm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/> I reviewed the parent matches and rows being left out.</label><div className="form-actions"><Button variant="outline" disabled={busy} onClick={onBack}>Back to columns</Button><Button disabled={busy||!confirmed||!!plan.errors.length||!plan.matched} onClick={save}>{busy?'Saving pedigrees…':'Save pedigree updates'}</Button></div></section>
}
