"use client";
import {useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {type Animal,label,displayId} from '@/lib/livestock';
type Role='sire'|'dam';
type Editor={kind:'link'|'details'|'new';childId?:string;role?:Role;animalId?:string};
type Fields={id:string;name:string;sex:string;breed:string;dob:string;birthYear:string;farm:string;registry:string;registrationNumber:string;notes:string};
function fresh(sex='Male'):Fields{return {id:crypto.randomUUID(),name:'',sex,breed:'',dob:'',birthYear:'',farm:'',registry:'',registrationNumber:'',notes:''}}
function fieldsFor(a:Animal):Fields{let info:any={};try{info=JSON.parse(a.pedigreeInfo||'{}')}catch{}return {...fresh(a.sex),...info,id:a.id,name:a.name,sex:a.sex,breed:a.breed,dob:a.dob||'',birthYear:a.birthYear?String(a.birthYear):''}}
function AncestorFields({fields,setFields,sexLocked}:{fields:Fields;setFields:(v:Fields)=>void;sexLocked:boolean}){const set=(k:keyof Fields,v:string)=>setFields({...fields,[k]:v});return <div className="form-grid ancestor-fields"><label className="wide">Name / registered name / identifying label *<Input value={fields.name} onChange={e=>set('name',e.target.value)} required maxLength={200}/></label><label>Sex<Select value={fields.sex} onValueChange={v=>set('sex',v)} disabled={sexLocked}><SelectTrigger aria-label="Ancestor sex"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Male">Male</SelectItem><SelectItem value="Female">Female</SelectItem></SelectContent></Select></label><label>Breed / description<Input value={fields.breed} onChange={e=>set('breed',e.target.value)} maxLength={200}/></label><label>Date of birth (if known)<Input type="date" value={fields.dob} onChange={e=>set('dob',e.target.value)}/></label><label>Birth year only (if known)<Input type="number" min={1900} max={new Date().getFullYear()} disabled={!!fields.dob} value={fields.birthYear} onChange={e=>set('birthYear',e.target.value)}/></label><label>Breeder / farm<Input value={fields.farm} onChange={e=>set('farm',e.target.value)} maxLength={200}/></label><label>Registry<Input value={fields.registry} onChange={e=>set('registry',e.target.value)} maxLength={200}/></label><label className="wide">Registration number / pedigree identifier<Input value={fields.registrationNumber} onChange={e=>set('registrationNumber',e.target.value)} maxLength={200}/></label><label className="wide">Notes / pedigree source<Textarea value={fields.notes} onChange={e=>set('notes',e.target.value)} maxLength={2000} placeholder="For example: details from the registration certificate"/></label></div>}
export default function PedigreeWorkspace({animals,species,year,rootId,onRootChange,onReload,onOpenAnimal}:{animals:Animal[];species:string;year:string;rootId:string;onRootChange:(id:string)=>void;onReload:()=>Promise<void>;onOpenAnimal:(a:Animal)=>void}){
 const [editor,setEditor]=useState<Editor|null>(null),[mode,setMode]=useState('existing'),[parentId,setParentId]=useState('unknown'),[fields,setFields]=useState<Fields|null>(null),[reason,setReason]=useState('Pedigree information entered'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[op,setOp]=useState(''),[search,setSearch]=useState(''),[expanded,setExpanded]=useState<Set<string>>(new Set());
 const map=useMemo(()=>new Map(animals.map(a=>[a.id,a])),[animals]);const root=map.get(rootId);const readonly=year==='all';
 const choices=animals.filter(a=>a.species===species&&!a.archivedAt&&!a.pedigreeOnly);const references=animals.filter(a=>a.species===species&&!a.archivedAt&&a.pedigreeOnly);
 const editable=(a:Animal)=>!readonly&&!a.archivedAt&&(!!a.pedigreeOnly||a.firstYear<=Number(year));
 function start(e:Editor){setEditor(e);setError('');setSearch('');setOp(crypto.randomUUID());setReason('Pedigree information entered');const child=map.get(e.childId||'');const id=child&&e.role?child[e.role]:null;setMode(id?'existing':e.kind==='link'?'new':'existing');setParentId(id||'unknown');setFields(e.kind==='details'?fieldsFor(map.get(e.animalId!)!):fresh(e.role==='dam'?'Female':'Male'))}
 async function post(action:string,data:unknown){const r=await fetch('/api/flock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,year,data})});const result:any=await r.json();if(!r.ok)throw Error(result.error||'Unable to save.');return result}
 async function save(e:React.FormEvent){e.preventDefault();if(!editor||!fields)return;setBusy(true);setError('');let createdId='';try{
  const details={...fields,birthYear:fields.birthYear?Number(fields.birthYear):null,info:{farm:fields.farm,registry:fields.registry,registrationNumber:fields.registrationNumber,notes:fields.notes}};
  if(editor.kind==='details'){const a=map.get(editor.animalId!)!;await post('ancestor-edit',{...details,id:a.id,version:a.version,operationId:op,reason})}
  else if(editor.kind==='new'){await post('ancestor',{...details,species});createdId=fields.id;onRootChange(createdId)}
  else {
   const child=map.get(editor.childId!)!;let target=parentId==='unknown'?null:parentId;
   if(mode==='new'){await post('ancestor',{...details,sex:editor.role==='sire'?'Male':'Female',species:child.species});target=fields.id;createdId=fields.id;setMode('existing');setParentId(fields.id);await onReload()}
   await post('pedigree',{id:child.id,version:child.version,operationId:op,reason,sire:editor.role==='sire'?target:child.sire,dam:editor.role==='dam'?target:child.dam});
  }
  await onReload();setEditor(null);
 }catch(e){setError((createdId?'The ancestor record was saved, but the parent link needs review. ':'')+(e instanceof Error?e.message:'Unable to save.'));await onReload()}finally{setBusy(false)}}
 function toggle(path:string){setExpanded(s=>{const next=new Set(s);if(next.has(path))next.delete(path);else next.add(path);return next})}
 function branch(child:Animal,role:Role,path:string,level:number):React.ReactNode{
  const a=map.get(child[role]||'');const title=role==='sire'?'Sire':'Dam';const showChildren=level<3||expanded.has(path);let info:any={};try{info=JSON.parse(a?.pedigreeInfo||'{}')}catch{}
  return <div className={'ped-branch '+role} key={path}><div className={'ped-card '+(!a?'unknown':'')}><div className="ped-card-head"><span>{title} · generation {level}</span>{a&&<span className="ped-kind">{a.archivedAt?'Deleted record':a.pedigreeOnly?'Not owned':'Flock record'}</span>}</div>{a?<><h3>{label(a)}</h3><p>{a.breed||'Breed not entered'}{a.dob?' · '+a.dob:a.birthYear?' · born '+a.birthYear:''}</p>{info.registrationNumber&&<p>{info.registry||'Registration'}: {info.registrationNumber}</p>}{info.farm&&<p>{info.farm}</p>}<div className="ped-buttons"><Button variant="outline" size="sm" onClick={()=>onRootChange(a.id)}>Focus pedigree</Button>{a.pedigreeOnly?<Button variant="ghost" size="sm" disabled={!editable(a)} onClick={()=>start({kind:'details',animalId:a.id})}>Edit details</Button>:<Button variant="ghost" size="sm" onClick={()=>onOpenAnimal(a)}>Open record</Button>}<Button variant="ghost" size="sm" disabled={!editable(child)} onClick={()=>start({kind:'link',childId:child.id,role})}>Change {role}</Button></div></>:<><h3>Unknown {role}</h3><Button variant="outline" size="sm" disabled={!editable(child)} onClick={()=>start({kind:'link',childId:child.id,role})}>Add {role}</Button></>}</div>{a&&(showChildren?<div className="ped-descendants">{branch(a,'sire',path+'.sire',level+1)}{branch(a,'dam',path+'.dam',level+1)}</div>:<Button variant="ghost" className="expand-parents" onClick={()=>toggle(path)}>Show / enter earlier generations</Button>)}</div>
 }
 const child=editor?.childId?map.get(editor.childId):null;
 const eligible=editor?.role&&child?animals.filter(a=>a.id!==child.id&&a.species===species&&a.sex===(editor.role==='sire'?'Male':'Female')&&[label(a),a.eid,a.pedigreeInfo].some(v=>v?.toLowerCase().includes(search.toLowerCase()))):[];
 return <section className="panel pedigree-panel"><div className="panel-top"><div><p className="eyebrow">BOTH SIDES OF THE FAMILY</p><h2>Pedigree & ancestor records</h2></div><Button variant="outline" disabled={readonly} onClick={()=>start({kind:'new'})}>Add unowned ancestor</Button></div><p className="ped-intro">Parents, grandparents and earlier generations can be entered whether or not you own them. Reuse the same ancestor record wherever it appears in a pedigree.</p><div className="ped-root-picker"><label>Choose a flock animal<Select value={choices.some(a=>a.id===rootId)?rootId:'none'} onValueChange={v=>{onRootChange(v==='none'?'':v);setExpanded(new Set())}}><SelectTrigger aria-label="Pedigree animal"><SelectValue placeholder="Choose animal"/></SelectTrigger><SelectContent><SelectItem value="none">Choose a flock animal</SelectItem>{choices.map(a=><SelectItem key={a.id} value={a.id}>{label(a)}{a.pedigreeOnly?' · not owned':''}</SelectItem>)}</SelectContent></Select></label></div>
 {root&&root.species===species?<><div className="ped-root"><span className="pill">{root.pedigreeOnly?'Pedigree only · not owned':'Flock animal'}</span><h2>{label(root)}</h2><p>{root.breed||'Breed not entered'} · {root.dob||root.birthYear||'Birth date unknown'}</p>{root.pedigreeOnly?<Button variant="outline" disabled={!editable(root)} onClick={()=>start({kind:'details',animalId:root.id})}>Edit ancestor details</Button>:<Button variant="outline" onClick={()=>onOpenAnimal(root)}>Open animal record</Button>}</div><div className="ped-lines"><section><h3 className="line-title">Paternal line</h3>{branch(root,'sire','sire',1)}</section><section><h3 className="line-title">Maternal line</h3>{branch(root,'dam','dam',1)}</section></div></>:<div className="empty">Choose an animal to start its pedigree.<small>Add your flock animal in Animals, or add an unowned ancestor above.</small></div>}
 <details className="ancestor-library"><summary>Unowned ancestor records ({references.length})</summary>{references.length?references.map(a=><div className="ancestor-list-row" key={a.id}><div><b>{label(a)}</b><p>{a.sex} · {a.breed||'Breed not entered'}</p></div><div className="ped-buttons"><Button variant="outline" size="sm" onClick={()=>onRootChange(a.id)}>View pedigree</Button><Button variant="ghost" size="sm" disabled={!editable(a)} onClick={()=>start({kind:'details',animalId:a.id})}>Edit details</Button><Button variant="ghost" size="sm" onClick={()=>onOpenAnimal(a)}>Open record</Button></div></div>):<p>No unowned ancestors recorded yet.</p>}</details><p className="hint">Three ancestor generations are shown initially. Expand a branch for earlier generations, or focus on any ancestor. Unknown parentage stays unknown and makes COI an estimate based on the recorded pedigree.</p>
 <Dialog open={!!editor} onOpenChange={open=>{if(!busy&&!open)setEditor(null)}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{editor?.kind==='link'?`Set ${editor.role} for ${child?label(child):'animal'}`:editor?.kind==='details'?'Edit ancestor information':'Add an unowned ancestor'}</DialogTitle><DialogDescription>{editor?.kind==='link'?'Choose an existing record or enter an ancestor you do not own.':'Pedigree-only records do not count as flock animals. Birth details and registration information are optional.'}</DialogDescription></DialogHeader><form onSubmit={save}>{editor?.kind==='link'&&<Tabs value={mode} onValueChange={setMode}><TabsList><TabsTrigger value="existing">Use existing record</TabsTrigger><TabsTrigger value="new">Enter unowned ancestor</TabsTrigger></TabsList></Tabs>}
 {editor?.kind==='link'&&mode==='existing'?<div className="my-4"><label>Find a parent<Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or registration information"/></label><Select value={parentId} onValueChange={setParentId}><SelectTrigger aria-label="Choose parent"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unknown">Unknown / clear parent link</SelectItem>{eligible.map(a=><SelectItem key={a.id} value={a.id}>{label(a)}{a.pedigreeOnly?' · not owned':''}{a.archivedAt?' · deleted record':''}</SelectItem>)}</SelectContent></Select><p className="hint">Choose Enter unowned ancestor if the parent is not listed. Select Unknown to clear a mistaken parent link.</p></div>:fields&&<AncestorFields fields={fields} setFields={setFields} sexLocked={editor?.kind!=='new'}/>}
 {editor?.kind!=='new'&&<label className="block mt-4">Reason for change *<Input value={reason} onChange={e=>setReason(e.target.value)} required maxLength={500}/></label>}{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setEditor(null)}>Cancel</Button><Button type="submit" disabled={busy}>{busy?'Saving…':editor?.kind==='link'?'Save parent':editor?.kind==='details'?'Save details':'Save ancestor'}</Button></div></form></DialogContent></Dialog></section>
}
