"use client";
import AnimalPicker from './animal-picker';
import {useState} from 'react';
import {type BreedingGroup,type PregnancyCheck} from '@/lib/breeding';
import {type Animal,label} from '@/lib/livestock';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function PregnancyChecks({group,animals,year,onSaved}:{group:BreedingGroup;animals:Animal[];year:string;onSaved:()=>Promise<void>}){
 const [draft,setDraft]=useState<PregnancyCheck|null>(null),[operation,setOperation]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const name=(id:string)=>{const a=animals.find(a=>a.id===id);return a?label(a):id};
 const checks=[...(group.pregnancyChecks||[])].sort((a,b)=>b.date.localeCompare(a.date));
 const latest=group.eweIds.map(id=>checks.find(c=>c.eweId===id));
 function open(c?:PregnancyCheck){setDraft(c?{...c}:{id:crypto.randomUUID(),eweId:'',date:'',result:'Inconclusive',method:'Ultrasound',fetuses:null,notes:''});setOperation(crypto.randomUUID());setError('')}
 async function save(){if(!draft)return;setBusy(true);setError('');try{const list=group.pregnancyChecks||[],exists=list.some(c=>c.id===draft.id);const r=await fetch('/api/flock/breeding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({year:group.year,operationId:operation,reason:exists?'Pregnancy check corrected':'Pregnancy check recorded',data:{...group,pregnancyChecks:exists?list.map(c=>c.id===draft.id?draft:c):[...list,draft]}})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setDraft(null);await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const readonly=year==='all';
 return <div className="border-t mt-3 pt-3"><h4>Pregnancy checks</h4><p>{latest.filter(c=>c?.result==='Pregnant').length} pregnant · {latest.filter(c=>c?.result==='Open').length} open · {latest.filter(c=>c?.result==='Inconclusive').length} inconclusive · {latest.filter(c=>!c||c.result==='Not checked').length} not checked</p><Button variant="outline" disabled={readonly} onClick={()=>open()}>Record pregnancy check</Button><details className="my-2"><summary>Check records ({checks.length})</summary>{checks.map(c=><div key={c.id} className="border-b py-2"><strong>{name(c.eweId)}</strong> · {c.date} · {c.result} · {c.method}{c.fetuses!==null?' · '+c.fetuses+' fetuses':''}<p>{c.notes}</p><Button variant="outline" size="sm" disabled={readonly} onClick={()=>open(c)}>Correct check</Button></div>)}</details><Dialog open={!!draft} onOpenChange={v=>{if(!busy&&!v)setDraft(null)}}><DialogContent><DialogHeader><DialogTitle>Pregnancy check</DialogTitle><DialogDescription>Record the observed result. This does not assign paternity or create offspring. Corrections retain the previous values in group history.</DialogDescription></DialogHeader>{draft&&<form onSubmit={e=>{e.preventDefault();save()}} className="grid gap-3"><label>Animal<AnimalPicker date={draft.date} required className="border rounded p-2 w-full" value={draft.eweId} onChange={e=>setDraft({...draft,eweId:e.target.value})} animals={animals.filter(a=>group.eweIds.includes(a.id))} placeholder="Choose female"/></label><label>Check date<input required type="date" className="border rounded p-2 w-full" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Result<select className="border rounded p-2 w-full" value={draft.result} onChange={e=>setDraft({...draft,result:e.target.value,fetuses:e.target.value==='Pregnant'?draft.fetuses:null})}>{['Pregnant','Open','Inconclusive','Not checked'].map(v=><option key={v}>{v}</option>)}</select></label><label>Method<select className="border rounded p-2 w-full" value={draft.method} onChange={e=>setDraft({...draft,method:e.target.value})}>{['Ultrasound','Blood test','Veterinary examination','Observation','Other'].map(v=><option key={v}>{v}</option>)}</select></label>{draft.result==='Pregnant'&&<label>Fetus count (optional)<input type="number" min="1" max="10" className="border rounded p-2 w-full" value={draft.fetuses??''} onChange={e=>setDraft({...draft,fetuses:e.target.value?Number(e.target.value):null})}/></label>}<label>Notes<textarea className="border rounded p-2 w-full" maxLength={2000} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>{error&&<p role="alert" className="error">{error}</p>}<Button disabled={busy} type="submit">{busy?'Saving…':'Save check'}</Button></form>}</DialogContent></Dialog></div>
}
