"use client";
import {type FarmEvent,rationCost} from '@/lib/farm-events';
import {Button} from '@/components/ui/button';
type Ration=NonNullable<FarmEvent['ration']>;
const field='border rounded p-2 w-full';
export default function RationFields({value,onChange}:{value:Ration;onChange:(v:Ration)=>void}){
 const cost=rationCost(value),money=(n:number|null)=>n===null?'Unknown':'$'+n.toFixed(2);
 return <fieldset className="border rounded p-3"><legend>Ration version</legend><p>Record as-fed mix pounds; percentages are calculated from the mix. Create a new dated event for a new version. These estimates do not post expenses.</p><div className="form-grid"><label>Production stage<select className={field} value={value.stage||''} onChange={e=>onChange({...value,stage:e.target.value})}><option value="">Not specified</option>{['Maintenance','Breeding / flushing','Early gestation','Late gestation','Lactation','Market lambs','Replacement ewes','Replacement rams','Other'].map(v=><option key={v}>{v}</option>)}</select></label><label>Source / adviser / analysis reference<input className={field} value={value.source||''} onChange={e=>onChange({...value,source:e.target.value})}/></label></div>{value.ingredients.map((row,i)=><div className="form-grid border-b my-2" key={i}>{(['name','pounds','pricePerTon'] as const).map(k=><label key={k}>{{name:'Ingredient',pounds:'As-fed mix pounds',pricePerTon:'Price / 2,000-lb ton ($)'}[k]}<input className={field} type={k==='name'?'text':'number'} min="0" step="any" value={row[k]??''} onChange={e=>onChange({...value,ingredients:value.ingredients.map((x,n)=>n===i?{...x,[k]:k==='name'?e.target.value:k==='pricePerTon'&&e.target.value===''?null:Number(e.target.value)}:x)})}/></label>)}<p>{cost.pounds>0?(row.pounds/cost.pounds*100).toFixed(2)+'% of mix':'Enter mix pounds'}</p><Button variant="ghost" disabled={value.ingredients.length===1} onClick={()=>onChange({...value,ingredients:value.ingredients.filter((_,n)=>n!==i)})}>Remove ingredient</Button></div>)}<Button variant="outline" disabled={value.ingredients.length>=20} onClick={()=>onChange({...value,ingredients:[...value.ingredients,{name:'',pounds:0,pricePerTon:null}]})}>Add ingredient</Button><label>Planned lb/head/day (optional)<input className={field} type="number" min="0" step="any" value={value.feedingLb??''} onChange={e=>onChange({...value,feedingLb:e.target.value===''?null:Number(e.target.value)})}/></label><p>Mix: {cost.pounds} lb · {money(cost.perTon)}/ton · Daily estimate: {money(cost.perHeadDay)}/head</p><p>Leave unknown prices blank. Nutrient adequacy and automatic cost allocation are not calculated here. Attach the source sheet after saving.</p></fieldset>
}
