"use client";
import {useId,useState} from 'react';
import {type FarmEvent,rationCost} from '@/lib/farm-events';
import {balanceSheepRation,nutrientLabels,targetLabels,type Nutrient,type Target,type Requirement} from '@/lib/sheep-ration';
import {sheepFeeds,sheepRequirements} from '@/lib/sheep-ration-data';
import {Button} from '@/components/ui/button';
type Ration=NonNullable<FarmEvent['ration']>;
const field='border rounded p-2 w-full';
const num=(v:string)=>v===''?null:Number(v);
const fmt=(v:number|null|undefined)=>v==null?'Unknown':v.toLocaleString(undefined,{maximumFractionDigits:3});
const money=(v:number|null)=>v===null?'Unknown':'$'+v.toFixed(2);
export function RationResults({value}:{value:Ration}){
 const b=balanceSheepRation(value),req=value.nutrition?.requirement,complete=value.nutrition?.dietScope==='complete',cost=rationCost(value);
 return <div className="ration-results"><h3>Nutrient check</h3><p>{req?.name||'Choose a sheep requirement profile to compare intake.'} · {complete?'Whole diet':'Supplement only'}</p>
 <div className="ration-metrics"><span>As-fed intake<strong>{fmt(value.feedingLb)} lb/head/day</strong></span><span>Estimated intake from target DMI<strong>{fmt(b.estimatedAsFed)} lb/head/day</strong></span><span>Feed cost<strong>{money(cost.perHeadDay)}/head/day</strong></span></div>
 <div className="ration-table-scroll" tabIndex={0} aria-label="Nutrient comparison"><table className="ration-sheet"><thead><tr><th>Nutrient</th><th>Provided</th><th>Target</th><th>Difference</th><th>Review</th></tr></thead><tbody>{(Object.keys(targetLabels) as Target[]).map(k=>{const actual=b.daily[k],target=req?.targets[k],known=actual!==null&&target!=null;return <tr key={k}><th>{targetLabels[k]}</th><td>{fmt(actual)}</td><td>{fmt(target)}</td><td>{known?fmt(actual-target):'—'}</td><td>{!complete?'Partial diet':!known?'Unknown':k==='dmi'?'Intake reference':actual+1e-9<target?'Below target':'Target met*'}</td></tr>})}</tbody></table></div>
 <p>Ca:P {b.caP===null?'Unknown':fmt(b.caP)+':1'} · NDF {fmt(b.concentrations.ndf)}% as-fed · Copper {fmt(b.copperPpmDM)} ppm DM</p>
 <p className="hint">*Meeting a minimum does not establish a safe maximum or prove a complete diet. Vitamins, iodine, effective fiber and water contributions are not fully evaluated. Estimates require feed-test and sheep-nutrition review.</p>
 {b.warnings.map(w=><p className="caution" key={w}>{w}</p>)}
 <details><summary>Analysis gaps and calculation sources</summary><ul>{(Object.keys(nutrientLabels) as Nutrient[]).filter(k=>b.missing[k].length).map(k=><li key={k}>{nutrientLabels[k]}: {b.missing[k].join(', ')}</li>)}</ul><p>Ohio State Meat Sheep Balancer v6, Dr. Benjamin Wenner; database updates by Corienne Gammariello. Feed values are converted from dry matter to as-fed before calculating daily intake. The workbook uses 0.454 kg/lb. Workbook copper review limit: {fmt(b.copperLimit)} mg/day; the additional dry-matter copper check also accounts for wet diets.</p><p>{req?.source}</p></details>
 </div>
}
export default function RationFields({value,onChange,species='Sheep',events=[],headCount=0}:{value:Ration;onChange:(v:Ration)=>void;species?:string;events?:FarmEvent[];headCount?:number}){
 const [panel,setPanel]=useState<'mix'|'analysis'|'results'>('mix'),[search,setSearch]=useState('');const listId=useId();
 const cost=rationCost(value),sheep=species==='Sheep',nutrition=value.nutrition||{model:'osu-v6-1' as const,dietScope:'supplement' as const};
 const setNutrition=(v:Partial<NonNullable<Ration['nutrition']>>)=>onChange({...value,nutrition:{...nutrition,...v}});
 const update=(i:number,v:Partial<Ration['ingredients'][number]>)=>onChange({...value,ingredients:value.ingredients.map((r,n)=>n===i?{...r,...v}:r)});
 const setAnalysis=(i:number,key:Nutrient,v:number|null)=>{const r=value.ingredients[i];update(i,{analysis:{...r.analysis,source:r.analysis?.source||'User-entered analysis — add laboratory/product reference',nutrients:{...r.analysis?.nutrients,[key]:v}}})};
 const savedFeeds=events.filter(e=>e.species==='Sheep'&&e.ration&&!e.voided).flatMap(e=>e.ration!.ingredients.filter(i=>i.analysis).map((i,n)=>({id:'saved:'+e.id+':'+n,name:i.name,analysis:i.analysis!})));
 const chooseFeed=(i:number,id:string)=>{const saved=savedFeeds.find(f=>f.id===id);if(saved){update(i,{name:saved.name,analysis:structuredClone(saved.analysis)});return}const f=sheepFeeds.find(f=>f.id===id);if(f)update(i,{name:f.name,analysis:{id:f.id,source:f.source,nutrients:{...f.nutrients}}})};
 const planHeads=nutrition.headCount??headCount,days=nutrition.days,shrink=nutrition.shrinkPercent??0,totalPeriod=value.feedingLb&&planHeads>0&&days?value.feedingLb*planHeads*days/(1-shrink/100):null;
 return <fieldset className="ration-workspace"><legend>{sheep?'Sheep ration balancer':'Ration version'}</legend>
 <p>Enter the mix in pounds, then set the amount eaten per head each day. Plans do not post expenses.</p>
 <div className="ration-toolbar"><div role="tablist" aria-label="Ration worksheet">{(['mix','analysis','results'] as const).filter(k=>sheep||k==='mix').map(k=><Button key={k} role="tab" aria-selected={panel===k} variant={panel===k?'default':'outline'} onClick={()=>setPanel(k)}>{k==='mix'?'1 · Mix & feeding':k==='analysis'?'2 · Feed analysis':'3 · Nutrient check'}</Button>)}</div></div>
 {panel==='mix'&&<><div className="form-grid"><label>Production stage<select className={field} value={value.stage||''} onChange={e=>onChange({...value,stage:e.target.value})}><option value="">Not specified</option>{['Maintenance','Breeding / flushing','Early gestation','Late gestation','Lactation','Market lambs','Replacement ewes','Replacement rams','Other'].map(v=><option key={v}>{v}</option>)}</select></label><label>Source / adviser / analysis reference<input className={field} value={value.source||''} onChange={e=>onChange({...value,source:e.target.value})}/></label></div>
 {sheep&&<div className="form-grid"><label>Diet coverage<select className={field} value={nutrition.dietScope} onChange={e=>setNutrition({dietScope:e.target.value as 'complete'|'supplement'})}><option value="supplement">Supplement only — forage not included</option><option value="complete">Whole diet — includes forage and minerals</option></select></label><label>Sheep class and weight<select className={field} value={nutrition.requirement?.id||''} onChange={e=>{const r=sheepRequirements.find(r=>r.id===e.target.value);setNutrition({requirement:r?structuredClone(r):e.target.value==='custom'?{id:'custom',name:'Custom sheep requirements',source:'',targets:{}}:undefined})}}><option value="">Choose a requirement profile</option>{sheepRequirements.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}<option value="custom">Custom sheep profile / adviser targets</option></select></label></div>}
 <div className="ration-table-scroll" tabIndex={0} aria-label="Ration ingredients"><table className="ration-sheet"><thead><tr><th>#</th><th>Ingredient{sheep?' / library':''}</th><th>Mix lb (as-fed)</th><th>Mix %</th><th>$/US ton</th><th>lb/head/day</th><th></th></tr></thead><tbody>{value.ingredients.map((row,i)=><tr key={i}><td>{i+1}</td><td><input aria-label={`Ingredient ${i+1}`} className={field} value={row.name} onChange={e=>update(i,{name:e.target.value})}/>{sheep&&<select aria-label={`Feed library ${i+1}`} className={field} value="" onChange={e=>chooseFeed(i,e.target.value)}><option value="">Load book / saved analysis…</option>{savedFeeds.length>0&&<optgroup label="Saved ration analyses">{savedFeeds.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</optgroup>}<optgroup label="Ohio State book values">{sheepFeeds.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</optgroup></select>}</td><td><input aria-label={`Mix pounds ${i+1}`} className={field} type="number" min="0" step="any" value={row.pounds||''} onChange={e=>update(i,{pounds:Number(e.target.value)})}/></td><td>{cost.pounds?fmt(row.pounds/cost.pounds*100):'—'}</td><td><input aria-label={`Price per ton ${i+1}`} className={field} type="number" min="0" step="any" value={row.pricePerTon??''} onChange={e=>update(i,{pricePerTon:num(e.target.value)})}/></td><td>{cost.pounds&&value.feedingLb?fmt(row.pounds/cost.pounds*value.feedingLb):'—'}</td><td><Button variant="ghost" aria-label={`Remove ingredient ${i+1}`} disabled={value.ingredients.length===1} onClick={()=>onChange({...value,ingredients:value.ingredients.filter((_,n)=>n!==i)})}>Remove</Button></td></tr>)}</tbody></table></div>
 <Button variant="outline" disabled={value.ingredients.length>=20} onClick={()=>onChange({...value,ingredients:[...value.ingredients,{name:'',pounds:0,pricePerTon:null}]})}>Add ingredient</Button>
 <div className="form-grid"><label>As-fed lb/head/day<input className={field} type="number" min="0" step="any" value={value.feedingLb??''} onChange={e=>onChange({...value,feedingLb:num(e.target.value)})}/></label>{sheep&&<><label>Planning head count<input className={field} type="number" min="1" step="1" value={nutrition.headCount??(headCount||'')} onChange={e=>setNutrition({headCount:num(e.target.value)})}/></label><label>Feeding days<input className={field} type="number" min="1" step="1" value={days??''} onChange={e=>setNutrition({days:num(e.target.value)})}/></label><label>Storage shrink %<input className={field} type="number" min="0" max="99.9" step="any" value={nutrition.shrinkPercent??''} onChange={e=>setNutrition({shrinkPercent:num(e.target.value)})}/></label></>}</div>
 <div className="ration-metrics"><span>Mix cost<strong>{money(cost.perTon)}/US ton</strong></span><span>Daily cost<strong>{money(cost.perHeadDay)}/head</strong></span>{sheep&&<span>Period purchases incl. shrink<strong>{fmt(totalPeriod===null?null:totalPeriod/2000)} tons · {money(totalPeriod===null||cost.perTon===null?null:totalPeriod/2000*cost.perTon)}</strong></span>}</div>
 {sheep&&<p className="hint">Group-period planning follows the layout in your Iowa State ration sheets. Shrink is the fraction purchased but lost; purchase quantity = consumed quantity ÷ (1 − shrink). No automatic growth/intake scaling. Actual bills use dated membership and animal overrides in Feed allocation.</p>}
 </>}
 {panel==='analysis'&&sheep&&<><p>Enter laboratory values on a dry-matter basis. Keep unknown cells blank. An explicit 0 means measured/confirmed zero.</p><label>Find a nutrient<input className={field} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Protein, copper, calcium…"/></label><div className="ration-table-scroll" tabIndex={0} aria-label="Feed analysis spreadsheet"><table className="ration-sheet"><thead><tr><th>Nutrient / unit</th>{value.ingredients.map((r,i)=><th key={i}>{r.name||`Ingredient ${i+1}`}</th>)}</tr></thead><tbody>{(Object.keys(nutrientLabels) as Nutrient[]).filter(k=>nutrientLabels[k].toLowerCase().includes(search.toLowerCase())).map(k=><tr key={k}><th>{nutrientLabels[k]}</th>{value.ingredients.map((r,i)=><td key={i}><input aria-label={`${r.name||`Ingredient ${i+1}`} ${nutrientLabels[k]}`} className={field} type="number" min="0" step="any" value={r.analysis?.nutrients[k]??''} onChange={e=>setAnalysis(i,k,num(e.target.value))}/></td>)}</tr>)}<tr><th>Analysis source / test date</th>{value.ingredients.map((r,i)=><td key={i}><input aria-label={`Analysis source ${i+1}`} className={field} value={r.analysis?.source||''} onChange={e=>update(i,{analysis:{...r.analysis,source:e.target.value,nutrients:r.analysis?.nutrients||{}}})}/></td>)}</tr></tbody></table></div>
 <details><summary>Requirement targets / custom profile</summary><p>Use adviser-supplied targets for classes outside the workbook, including maintenance, lactation, small sheep and replacement rams. Editing a book target creates a custom profile.</p><div className="form-grid">{(['name','source'] as const).map(k=><label key={k}>{k==='name'?'Profile name':'Requirement source'}<input className={field} value={nutrition.requirement?.[k]||''} onChange={e=>setNutrition({requirement:{...nutrition.requirement,id:'custom',name:nutrition.requirement?.name||'Custom sheep requirements',source:nutrition.requirement?.source||'',targets:nutrition.requirement?.targets||{},[k]:e.target.value} as Requirement})}/></label>)}{(Object.keys(targetLabels) as Target[]).map(k=><label key={k}>{targetLabels[k]}<input className={field} type="number" min="0" step="any" value={nutrition.requirement?.targets[k]??''} onChange={e=>setNutrition({requirement:{id:'custom',name:nutrition.requirement?.name||'Custom sheep requirements',source:nutrition.requirement?.source||'',targets:{...nutrition.requirement?.targets,[k]:num(e.target.value)}}})}/></label>)}</div></details></>}
 {panel==='results'&&sheep&&<RationResults value={{...value,nutrition}}/>}
 {sheep&&<details><summary>Feeding guidance & references</summary><p>Start with forage analysis, choose the sheep class and weight, balance the whole diet, then compare cost. Separate market lambs from retained breeding replacements; use condition and performance to review group feeding.</p><ul><li><a href="https://extension.sdstate.edu/nutritional-considerations-flocks-during-breeding-season" target="_blank" rel="noreferrer">SDSU: breeding-season nutrition</a> — condition-aware feeding and separate needs for growing replacements.</li><li><a href="https://extension.sdstate.edu/mineral-considerations-sheep" target="_blank" rel="noreferrer">SDSU: sheep minerals</a> — consider forage tests, actual consumption and mineral interactions.</li><li>Iowa State / Garland Dahlke ration sheets supplied with this project: group sizes, stage-specific periods, as-fed quantities, shrink and separate mineral worksheets. Their example diets are not installed as your feeding instructions.</li><li>Ohio State Meat Sheep Balancer v6: nutrient calculations and reference profiles. The enterprise budget supplies cost structure, not nutrition requirements.</li></ul><p>Attach your forage report, mineral tag or adviser sheet after saving. Start a new dated ration version when the diet changes; use Edit for corrections.</p></details>}
 </fieldset>
}
