"use client";
import BackupVault from './backup-vault';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
export default function RecoveryWorkspace({onSaved}:{onSaved:()=>Promise<void>}){
 const [scope,setScope]=useState<'records'|'media'>('records');
 const [backup,setBackup]=useState<any>(null),[files,setFiles]=useState<Map<string,Uint8Array>>(new Map()),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[safety,setSafety]=useState<any[]>([]);
 async function loadSafety(){try{const r=await fetch('/api/flock/backup/restore'),d:any=await r.json();if(!r.ok)throw Error(d.error);setSafety(d.backups);if(d.more)setNotice('Showing the first 100 safety copies.')}catch(e){setError((e as Error).message)}}
 async function inspect(file:File){setBusy(true);setError('');setNotice('');setBackup(null);setPreview(null);setFiles(new Map());try{
  if(file.size>100*1024*1024)throw Error('This restore screen supports archives up to 100 MB.');
  const bytes=new Uint8Array(await file.arrayBuffer()),members=new Map<string,Uint8Array>();let data:any;
  if(file.name.toLowerCase().endsWith('.json'))data=JSON.parse(new TextDecoder().decode(bytes));else{
   let offset=0;while(offset+512<=bytes.length){const header=bytes.slice(offset,offset+512);if(header.every(v=>v===0))break;const text=(start:number,length:number)=>new TextDecoder().decode(header.slice(start,start+length)).split('\0')[0];const name=text(0,100),size=parseInt(text(124,12).trim(),8),checksum=parseInt(text(148,8).trim(),8);header.fill(32,148,156);if(header.reduce((n,v)=>n+v,0)!==checksum||!Number.isSafeInteger(size)||size<0||offset+512+size>bytes.length||members.has(name)||!['0',''].includes(text(156,1)))throw Error('Invalid or incomplete archive.');members.set(name,bytes.slice(offset+512,offset+512+size));offset+=512+Math.ceil(size/512)*512;}
   if(!members.has('records.json')||!members.has('checksums.json'))throw Error('Choose a full backup created by this application.');
   const checksums=JSON.parse(new TextDecoder().decode(members.get('checksums.json')));
   for(const [name,content] of members){if(name==='checksums.json')continue;const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(content)))).map(v=>v.toString(16).padStart(2,'0')).join('');if(checksums[name]!==hash)throw Error('Backup checksum failed: '+name);}
   data=JSON.parse(new TextDecoder().decode(members.get('records.json')));for(const f of data.files||[])if(!/^(animal-files|event-files)\/[0-9a-f-]{36}\/[0-9a-f-]{36}$/i.test(f.key)||members.get(f.key)?.length!==f.size)throw Error('A backup media file is missing or incomplete.');
  }
  if(scope==='media'){if(!data.includesMediaBytes||!data.files?.length||!members.size)throw Error('Choose a full archive containing photos/documents for media-only recovery.');setBackup(data);setFiles(members);setPreview({counts:{},conflicts:[],conflictCount:0,stamp:''});return;}
  const response=await fetch('/api/flock/backup/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'preview',backup:data})}),result:any=await response.json();if(!response.ok)throw Error(result.error);setBackup(data);setFiles(members);setPreview(result);
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function restore(){setBusy(true);setError('');setNotice('');try{
  let result:any={restored:0};if(scope==='records'){const response=await fetch('/api/flock/backup/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'apply',backup,stamp:preview.stamp})});result=await response.json();if(!response.ok)throw Error(result.error);}
  setNotice(result.restored+' records restored. Checking media…');
  let count=0;for(const f of backup.files||[]){const content=files.get(f.key);if(!content)throw Error('Records restored, but media bytes were not provided. Use the full archive to recover photos.');const [folder,ownerId,fileId]=f.key.split('/'),body=new FormData();body.set(folder==='event-files'?'eventId':'animalId',ownerId);body.set('fileId',fileId);body.set('file',new Blob([content as BlobPart]),fileId);const r=await fetch('/api/flock/backup/media',{method:'POST',body}),d:any=await r.json();if(!r.ok)throw Error((scope==='media'?'Media recovery needs attention: ':'Records restored; media recovery needs attention: ')+d.error);count++;setNotice(result.restored+' records restored · '+count+' files checked');}
  setNotice('Restore finished: '+result.restored+' missing records added and '+count+' media files checked. Existing records were preserved.');setPreview(null);setBackup(null);await onSaved();
 }catch(e){setError((e as Error).message);await onSaved()}finally{setBusy(false)}}
 return <section className="panel"><h2>Backups and recovery</h2><div className="flex flex-wrap gap-4 my-4"><a className="underline" href="/api/flock/backup/full">Download full backup with photos</a><a className="underline" href="/api/flock/backup">Download records only</a></div><p>The full archive includes current and removed photo, registration and event documents, all records and change histories. Keep a copy outside this application.</p><div className="my-4"><Button variant="outline" onClick={loadSafety}>Show safety copies</Button>{safety.map(s=><p key={s.key}><a className="underline" href={'/api/flock/backup/restore?key='+encodeURIComponent(s.key)}>{new Date(s.createdAt).toLocaleString()} · {(s.size/1024).toFixed(1)} KB</a></p>)}</div><BackupVault/><h3 className="mt-6">Recover missing records or media</h3><p>Preview a backup first. This restores missing records and media, and makes a safety copy before adding records. Existing records that differ are reported as conflicts and are not replaced. Reverting newer edits and scheduled backups are not available in this screen.</p><label className="block my-3">Recovery scope<select className="border rounded p-2 w-full" value={scope} disabled={busy} onChange={e=>{setScope(e.target.value as 'records'|'media');setBackup(null);setPreview(null);setFiles(new Map());setError('');setNotice('')}}><option value="records">Missing records and media</option><option value="media">Missing media only — keep current records</option></select></label>{scope==='media'&&<p>Verify and recover photos/documents still referenced by current profiles or events. Existing files and records are preserved. Unrecognized or changed references need review.</p>}<label className="block my-3">Backup file (.tar or .json)<input key={scope} className="block" type="file" accept={scope==='media'?'.tar':'.tar,.json'} disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)inspect(file)}}/></label>{busy&&<p role="status">Working…</p>}{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}{preview&&<div className="border rounded p-4"><h3>Restore preview</h3><p>Backup created: {backup?.exportedAt?new Date(backup.exportedAt).toLocaleString():'Date not recorded'} · {scope==='media'?'Media only':'Missing records and media'}</p>{Object.entries(preview.counts).map(([table,count])=><p key={table}>{table.replaceAll('_',' ')}: {String(count)} missing records</p>)}<p>{backup?.files?.length||0} media files · {preview.conflictCount} conflicts</p>{preview.conflicts.map((v:string)=><p key={v}>{v}</p>)}<Button disabled={busy||preview.conflictCount>0} onClick={restore}>{scope==='media'?'Verify and recover missing media':'Restore missing records and media'}</Button></div>}</section>
}
