"use client";
import {useMemo,useState} from 'react';import {type Animal,label} from '@/lib/livestock';import {Button} from '@/components/ui/button';import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Result={id:string;title:string;detail:string;text:string;section:string;year:string;species:string;animal?:Animal};
export default function RecordSearch({animals,history,onAnimal,onNavigate}:{animals:Animal[];history:any[];onAnimal:(a:Animal)=>void;onNavigate:(section:string,year:string,species:string)=>void}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[rows,setRows]=useState<Result[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const animalText=useMemo(()=>{const map=new Map<string,string[]>();for(const h of history){const values=map.get(h.animalId)||[];values.push(h.before,h.after);map.set(h.animalId,values)}return new Map(animals.map(a=>[a.id,JSON.stringify(a)+' '+(map.get(a.id)||[]).join(' ')]))},[animals,history]);
 const labels:Record<string,string>={animals:'Animals',events:'Animal events',health:'Health & inventory',finance:'Finances',feed:'Feed & rations',genetics:'Genetic evaluations',management:'Management groups',breeding:'Breeding',lambing:'Lambing / kidding',settings:'Settings'};
 const animalName=(id:string)=>{const a=animals.find(a=>a.id===id);return a?label(a):'Unknown'};
 async function start(){setOpen(true);setBusy(true);setError('');setQuery('');const paths=['events','breeding','lambing','projects','contacts'];const results=await Promise.allSettled(paths.map(async path=>{const r=await fetch('/api/flock/'+path),d=await r.json() as any;if(!r.ok)throw Error(path+' unavailable');return d}));const found:Result[]=[];const failed:string[]=[];results.forEach((r,i)=>{if(r.status==='rejected'){failed.push(paths[i]);return}const d=r.value;
  for(const e of d.events||[])if(!e.voided){const section=['treatment','stock','condition','lab'].includes(e.kind)?'health':['expense','income','valuation','selection'].includes(e.kind)?'finance':['ration','growthplan'].includes(e.kind)?'feed':e.kind==='evaluation'?'genetics':e.kind==='management'?'management':'events';found.push({id:e.id,title:e.title,detail:e.date+' · '+e.kind+' · '+e.notes,text:JSON.stringify(e)+' '+e.animalIds.map(animalName).join(' '),section,year:e.date.slice(0,4),species:e.species})}
  for(const g of d.groups||[])if(!g.archivedAt)found.push({id:g.id,title:g.name,detail:g.year+' · '+g.state+' · '+g.notes,text:JSON.stringify(g)+' '+[g.ramId,...g.eweIds].map(animalName).join(' '),section:'breeding',year:String(g.year),species:g.species});
  for(const l of d.litters||[])if(!l.voided)found.push({id:l.id,title:'Litter · '+animalName(l.damId),detail:l.date+' · '+l.lambs.length+' offspring · '+l.notes,text:JSON.stringify(l)+' '+animalName(l.damId)+' '+animalName(l.sireId),section:'lambing',year:l.date.slice(0,4),species:l.species});
  for(const p of d.projects||[])found.push({id:p.id,title:p.name,detail:'Breeding project',text:JSON.stringify(p),section:'breeding',year:'',species:''});
  for(const c of d.contacts||[])if(!c.archived)found.push({id:c.id,title:c.name,detail:c.role+' · '+c.phone+' · '+c.email,text:JSON.stringify(c),section:'settings',year:'',species:''});
 });setRows(found);if(failed.length)setError('Partial results: could not load '+failed.join(', ')+'. Close and reopen search to retry.');setBusy(false)}
 const needle=query.trim().toLowerCase();const matches=needle.length<2?[]:[...animals.filter(a=>!a.pedigreeOnly&&!a.archivedAt).map(a=>({id:a.id,title:label(a),detail:a.species+' · '+a.breed+' · '+a.status,text:animalText.get(a.id)||'',section:'animals',year:'',species:a.species,animal:a})),...rows].filter(r=>(r.title+' '+r.text).toLowerCase().includes(needle));
 return <><Button variant="outline" onClick={start}>Search records</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-3xl max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Search records</DialogTitle><DialogDescription>Search across both species and all years. Deleted records and unowned ancestor profiles remain in their dedicated views.</DialogDescription></DialogHeader><input autoFocus aria-label="Search all records" className="border rounded p-2 w-full" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, tag, bill, product, group, date or contact"/>{busy&&<p>Loading searchable records…</p>}{error&&<p role="alert">{error}</p>}{needle.length>=2&&<p>{matches.length} matching records{matches.length>100?' · Showing the first 100; refine your search.':''}</p>}{matches.slice(0,100).map(r=><article className="border-b py-3" key={r.section+r.id}><h3>{r.title}</h3><p className="break-words">{r.detail}</p><Button variant="outline" onClick={()=>{setOpen(false);if(r.animal)onAnimal(r.animal);else onNavigate(r.section,r.year,r.species)}}>{r.animal?'Open profile':'Go to '+(labels[r.section]||r.section)+(r.year?' · '+r.year:'')}</Button></article>)}</DialogContent></Dialog></>
}
