"use client";
import {useEffect,useState} from 'react';
import {type ReportFilter,emptyReportFilter} from '@/lib/report-filters';
import {Button} from '@/components/ui/button';
export default function ReportFilters({value,onChange,species,year}:{value:ReportFilter;onChange:(f:ReportFilter)=>void;species:string;year:string}){
 const [presets,setPresets]=useState<any[]>([]),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/flock/report-presets'),d=await r.json() as any;if(!r.ok)throw Error(d.error);setPresets(d.presets);setError('')}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[]);
 async function save(){setBusy(true);try{const r=await fetch('/api/flock/report-presets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({year,operationId:crypto.randomUUID(),data:{id:crypto.randomUUID(),version:0,name,species,filter:value,archived:false}})}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setName('');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <fieldset className="border rounded p-3 my-3"><legend>Report filters</legend><div className="form-grid">{(['query','breed','birthYear'] as const).map(k=><label key={k}>{{query:'Animal search',breed:'Breed contains',birthYear:'Birth year'}[k]}<input className="border rounded p-2 w-full" value={value[k]} onChange={e=>onChange({...value,[k]:e.target.value})}/></label>)}{(['status','sex','sort'] as const).map(k=><label key={k}>{k}<select className="border rounded p-2 w-full" value={value[k]} onChange={e=>onChange({...value,[k]:e.target.value})}>{({status:['All','Active','Sold','Dead','Culled','Transferred'],sex:['All','Unknown','Female','Male','Castrated male'],sort:['Animal','Breed','Birth year']}[k]).map(v=><option key={v}>{v}</option>)}</select></label>)}</div><div className="flex flex-wrap gap-2 my-3"><Button variant="outline" onClick={()=>onChange({...emptyReportFilter})}>Clear filters</Button><select aria-label="Load saved report" className="border rounded p-2" value="" onChange={e=>{const p=presets.find(p=>p.id===e.target.value);if(p)onChange(p.filter)}}><option value="">Load saved filters…</option>{presets.filter(p=>p.species===species&&!p.archived).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input aria-label="Saved report name" className="border rounded p-2" value={name} onChange={e=>setName(e.target.value)} placeholder="Name these filters"/><Button disabled={busy||year==='all'||!name.trim()} onClick={save}>Save filter setup</Button></div><p>Filters apply to the animal report and its export. Saved setups use the currently selected species and year when loaded.</p>{error&&<p role="alert">{error}</p>}</fieldset>
}
