"use client";
import {useEffect,useState} from 'react';
const phases=[
 {name:'1 · Animal identity and lifetime records',time:'20–30 minutes',built:'Profiles, imports, tag retirement and swaps, EID, photos and past photos, registration papers, status/ownership history, pedigree and batch edits.',tests:['Compare imported names, tags, leading zeros and parents with the spreadsheet.','Correct a tag typo; separately retire/replace a lost tag; swap two selected tags and check colors.','Upload two photos and a registration paper, change the primary photo, then reopen the profile.','Check Active/Sold/Dead counts, unknown exit dates and both sides of a pedigree.'],remaining:'Broader batch and sorting refinements remain deferred; uncommon document layouts need review.'},
 {name:'2 · Breeding and projects',time:'20–25 minutes',built:'Planned and actual dates, dated ewe exposures, pregnancy checks, flexible groups, project targets, relationships, ram comparisons and group archive/restore.',tests:['Save a planned group without a date; later add actual exposure and retain the planned date.','Use one ram in multiple groups and check each female’s exposure period.','Set Composite 4 targets and inspect incomplete ancestry and relatedness warnings.','Check a group crossing December/January remains in its originating breeding year.'],remaining:'Incomplete pedigree cannot establish unrelatedness. Complex historical corrections need further work.'},
 {name:'3 · Lambing / kidding and rearing',time:'20–25 minutes',built:'Dedicated Lambing/Kidding section; offspring-first litter entry, linked live profiles and birth weights, stillborn outcomes, safe corrections/void/restore, fostering and weaning.',tests:['Record a litter with a live and stillborn offspring; confirm only the live offspring gets a flock profile.','Leave an uncertain sire unknown and confirm breed percentages are not invented.','Correct an eligible birth date and check the litter, profile and birth weight agree.','Record fostering and weaning; verify biological parents remain unchanged.'],remaining:'Cross-year birth corrections are available for eligible litters; outcome changes with later dependent records remain restricted.'},
 {name:'4 · Weights and performance',time:'15–20 minutes',built:'Lamb-first weighing, adult measurements, sessions/imports, actual ADG, parent/cohort reports and a separate sourced adjusted-weight calculator.',tests:['Enter a small lamb weighing session and verify dates, units and actual ADG.','Import a device/spreadsheet sample and review ambiguous or former identifiers.','Correct or void a measurement and verify history and totals.','Use an explicit adjustment factor/source and confirm actual scale weights stay unchanged.'],remaining:'Peer comparisons and saved calculation snapshots are available; representative device exports and broader normalized comparisons need review.'},
 {name:'5 · Health, feed and management',time:'20–30 minutes',built:'Multi-day protocols, individual dose states/amounts, inventory lots and review warnings, lab results, dated management membership, ration versions and growth budgets.',tests:['Schedule several doses, mark one animal skipped and another given, then check history and inventory.','Review duplicate/repeat and user-sourced dose warnings without blocking an intentional treatment.','Record a lab result and attach its document.','Enter a ration with an unknown ingredient price and confirm cost stays unknown.'],remaining:'Feed allocation, management flags and dashboard inventory-warning placement are open decisions. Nutrient-model integration remains incomplete.'},
 {name:'6 · Finances, reports and calendar',time:'20–25 minutes',built:'Animal/general expenses, payment-linked sales, explicit allocations, separate retained estimates, cash charts, report filters, contacts and calendar source links.',tests:['Enter a veterinary expense for one animal and a group bill; check each bill is counted once.','Record a sale payment and inspect the animal’s exit history.','Check retained estimates and retention decisions do not become cash income or status exits.','Save report filters, update/archive/restore a setup, and open a calendar record in its source year.'],remaining:'Recorded purchase basis and customizable dashboard cards are available; broader statements, exports and reconciliation remain.'},
 {name:'7 · Phone, settings and recovery',time:'20–30 minutes',built:'Responsive screens, install metadata, remembered species/year, custom fields, manual offline queue, standard exports, full media archives, retained manual backups and recovery previews.',tests:['Switch species/year, reload and confirm each species remembers its year.','Load records online, disconnect, save a test change and manually sync after reconnecting.','Check that a conflicting queued save is retained for review rather than overwriting newer data.','Download records and full backups; inspect recovery differences before applying anything in a test copy.'],remaining:'Full/species rollback and deliberate note/reminder conflict merging are available. Unattended scheduling and further phone/chute refinements remain. Media uploads require connection.'}
];
export default function ReviewGuide(){
 const [checked,setChecked]=useState<Record<string,boolean>>({});
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem('flock-review-checklist-v2')||'{}');if(v&&typeof v==='object'&&!Array.isArray(v))setChecked(v)}catch{}},[]);
 function toggle(key:string,value:boolean){const next={...checked,[key]:value};setChecked(next);try{localStorage.setItem('flock-review-checklist-v2',JSON.stringify(next))}catch{}}
 return <div className="my-5"><h3>Connected build and acceptance review</h3><p>The 37 requirement areas are grouped into seven phases below. Available screens are not a declaration that every requirement is complete. This checklist covers the connected workflows; remaining items are listed with each phase.</p><p>Suggested review: three sessions—identity/breeding/births, then weights/health/feed, then finances/recovery. Use test records for changes you do not want in farm history. Checkmarks are saved in this browser.</p>{phases.map((p,i)=><details className="my-3 rounded border p-3" key={p.name}><summary>{p.name} · {p.time}</summary><p className="my-2"><strong>Available:</strong> {p.built}</p>{p.tests.map((t,j)=><label className="flex gap-2 my-2" key={t}><input type="checkbox" checked={!!checked[i+'-'+j]} onChange={e=>toggle(i+'-'+j,e.target.checked)}/>{t}</label>)}<p className="hint"><strong>Remaining:</strong> {p.remaining}</p></details>)}<p>Keep feed allocation, watch flags/favorites and central inventory warnings open until their designs are agreed. Formula examples are not imported as actual farm records, and depreciation is excluded.</p></div>;
}
