"use client";
import {LayoutDashboard,CalendarDays,ChartNoAxesCombined,Tags,GitBranch,Dna,HeartHandshake,Baby,Scale,NotebookPen,Leaf,Fence,HeartPulse,Wallet,Settings,ArchiveRestore,Trash2,ListChecks,ChevronDown,Check,type LucideIcon} from 'lucide-react';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuGroup,DropdownMenuLabel,DropdownMenuItem} from '@/components/ui/dropdown-menu';
type Entry={id:string;name:string;detail:string;icon:LucideIcon};
export default function SectionMenu({value,onChange,species,deletedCount}:{value:string;onChange:(v:string)=>void;species:string;deletedCount:number}){
 const groups:{name:string;tone:string;items:Entry[]}[]=[
 {name:'Overview',tone:'sage',items:[{id:'dashboard',name:'Dashboard',detail:'Your flock at a glance',icon:LayoutDashboard},{id:'calendar',name:'Calendar',detail:'Upcoming work & dates',icon:CalendarDays},{id:'reports',name:'Reports',detail:'Performance & financial results',icon:ChartNoAxesCombined}]},
 {name:'Animals & breeding',tone:'blue',items:[{id:'animals',name:'Animals',detail:'Profiles, tags & photos',icon:Tags},{id:'pedigree',name:'Pedigree',detail:'Parents & generations',icon:GitBranch},{id:'genetics',name:'Genetic evaluations',detail:'Tests & recorded traits',icon:Dna},{id:'breeding',name:'Breeding',detail:'Groups, plans & exposures',icon:HeartHandshake},{id:'lambing',name:species==='Sheep'?'Lambing':'Kidding',detail:'Births & offspring records',icon:Baby},{id:'weights',name:'Weights & growth',detail:'Measurements & lamb progress',icon:Scale}]},
 {name:'Farm management',tone:'amber',items:[{id:'events',name:'Animal events',detail:'Notes, rearing & dated records',icon:NotebookPen},{id:'health',name:'Health & inventory',detail:'Treatments, tests & supplies',icon:HeartPulse},{id:'feed',name:'Feed & rations',detail:'Mixes & feeding budgets',icon:Leaf},{id:'management',name:'Management groups',detail:'Group membership over time',icon:Fence},{id:'finance',name:'Finances',detail:'Income, expenses & values',icon:Wallet}]},
 {name:'Tools & settings',tone:'slate',items:[{id:'settings',name:'Settings',detail:'Contacts & custom fields',icon:Settings},{id:'recovery',name:'Backups & recovery',detail:'Save, export & recover records',icon:ArchiveRestore},{id:'deleted',name:'Deleted animals',detail:`${deletedCount} records available to review`,icon:Trash2},{id:'plan',name:'Build plan',detail:'Progress & testing checklist',icon:ListChecks}]}];
 const current=groups.flatMap(g=>g.items).find(i=>i.id===value)||groups[0].items[0],Icon=current.icon;
 return <nav className="workspace-navigation" aria-label="Workspace navigation"><DropdownMenu><DropdownMenuTrigger className="workspace-trigger" aria-label={`Section: ${current.name}`}><span className="workspace-current-icon"><Icon size={24}/></span><span className="workspace-current-copy"><small>WORKSPACE</small><strong>{current.name}</strong><span>{current.detail}</span></span><span className="workspace-switch">Change section<ChevronDown size={18}/></span></DropdownMenuTrigger><DropdownMenuContent align="start" sideOffset={10} className="workspace-menu"><div className="workspace-menu-heading"><strong>Where would you like to go?</strong><span>Choose a workspace</span></div><div className="workspace-menu-grid">{groups.map(g=><DropdownMenuGroup key={g.name} className={`workspace-menu-group tone-${g.tone}`}><DropdownMenuLabel className="workspace-group-label">{g.name}</DropdownMenuLabel>{g.items.map(item=>{const ItemIcon=item.icon,selected=item.id===value;return <DropdownMenuItem key={item.id} textValue={item.name} aria-current={selected?'page':undefined} className={`workspace-menu-item ${selected?'is-current':''}`} onSelect={()=>onChange(item.id)}><span className="workspace-item-icon"><ItemIcon size={20}/></span><span className="workspace-item-copy"><strong>{item.name}</strong><small>{item.detail}</small></span>{selected&&<Check className="workspace-item-check" size={17}/>}</DropdownMenuItem>})}</DropdownMenuGroup>)}</div></DropdownMenuContent></DropdownMenu></nav>;
}
