"use client";
import {GroupFilter,useGroups} from './group-context';
import {groupMembers} from '@/lib/management-groups';
import EntrySheet from './entry-sheet';
import WeightSpreadsheet from './weight-spreadsheet';
import {useState} from 'react';
import {type Animal,type Weight,label,displayId} from '@/lib/livestock';
import {validateWeight} from '@/lib/weight-records';
import {statusAt} from '@/lib/animal-status';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Entry={id:string;animalId:string;originalValue:number;unit:string};
export default function WeighingSessions({animals,weights,history,year,editable,onSaved}:{animals:Animal[];weights:Weight[];history:any[];year:string;editable:boolean;onSaved:()=>Promise<void>}){
 const {events:membershipEvents,error:membershipError,loading:membershipLoading}=useGroups();
 const [group,setGroup]=useState('');
 const [open,setOpen]=useState(false),[date,setDate]=useState(''),[name,setName]=useState(''),[query,setQuery]=useState(''),[unit,setUnit]=useState('lb'),[values,setValues]=useState<Record<string,{value:string;unit:string}>>({}),[review,setReview]=useState<Entry[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[batchId,setBatchId]=useState(''),[operationId,setOperationId]=useState('');
 const [selected,setSelected]=useState(''),[mode,setMode]=useState(''),[reason,setReason]=useState(''),[changeId,setChangeId]=useState('');
 const batches=Array.from(new Set(weights.filter(w=>w.batchId&&(year==='all'||w.date.startsWith(year))&&animals.some(a=>a.id===w.animalId)).map(w=>w.batchId!)));
 const session=weights.filter(w=>w.batchId===selected);const candidates=animals.filter(a=>!a.pedigreeOnly&&!a.archivedAt);
 function exportSession(){const quote=(v:unknown)=>{const s=String(v??'');return '"'+(/^[=+@\-\t\r]/.test(s)?"'":'')+s.replaceAll('"','""')+'"'};const data=[['Animal ID','Animal','Date','Weight','Unit','Session','Status'],...session.map(w=>[w.animalId,label(animals.find(a=>a.id===w.animalId)!),w.date,w.originalValue,w.unit,w.session,w.voided?'Voided':'Valid'])].map(row=>row.map(quote).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='weighing-session.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function start(){if(!batchId){setBatchId(crypto.randomUUID());setOperationId(crypto.randomUUID());setDate(year===String(new Date().getFullYear())?new Date().toLocaleDateString('en-CA'):year+'-01-01');setName('Weighing session');}setOpen(true);setError('');setNotice('');}
 function preview(e:React.FormEvent){e.preventDefault();setError('');try{const entered=candidates.filter(a=>values[a.id]?.value.trim());if(!entered.length||entered.length>100)throw Error('Enter weights for 1–100 animals. Blank rows are skipped.');const rows=entered.map(a=>{const v=values[a.id];validateWeight({date,session:name,unit:v.unit,originalValue:Number(v.value)},Number(year));if(weights.some(w=>w.animalId===a.id&&w.date===date))throw Error(label(a)+' already has a weight on this date. Review the existing record.');if((a.dob&&date<a.dob)||(statusAt(a,date)!=='Active'&&!a.statusEvents?.some(e=>e.date===date&&e.status!=='Active')))throw Error(label(a)+' was not active on this date, or its exit date needs review.');return {id:crypto.randomUUID(),animalId:a.id,originalValue:Number(v.value),unit:v.unit};});setReview(rows);}catch(e){setError((e as Error).message)}}
 async function request(action:string,data:any){const r=await fetch('/api/flock/weight-sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({year,action,data})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);return d;}
 async function save(){setBusy(true);setError('');try{await request('create',{id:batchId,operationId,species:animals[0]?.species,date,name,rows:review});await onSaved();setOpen(false);setReview(null);setValues({});setBatchId('');setNotice('Weighing session saved.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function change(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await request(mode,{id:selected,operationId:changeId,species:animals[0]?.species,reason,expected:session.map(w=>({id:w.id,version:w.version}))});await onSaved();setMode('');setSelected('');setNotice('Session '+(mode==='void'?'voided':'restored')+'.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="my-5"><div className="flex flex-wrap items-center gap-3"><h3>Weighing sessions</h3><Button disabled={!editable||!candidates.length} onClick={start}>{batchId?'Resume batch entry':'Enter batch weights'}</Button></div><p className="hint">Enter up to 100 animals, review, then save the whole batch. Draft entries remain here while this view stays open; save before refreshing or leaving. Individual corrections remain available below.</p>{notice&&<p role="status">{notice}</p>}{batches.length?<div className="flex flex-wrap gap-2">{batches.map(id=>{const rows=weights.filter(w=>w.batchId===id);return <Button variant="outline" key={id} onClick={()=>{setSelected(id);setMode('');setError('');}}>{rows[0].session} · {rows[0].date} · {rows.filter(w=>!w.voided).length}/{rows.length} valid</Button>})}</div>:<p>No saved batch sessions in this view.</p>}
 <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="worksheet-dialog"><DialogHeader><DialogTitle>{review?'Review weighing session':'Batch weight entry'}</DialogTitle><DialogDescription>{review?name+' · '+date+' · '+review.length+' measurements':'Blank weight rows will not be saved. Search does not remove entered weights.'}</DialogDescription></DialogHeader>{review?<><div className="max-h-80 overflow-auto">{review.map(r=><p key={r.id}>{label(animals.find(a=>a.id===r.animalId)!)} · {r.originalValue} {r.unit}</p>)}</div><Button disabled={busy} variant="outline" onClick={()=>setReview(null)}>Back to entry</Button><Button disabled={busy} onClick={save}>{busy?'Saving…':'Save all '+review.length+' measurements'}</Button></>:<form onSubmit={preview}><WeightSpreadsheet history={history} animals={candidates} date={date} unit={unit} onApply={rows=>{if(rows.some(r=>values[r.animalId]?.value.trim()))throw Error("A reviewed animal already has a draft weight. Clear that draft entry first to avoid overwriting it.");setValues({...values,...Object.fromEntries(rows.map(r=>[r.animalId,{value:r.value,unit:r.unit}]))});setError('');}}/><div className="form-grid"><label>Session name<Input value={name} onChange={e=>setName(e.target.value)} maxLength={200} required/></label><label>Weighing date<Input type="date" value={date} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)} required/></label><label>Default unit for new entries<select value={unit} onChange={e=>setUnit(e.target.value)}><option>lb</option><option>kg</option></select></label><label>Find animal<Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, tag or EID"/></label></div><div className="animal-sheet-tools"><GroupFilter value={group} onChange={setGroup} date={date} species={animals[0]?.species} eligibleIds={candidates.map(a=>a.id)}/></div><EntrySheet columns={[{key:'animal',label:'Animal',readOnly:true},{key:'right',label:'Right tag',readOnly:true},{key:'left',label:'Left tag',readOnly:true},{key:'value',label:'Measured weight',type:'number'},{key:'unit',label:'Unit',options:['lb','kg']}]} rows={candidates.filter(a=>(!group||!membershipError&&!membershipLoading&&groupMembers(membershipEvents,group,date).has(a.id))&&[label(a),a.rightTag,a.leftTag,a.eid,displayId(a)].join(' ').toLowerCase().includes(query.toLowerCase())).map(a=>({id:a.id,animal:label(a),right:a.rightTag||'—',left:a.leftTag||'—',value:values[a.id]?.value||'',unit:values[a.id]?.unit||unit}))} onChange={rows=>setValues({...values,...Object.fromEntries(rows.map(r=>[r.id,{value:r.value,unit:r.unit}]))})}/>
<p>{Object.values(values).filter(v=>v.value.trim()).length} measurements entered</p><Button type="submit">Review batch</Button></form>}{error&&<p role="alert" className="error">{error}</p>}</DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v&&!busy)setSelected('')}}><DialogContent className="worksheet-dialog"><DialogHeader><DialogTitle>Saved weighing session</DialogTitle><DialogDescription>{session[0]?.session} · {session.length} measurements</DialogDescription></DialogHeader><Button variant="outline" onClick={exportSession}>Download session CSV</Button><div className="max-h-80 overflow-auto">{session.map(w=><p key={w.id}>{label(animals.find(a=>a.id===w.animalId)!)} · {w.date} · {w.originalValue} {w.unit} · {w.voided?'Voided':'Valid'}</p>)}</div>{editable&&(!mode?<div className="flex gap-2"><Button variant="outline" disabled={!session.some(w=>!w.voided)} onClick={()=>{setMode('void');setReason('');setChangeId(crypto.randomUUID())}}>Void valid measurements</Button><Button variant="outline" disabled={!session.some(w=>w.voided)} onClick={()=>{setMode('restore');setReason('');setChangeId(crypto.randomUUID())}}>Restore voided measurements</Button></div>:<form onSubmit={change}><p>{mode==='void'?'Void all currently valid measurements in this session.':'Restore all currently voided measurements in this session, including individually voided entries.'} Original values and history remain available.</p><label>Reason<Input value={reason} onChange={e=>setReason(e.target.value)} required maxLength={500}/></label><Button disabled={busy} type="submit">{busy?'Saving…':'Confirm '+mode}</Button><Button disabled={busy} type="button" variant="outline" onClick={()=>setMode('')}>Cancel</Button></form>)}{error&&<p role="alert" className="error">{error}</p>}</DialogContent></Dialog></section>;
}
