"use client";
import {useState} from 'react';
import {type Animal,label,displayId} from '@/lib/livestock';
import {parseCsv} from '@/lib/animal-import';
import {weightFields,weightHeaders,matchWeightHeader,weightImportRows,weightTemplate,type WeightField} from '@/lib/weight-import';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
type Row=ReturnType<typeof weightImportRows>[number];
export default function WeightSpreadsheet({animals,date,unit,onApply}:{animals:Animal[];date:string;unit:string;onApply:(rows:Row[])=>void}){
 const [grid,setGrid]=useState<string[][]>([]),[mapping,setMapping]=useState<WeightField[]>([]),[rows,setRows]=useState<Row[]|null>(null),[file,setFile]=useState<File|null>(null),[sheets,setSheets]=useState<string[]>([]),[sheet,setSheet]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 function loadGrid(data:string[][]){if(data.length>2001)throw Error('Use at most 2,000 spreadsheet rows. Save batches of up to 100 measurements.');setGrid(data);setMapping((data[0]||[]).map(matchWeightHeader));setRows(null);}
 async function excel(f:File,name:string){const {default:read}=await import('read-excel-file/browser');const data=await read(f,{sheet:name});loadGrid(data.map(r=>r.map(v=>v instanceof Date?v.toISOString().slice(0,10):String(v??''))).filter(r=>r.some(v=>v.trim())));}
 async function load(f:File){setBusy(true);setError('');setRows(null);setGrid([]);setSheets([]);try{if(f.size>10*1024*1024)throw Error('Choose a file under 10 MB.');setFile(f);if(f.name.toLowerCase().endsWith('.csv'))loadGrid(parseCsv(await f.text()));else if(f.name.toLowerCase().endsWith('.xlsx')){const {readSheetNames}=await import('read-excel-file/browser');const names=await readSheetNames(f);if(!names.length)throw Error('No worksheets found.');setSheets(names);setSheet(names[0]);await excel(f,names[0]);}else throw Error('Choose CSV or Excel .xlsx.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function review(){setError('');try{const next=weightImportRows(grid,mapping,animals,unit);if(!next.length)throw Error('No weight values found.');setRows(next);}catch(e){setError((e as Error).message)}}
 function apply(){setError('');try{if(!rows?.length||rows.length>100)throw Error('Keep 1–100 measurements for this batch.');const seen=new Set();for(const r of rows){if(!r.animalId)throw Error('Choose an animal for every unmatched row or remove it.');if(seen.has(r.animalId))throw Error('An animal appears twice. Remove the duplicate row.');seen.add(r.animalId);if(!Number.isFinite(Number(r.value))||Number(r.value)<=0||Number(r.value)>10000||!['lb','kg'].includes(r.unit))throw Error('Correct invalid weights or units.');if(r.date&&r.date!==date)throw Error('File dates must match the session date. Use a separate session for each date.');}onApply(rows);setRows(null);setGrid([]);setSheets([]);}catch(e){setError((e as Error).message)}}
 function download(){const url=URL.createObjectURL(new Blob([weightTemplate(animals)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='weighing-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <details className="my-4"><summary>Import weight spreadsheet / download template</summary><p className="hint">The template contains your animals and blank weights. Keep Animal ID unchanged, enter measured weights, then upload CSV or Excel. Identifier columns must agree; names or tags that match multiple animals need your selection. Blank weights are skipped. No scale-specific format is assumed.</p><Button type="button" variant="outline" onClick={download}>Download weighing template</Button><label>Weight file<Input type="file" accept=".csv,.xlsx" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void load(f);e.target.value='';}}/></label>{sheets.length>1&&<label>Worksheet<select value={sheet} disabled={busy} onChange={async e=>{setSheet(e.target.value);setBusy(true);setError('');try{await excel(file!,e.target.value)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{sheets.map(s=><option key={s}>{s}</option>)}</select></label>}{busy&&<p role="status">Reading spreadsheet…</p>}{grid.length>0&&!rows&&<><div className="form-grid">{grid[0].map((header,i)=><label key={i}>{header||'Column '+(i+1)}<select value={mapping[i]} onChange={e=>setMapping(mapping.map((v,n)=>n===i?e.target.value as WeightField:v))}>{weightFields.map(f=><option value={f} key={f}>{weightHeaders[f]}</option>)}</select></label>)}</div><Button type="button" disabled={busy} onClick={review}>Review spreadsheet</Button></>}{rows&&<><p>{rows.length} nonblank measurements. Session date: {date||'choose above'}.</p><div className="max-h-80 overflow-auto">{rows.map((r,i)=><div className="border rounded p-2 my-2" key={r.sourceRow}><p>Row {r.sourceRow} · {r.source}{!r.animalId?' · '+r.matchNote:''}{r.date?' · '+r.date:''}</p><label>Matched animal<select value={r.animalId} onChange={e=>setRows(rows.map((v,n)=>n===i?{...v,animalId:e.target.value}:v))}><option value="">Choose animal</option>{animals.map(a=><option value={a.id} key={a.id}>{label(a)} · {displayId(a)}</option>)}</select></label><label>Weight<Input type="number" step="any" value={r.value} onChange={e=>setRows(rows.map((v,n)=>n===i?{...v,value:e.target.value}:v))}/></label><label>Unit<select value={r.unit} onChange={e=>setRows(rows.map((v,n)=>n===i?{...v,unit:e.target.value}:v))}>{!['lb','kg'].includes(r.unit)&&<option value={r.unit}>{r.unit||'Choose unit'}</option>}<option>lb</option><option>kg</option></select></label><Button type="button" variant="outline" onClick={()=>setRows(rows.filter((_,n)=>n!==i))}>Remove row</Button></div>)}</div><Button type="button" variant="outline" onClick={()=>setRows(null)}>Back to columns</Button><Button type="button" onClick={apply}>Add reviewed rows to batch</Button></>}{error&&<p role="alert" className="error">{error}</p>}</details>;
}
