"use client";
import {useState} from 'react';
import {type Animal,type Weight,label,adg} from '@/lib/livestock';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function WeightWorkspace({animals,weights,history,year,editable,onSaved}:{animals:Animal[];weights:Weight[];history:any[];year:string;editable:boolean;onSaved:()=>Promise<void>}){
 const [showVoided,setShowVoided]=useState(false),[selected,setSelected]=useState<Weight|null>(null),[action,setAction]=useState('weight-edit'),[operationId,setOperationId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const rows=weights.filter(w=>(year==='all'||w.date.startsWith(year))&&animals.some(a=>a.id===w.animalId)&&(showVoided||!w.voided));
 function open(w:Weight,mode:string){setSelected(w);setAction(mode);setOperationId(crypto.randomUUID());setError('');}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const response=await fetch('/api/flock/weights',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({year,action,data:{id:selected!.id,version:selected!.version,operationId,date:f.get('date'),originalValue:Number(f.get('value')),unit:f.get('unit'),session:f.get('session'),reason:f.get('reason')}})});const result=await response.json() as any;if(!response.ok)throw Error(result.error);await onSaved();setSelected(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><p className="hint">Voided measurements stay in history but do not count toward growth or latest weight. A voided record keeps its animal/date reserved; restore and correct it instead of entering a duplicate.</p><label><input type="checkbox" checked={showVoided} onChange={e=>setShowVoided(e.target.checked)}/> Show voided weights</label><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr>{['Animal','Date','Measured weight','Session','Latest ADG','Actions'].map(v=><th key={v} className="p-2">{v}</th>)}</tr></thead><tbody>{rows.map(w=>{const animal=animals.find(a=>a.id===w.animalId)!;const gain=adg(weights.filter(v=>!v.voided&&v.animalId===animal.id));return <tr key={w.id}><td className="p-2">{label(animal)}</td><td className="p-2">{w.date}</td><td className="p-2">{w.originalValue} {w.unit}{w.voided&&<strong> · Voided</strong>}</td><td className="p-2">{w.session}</td><td className="p-2">{gain===null?'Needs two dates':gain.toFixed(3)+' lb/day'}</td><td className="p-2"><Button variant="outline" onClick={()=>open(w,'history')}>History</Button>{editable&&!animal.archivedAt&&(w.voided?<Button variant="outline" onClick={()=>open(w,'weight-restore')}>Restore</Button>:<><Button variant="outline" onClick={()=>open(w,'weight-edit')}>Correct</Button><Button variant="outline" onClick={()=>open(w,'weight-void')}>Void</Button></>)}</td></tr>})}</tbody></table></div>{!rows.length&&<p className="empty">No measured weights in this view.</p>}
 <Dialog open={!!selected} onOpenChange={v=>{if(!v&&!busy)setSelected(null)}}><DialogContent><DialogHeader><DialogTitle>{action==='history'?'Weight history':action==='weight-edit'?'Correct weight':action==='weight-void'?'Void weight':'Restore weight'}</DialogTitle><DialogDescription>{selected?label(animals.find(a=>a.id===selected.animalId)!)+' · '+selected.date:''}</DialogDescription></DialogHeader>{selected&&(action==='history'?<div><p>Current record: {selected.originalValue} {selected.unit} · {selected.date} · {selected.voided?'Voided':'Valid'}</p>{history.filter(h=>h.action?.startsWith('weight-')).filter(h=>{try{return JSON.parse(h.after).id===selected.id}catch{return false}}).map(h=>{const before=JSON.parse(h.before),after=JSON.parse(h.after);return <p key={h.operationId} className="my-3"><strong>{h.action.replace('weight-','')} · {new Date(h.createdAt).toLocaleString()}</strong><br/>{before.originalValue} {before.unit} on {before.date} → {after.originalValue} {after.unit} on {after.date}<br/>{before.session} → {after.session}<br/>{h.reason}</p>})}<p className="hint">Original measurements are retained in the before/after history when corrected or voided.</p></div>:<form onSubmit={save}>{action==='weight-edit'&&<div className="form-grid"><label>Date<Input name="date" type="date" defaultValue={selected.date} required/></label><label>Measured weight<Input name="value" type="number" step="any" min="0.001" max="10000" defaultValue={selected.originalValue} required/></label><label>Unit<select name="unit" defaultValue={selected.unit}><option>lb</option><option>kg</option></select></label><label>Session<Input name="session" defaultValue={selected.session} maxLength={200} required/></label></div>}<label>Reason<Input name="reason" required maxLength={500}/></label>{error&&<p role="alert" className="error">{error}</p>}<Button disabled={busy} type="submit">{busy?'Saving…':action==='weight-edit'?'Save correction':action==='weight-void'?'Void measurement':'Restore measurement'}</Button></form>)}</DialogContent></Dialog></>;
}
