import type {Animal} from './livestock.ts';
export type Share={breed:string;percent:number};
export type Project={id:string;version:number;name:string;targets:Share[];gestationMin:number|null;gestationMax:number|null;flushingDays:number|null;crayonDays:number|null};
export function shares(value:unknown,complete=false):Share[]{if(!Array.isArray(value)||value.length>20)throw Error('Enter up to 20 breed percentages.');const seen=new Set<string>();let total=0;for(const row of value){if(!row||typeof row.breed!=='string'||!row.breed.trim()||row.breed.length>100||seen.has(row.breed.trim().toLowerCase()))throw Error('Enter distinct breed names.');seen.add(row.breed.trim().toLowerCase());if(typeof row.percent!=='number'||!Number.isFinite(row.percent)||row.percent<=0||row.percent>100||Math.abs(row.percent*100-Math.round(row.percent*100))>1e-6)throw Error('Percentages must be positive with at most two decimals.');total+=Math.round(row.percent*100);}if(total>10000||complete&&total!==10000)throw Error(complete?'Target percentages must total 100%.':'Known percentages cannot exceed 100%.');return value.map(v=>({breed:v.breed.trim(),percent:v.percent}));}
export function validateProject(p:Project){if(!p.name?.trim()||p.name.length>200)throw Error('Enter a project name.');shares(p.targets,true);for(const k of ['gestationMin','gestationMax','flushingDays','crayonDays'] as const){const n=p[k];if(n!==null&&(!Number.isInteger(n)||n<1||n>730))throw Error('Timing values must be blank or whole days from 1 to 730.');}if((p.gestationMin===null)!==(p.gestationMax===null)||p.gestationMin!==null&&p.gestationMax!<p.gestationMin)throw Error('Enter both gestation bounds in increasing order, or leave both blank.');}
export function composition(a:Animal):Share[]{try{return shares(JSON.parse(a.pedigreeInfo||'{}').breedComposition||[])}catch{return []}}
export function offspring(sire:Animal,dam:Animal){const parents=[composition(sire),composition(dam)];if(parents.some(rows=>Math.abs(rows.reduce((sum,r)=>sum+r.percent,0)-100)>.001))return [];const result=new Map<string,Share>();for(const row of parents.flat()){const key=row.breed.toLowerCase(),old=result.get(key);result.set(key,{breed:old?.breed||row.breed,percent:(old?.percent||0)+row.percent/2})}return [...result.values()];}
export function targetDistance(actual:Share[],targets:Share[]){if(Math.abs(actual.reduce((s,r)=>s+r.percent,0)-100)>.001)return null;const keys=new Set([...actual,...targets].map(r=>r.breed.toLowerCase()));return [...keys].reduce((s,k)=>s+Math.abs((actual.find(r=>r.breed.toLowerCase()===k)?.percent||0)-(targets.find(r=>r.breed.toLowerCase()===k)?.percent||0)),0)/2;}
export function addDays(date:string,days:number){return new Date(Date.parse(date+'T12:00:00Z')+days*86400000).toISOString().slice(0,10)}
