const enc=new TextEncoder();
export const sessionCookie='flock_access';
export const sessionSeconds=12*60*60;
export const hex=(bytes:Uint8Array)=>Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');
export async function digest(value:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value))))}
export async function passwordHash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return hex(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations:100000},key,256)))}
export async function checkPassword(password:string,stored:string){const [salt,expected]=stored.split(':');if(!salt||!expected||expected.length!==64)return false;const actual=await passwordHash(password,salt);let diff=0;for(let i=0;i<64;i++)diff|=actual.charCodeAt(i)^expected.charCodeAt(i);return diff===0}
export function readSession(request:Request){const value=request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(sessionCookie+'='))?.slice(sessionCookie.length+1)||'';return /^[a-f0-9]{64}$/.test(value)?value:''}
export function sessionHeader(token:string,secure:boolean,age=sessionSeconds){return `${sessionCookie}=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${age}${secure?'; Secure':''}`}
export function sameOrigin(request:Request,origin:string){return request.headers.get('origin')===origin&&request.headers.get('sec-fetch-site')!=='cross-site'}
export function gatePage(message=''){
 const safe=message.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]!));
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Unlock · Clarkson’s Flock</title><style>body{margin:0;background:#eff3ef;color:#23392c;font:16px system-ui;display:grid;min-height:100dvh;place-items:center}main{box-sizing:border-box;width:min(420px,calc(100% - 32px));padding:32px;background:white;border:1px solid #d8e0d9;border-radius:16px;box-shadow:0 12px 40px #23392c12}h1{font-size:26px;margin:0 0 12px}p{line-height:1.5;color:#526459}label{display:block;font-weight:600;margin-top:24px}input,button{box-sizing:border-box;width:100%;padding:13px;margin-top:10px;border:1px solid #a6b7aa;border-radius:7px;font:inherit}button{background:#28543c;color:white;cursor:pointer;font-weight:650}small{display:block;margin-top:22px;color:#526459}[role=alert]{color:#9a2e21}</style></head><body><main><h1>Clarkson’s Flock</h1><p>Enter the shared password to open the farm dashboard. No account needed.</p>${safe?`<p role="alert">${safe}</p>`:''}<form method="post" action="/access/unlock"><label for="password">Dashboard password</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="128" autofocus><button type="submit">Unlock dashboard</button></form><small>Only unlock on a device you trust. Use Lock dashboard when finished on a shared computer.</small></main></body></html>`;
}
