import {withReadEpoch,withWriteEpoch} from '@/db/recovery-context';
import {rawDb} from '@/db';
import {isUuid} from '@/lib/lambing';
import {validateReportFilter} from '@/lib/report-filters';
export const dynamic='force-dynamic';
async function handleGET(){try{const r=await rawDb().prepare("SELECT data FROM farm_records WHERE kind='report-preset'").all<any>();return Response.json({presets:r.results.map(r=>JSON.parse(r.data))},{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'Saved reports unavailable.'},{status:503})}}
async function handlePOST(req:Request){try{const b:any=await req.json(),p=b.data;if(!p||!isUuid(p.id)||!isUuid(b.operationId)||!['Sheep','Goats'].includes(p.species)||typeof p.name!=='string'||!p.name.trim()||p.name.length>100||typeof p.archived!=='boolean'||!Number.isInteger(p.version)||p.version<0||(!/^\d{4}$/.test(String(b.year))||Number(b.year)<1900||Number(b.year)>new Date().getFullYear()+10))throw Error('Enter a valid saved report name and choose a year.');validateReportFilter(p.filter);const db=rawDb(),prior:any=await db.prepare('SELECT recordId FROM farm_history WHERE operationId=?').bind(b.operationId).first();if(prior){if(prior.recordId!==p.id)throw Error('Change identifier reused.');return Response.json({saved:true})}const old:any=await db.prepare('SELECT * FROM farm_records WHERE id=?').bind(p.id).first();if(old&&(old.kind!=='report-preset'||old.species!==p.species))throw Error('Invalid saved report.');if((old?.version||0)!==p.version)return Response.json({error:'Saved report changed elsewhere. Reload.'},{status:409});const next={id:p.id,name:p.name.trim(),species:p.species,filter:p.filter,archived:p.archived,version:p.version+1},data=JSON.stringify(next),now=new Date().toISOString();const statements=old?[db.prepare("INSERT INTO animals(id,species,sex,origin,firstYear,createdAt) SELECT NULL,'Sheep','Unknown','Purchased',1900,'' WHERE NOT EXISTS(SELECT 1 FROM farm_records WHERE id=? AND version=?)").bind(p.id,p.version),db.prepare('UPDATE farm_records SET data=?,version=version+1 WHERE id=? AND version=?').bind(data,p.id,p.version)]:[db.prepare("INSERT INTO farm_records(id,kind,species,date,data,version) VALUES (?,'report-preset',?,?,?,1)").bind(p.id,p.species,now.slice(0,10),data)];statements.push(db.prepare('INSERT INTO farm_history(operationId,recordId,before,after,createdAt) VALUES (?,?,?,?,?)').bind(b.operationId,p.id,old?.data||'{}',data,now));await db.batch(statements);return Response.json({saved:true});}catch(e){return Response.json({error:(e as Error).message},{status:400})}}

export const GET=withReadEpoch(handleGET);

export const POST=withWriteEpoch(handlePOST);
