import {rawDb} from '@/db';
import {isUuid} from '@/lib/lambing';
import {validateFields,type CustomField} from '@/lib/custom-fields';
export const dynamic='force-dynamic';
export const settingsId='00000000-0000-0000-0000-000000000001';
export async function GET(){try{const r:any=await rawDb().prepare('SELECT data,version FROM farm_records WHERE id=?').bind(settingsId).first();return Response.json(r?{...JSON.parse(r.data),version:r.version}:{fields:[],version:0},{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'Settings unavailable.'},{status:503})}}
export async function POST(req:Request){try{
 const b:any=await req.json();if(b.year==='all'||!Number.isInteger(Number(b.year))||Number(b.year)<1900||Number(b.year)>new Date().getFullYear()+10||!isUuid(b.operationId))throw Error('Select a year before changing settings.');validateFields(b.fields);
 const db=rawDb(),old:any=await db.prepare('SELECT * FROM farm_records WHERE id=?').bind(settingsId).first(),prior=await db.prepare('SELECT recordId FROM farm_history WHERE operationId=?').bind(b.operationId).first<any>();if(prior){if(prior.recordId!==settingsId)throw Error('Change identifier reused.');return Response.json({saved:true})}if((old?.version||0)!==b.version)return Response.json({error:'Settings changed elsewhere. Reload.'},{status:409});
 const before=old?JSON.parse(old.data):{fields:[]};for(const f of before.fields as CustomField[]){const next=b.fields.find((v:CustomField)=>v.id===f.id);if(!next||next.type!==f.type)throw Error('Existing fields must keep their ID and type. Archive a field instead of deleting it.');}
 const rows=await db.prepare('SELECT pedigreeInfo,version FROM animals').all<any>();for(const f of b.fields as CustomField[])if(f.type==='Choice')for(const a of rows.results){const value=JSON.parse(a.pedigreeInfo||'{}').customValues?.[f.id];if(value!==undefined&&value!==null&&!f.choices.includes(value))throw Error('A removed choice is still used by an animal: '+f.name);}
 const animalGuard=db.prepare("INSERT INTO animals(id,species,sex,origin,firstYear,createdAt) SELECT NULL,'Sheep','Unknown','Purchased',1900,'' WHERE ? != (SELECT COALESCE(SUM(version),0) FROM animals)").bind(rows.results.reduce((n,a)=>n+a.version,0));const now=new Date().toISOString(),data=JSON.stringify({fields:b.fields,version:b.version+1});if(old){const r=await db.batch([animalGuard,db.prepare('INSERT INTO farm_history(operationId,recordId,before,after,createdAt) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM farm_records WHERE id=? AND version=?)').bind(b.operationId,settingsId,old.data,data,now,settingsId,b.version),db.prepare('UPDATE farm_records SET data=?,version=version+1 WHERE id=? AND version=?').bind(data,settingsId,b.version)]);if(r[2].meta.changes!==1)return Response.json({error:'Settings changed elsewhere.'},{status:409});}else await db.batch([animalGuard,db.prepare("INSERT INTO farm_records(id,kind,species,date,data,version) VALUES (?,'settings','Shared',?,?,1)").bind(settingsId,now.slice(0,10),data),db.prepare('INSERT INTO farm_history(operationId,recordId,before,after,createdAt) VALUES (?,?,?,?,?)').bind(b.operationId,settingsId,'{}',data,now)]);return Response.json({saved:true});
 }catch(e){return Response.json({error:(e as Error).message},{status:400})}}
