import {env} from 'cloudflare:workers';
import {rawDb} from '@/db';
import {isUuid} from '@/lib/lambing';
import {eventKinds} from '@/lib/farm-events';
import {fileType} from '@/lib/animal-files';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const url=new URL(req.url),id=url.searchParams.get('event'),fileId=url.searchParams.get('file');if(!isUuid(id)||!isUuid(fileId))throw Error('Invalid file reference.');const row:any=await rawDb().prepare('SELECT data FROM farm_records WHERE id=?').bind(id).first(),file=row&&JSON.parse(row.data).attachments?.find((f:any)=>f.id===fileId&&!f.removedAt);if(!file)return Response.json({error:'Document not found.'},{status:404});const object=await env.BUCKET?.get('event-files/'+id+'/'+fileId);if(!object)return Response.json({error:'Document bytes unavailable.'},{status:404});return new Response(object.body,{headers:{'Content-Type':file.type,'Content-Disposition':'inline; filename="'+file.name.replace(/[^a-zA-Z0-9._ -]/g,'_')+'"','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}})}catch{return Response.json({error:'Document could not be loaded.'},{status:503})}}
export async function POST(req:Request){try{
 const form=await req.formData(),id=String(form.get('eventId')),op=String(form.get('operationId')),action=String(form.get('action')),version=Number(form.get('version')),year=String(form.get('year'));
 if(!isUuid(id)||!isUuid(op)||!['upload','remove','restore'].includes(action))throw Error('Invalid document action.');const db=rawDb(),row:any=await db.prepare('SELECT * FROM farm_records WHERE id=?').bind(id).first();if(!row||!eventKinds.includes(row.kind)||year==='all'||row.date.slice(0,4)!==year)throw Error('Open the event in its recorded year.');const before=JSON.parse(row.data);if(before.voided)throw Error('Restore the event before changing its documents.');const prior:any=await db.prepare('SELECT recordId FROM farm_history WHERE operationId=?').bind(op).first();if(prior){if(prior.recordId!==id)throw Error('Change identifier reused.');return Response.json({saved:true})}if(row.version!==version)return Response.json({error:'Event changed elsewhere. Reload.'},{status:409});
 const files=[...(before.attachments||[])],now=new Date().toISOString();if(action==='upload'){const file=form.get('file');if(!(file instanceof File)||!file.size||file.size>10*1024*1024||files.length>=100)throw Error('Choose a file up to 10 MB; each event supports 100 documents.');const bytes=new Uint8Array(await file.arrayBuffer()),type=fileType(bytes);if(!type)throw Error('Use PDF, JPG, PNG or WebP.');if(!env.BUCKET)throw Error('File storage unavailable.');await env.BUCKET.put('event-files/'+id+'/'+op,bytes,{httpMetadata:{contentType:type}});files.push({id:op,name:file.name.slice(0,200),type,size:file.size,uploadedAt:now});}else{const index=files.findIndex(f=>f.id===String(form.get('fileId')));if(index<0)throw Error('Document not found.');files[index]={...files[index]};if(action==='remove')files[index].removedAt=now;else delete files[index].removedAt;}
 const next=JSON.stringify({...before,attachments:files,version:version+1}),result=await db.batch([db.prepare('INSERT INTO farm_history(operationId,recordId,before,after,createdAt) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM farm_records WHERE id=? AND version=?)').bind(op,id,row.data,next,now,id,version),db.prepare('UPDATE farm_records SET data=?,version=version+1 WHERE id=? AND version=?').bind(next,id,version)]);if(result[1].meta.changes!==1)return Response.json({error:'Event changed elsewhere. Retry after reloading.'},{status:409});return Response.json({saved:true});
 }catch(e){return Response.json({error:(e as Error).message},{status:400})}}
